import { T, t } from "../i18n";

/** Release notes. Newest first; `date` is ISO so it sorts and localises
 *  predictably. The header dot lights up while the newest entry is unread. */
export const RELEASES = [
  {
    date: "2026-09-30",
    title: { en: "The first rashguard samples go on trial", fr: "Les premiers échantillons de rashguards à l'essai", ja: "ラッシュガードの最初のサンプルが試用フェーズへ", pt: "As primeiras amostras de rashguard entram em teste", ro: "Primele mostre de rashguard intră în testare" },
    items: [
      { en: "The first Kintsugi Fighter rashguard samples are being worn and tested on the mats — a banner on the home page says so, and says nothing is on sale yet", fr: "Les premiers échantillons de rashguards Kintsugi Fighter sont portés et testés sur le tatami — une bannière sur la page d'accueil l'annonce, et précise que rien n'est encore en vente", ja: "Kintsugi Fighterラッシュガードの最初のサンプルを、マットの上で実際に着用・テストしています。トップページのバナーでお知らせしており、まだ何も販売していないことも明記しています", pt: "As primeiras amostras dos rashguards Kintsugi Fighter estão sendo vestidas e testadas no tatame — um banner na página inicial avisa, e deixa claro que nada está à venda ainda", ro: "Primele mostre de rashguard Kintsugi Fighter sunt purtate și testate pe saltea — un banner pe pagina principală anunță asta și precizează că nimic nu este încă de vânzare" },
      { en: "On the shop page, the long-sleeve rashguard is marked as available for sampling, not for sale", fr: "Sur la page boutique, le rashguard manches longues est indiqué comme disponible pour des essais, pas à la vente", ja: "ショップページでは、長袖ラッシュガードに「サンプル試用中・販売前」と表示しています", pt: "Na página da loja, o rashguard de manga longa aparece como disponível para teste, não para venda", ro: "Pe pagina magazinului, rashguard-ul cu mânecă lungă este marcat ca disponibil pentru testare, nu pentru vânzare" },
      { en: "A new tester-feedback section under the rashguards will carry what the people wearing the samples tell us, in their own words and marked as free samples", fr: "Une nouvelle section de retours des testeurs, sous les rashguards, publiera ce que nous disent les personnes qui portent les échantillons, avec leurs propres mots et en précisant qu'il s'agit d'échantillons gratuits", ja: "ラッシュガードの下に、サンプル着用者の声を本人の言葉のまま掲載するテスター欄を新設しました。無償サンプルであることも明記します", pt: "Uma nova seção de opiniões dos testadores, abaixo dos rashguards, vai trazer o que nos dizem as pessoas que usam as amostras, com as próprias palavras e indicando que são amostras gratuitas", ro: "O nouă secțiune cu părerile testerilor, sub rashguard-uri, va publica ce ne spun cei care poartă mostrele, cu propriile lor cuvinte și cu mențiunea că sunt mostre gratuite" },
      { en: "The Kintsugi Gi moves to Q2 2027; the rest of the first drop is still expected in Q1 2027", fr: "Le Kintsugi Gi passe au deuxième trimestre 2027 ; le reste de la première collection est toujours prévu au premier trimestre 2027", ja: "Kintsugi Giの発売予定を2027年第2四半期に変更しました。ファーストドロップのその他のアイテムは引き続き2027年第1四半期の予定です", pt: "O Kintsugi Gi passa para o segundo trimestre de 2027; o restante da primeira coleção continua previsto para o primeiro trimestre de 2027", ro: "Kintsugi Gi se mută în al doilea trimestru din 2027; restul primei colecții este în continuare estimat pentru primul trimestru din 2027" },
    ],
  },
  {
    date: "2026-08-30",
    title: { en: "The gi, shorts and belt join the first drop", fr: "Le kimono, les shorts et la ceinture rejoignent la première collection", ja: "柔術衣・ショーツ・帯がファーストドロップに加わりました", pt: "O kimono, os shorts e a faixa entram na primeira coleção", ro: "Kimonoul, pantalonii scurți și centura se alătură primei colecții" },
    items: [
      { en: "The Kintsugi Gi is on the shop page now, in black, blue, pink and white, shown front, side and back with its own spec panel — it used to sit further down under \"to be announced\"; there is artwork and a price range for it now, so it has moved up between the rashguards and the t-shirts", fr: "Le Kintsugi Gi est désormais présent sur la page boutique, en noir, bleu, rose et blanc, montré de face, de profil et de dos, avec son propre panneau de caractéristiques — il figurait plus bas sous « à annoncer » ; il existe maintenant un visuel et une fourchette de prix pour lui, il se trouve donc désormais entre les rashguards et les t-shirts", ja: "Kintsugi Giをショップページに掲載しました。ブラック・ブルー・ピンク・ホワイトの4色を、前面・側面・背面で確認でき、専用のスペック表も添えています。これまでは下段の「近日発表」に置いていましたが、デザインと価格帯が決まったため、ラッシュガードとTシャツの間に移しました", pt: "O Kintsugi Gi agora está na página da loja, em preto, azul, rosa e branco, mostrado de frente, de lado e de costas, com seu próprio painel de especificações — antes ficava mais abaixo, sob \"a ser anunciado\"; agora há arte e uma faixa de preço para ele, então subiu para entre os rashguards e as camisetas", ro: "Kintsugi Gi este acum pe pagina magazinului, în negru, albastru, roz și alb, arătat față, profil și spate, cu propriul panou de specificații — stătea mai jos, la „urmează să fie anunțat”; acum există grafică și un interval de preț pentru el, așa că a urcat între rashguard-uri și tricouri" },
      { en: "The pink colourway is cut for women; that's called out on its card, the same way the rashguard's two cuts are", fr: "Le coloris rose est coupé pour femme ; c'est indiqué sur sa fiche, de la même façon que les deux coupes du rashguard", ja: "ピンクは女性用カットです。ラッシュガードの2種類のカット表示と同じ方式で、カード上に明記しています", pt: "A cor rosa tem corte feminino; isso é indicado no card, da mesma forma que os dois cortes do rashguard", ro: "Culoarea roz are croială pentru femei; asta este menționat pe card, la fel cum sunt cele două croieli ale rashguard-ului" },
      { en: "Two Kintsugi NoGi shorts have joined them under the rashguards: the 2-in-1 build with a compression liner sewn in, and the compression layer sold on its own for anyone who already has an outer short — shown front and back with a shared spec panel", fr: "Deux shorts Kintsugi NoGi les ont rejoints sous les rashguards : la version 2-en-1 avec doublure de compression intégrée, et la couche de compression seule pour qui possède déjà un short extérieur — montrés de face et de dos avec un panneau de caractéristiques commun", ja: "Kintsugi NoGiショーツ2型もラッシュガードの下に加わりました。コンプレッションライナーを内蔵した2-in-1と、アウターショーツをお持ちの方向けのコンプレッションレイヤー単体です。前面と背面で確認でき、共通のスペック表を添えています", pt: "Dois shorts Kintsugi NoGi entraram junto, abaixo dos rashguards: a versão 2 em 1 com forro de compressão costurado, e a camada de compressão isolada para quem já tem um short externo — mostrados de frente e de costas com um painel de especificações compartilhado", ro: "Doi pantaloni scurți Kintsugi NoGi li s-au alăturat sub rashguard-uri: varianta 2-în-1 cu strat de compresie cusut în interior, și stratul de compresie de sine stătător pentru cine are deja un pantalon exterior — arătați față și spate, cu un panou de specificații comun" },
      { en: "The Kintsugi Belt closes out the shop — one photograph across all five adult ranks, white through black — with its own spec panel; its price moved from the old, undated 25 – 35 SGD to a first-drop 40 – 60 SGD", fr: "La Ceinture Kintsugi clôture la boutique — une seule photographie couvrant les cinq grades adultes, du blanc au noir — avec son propre panneau de caractéristiques ; son prix passe de l'ancien 25 – 35 SGD non daté à 40 – 60 SGD pour cette première collection", ja: "Kintsugi Beltがショップの最後を締めくくります。白から黒まで成人の5階級すべてを1枚の写真で掲載し、専用のスペック表を添えています。価格は従来の未定の25〜35 SGDから、ファーストドロップとして40〜60 SGDに変更しました", pt: "A Faixa Kintsugi fecha a loja — uma única fotografia com todas as cinco faixas adultas, da branca à preta — com seu próprio painel de especificações; o preço passou dos antigos 25 – 35 SGD sem data para 40 – 60 SGD nesta primeira coleção", ro: "Centura Kintsugi încheie magazinul — o singură fotografie cu toate cele cinci centuri pentru adulți, de la albă la neagră — cu propriul panou de specificații; prețul a trecut de la vechiul 25 – 35 SGD nedatat la 40 – 60 SGD pentru această primă colecție" },
      { en: "The undated \"rest of the range\" grid is gone — everything in the shop now has artwork, a price and the same first-quarter-2027 date", fr: "La grille non datée « le reste de la gamme » a disparu — tout ce qui figure désormais dans la boutique a un visuel, un prix et la même date, le premier trimestre 2027", ja: "未定だった「その他のラインナップ」のグリッドは廃止しました。ショップに掲載されているものはすべて、デザイン・価格・2027年第1四半期という同じ発売時期を備えています", pt: "A grade não datada \"o resto da linha\" foi removida — tudo na loja agora tem arte, preço e a mesma data, o primeiro trimestre de 2027", ro: "Grila nedatată „restul gamei” a dispărut — tot ce se află acum în magazin are grafică, preț și aceeași dată, primul trimestru din 2027" },
      { en: "Nothing has changed about what the site claims: still no product, no shop and no account, and the first run — rashguards, shorts, gi, tees and belt together — is still expected in the first quarter of 2027", fr: "Rien ne change quant à ce que le site affirme : toujours aucun produit, aucune boutique et aucun compte, et la première série — rashguards, shorts, kimono, t-shirts et ceinture ensemble — est toujours attendue au premier trimestre 2027", ja: "サイトが述べている内容に変更はありません。製品も、ショップも、アカウントも依然としてなく、ラッシュガード・ショーツ・柔術衣・Tシャツ・帯をあわせた初回生産は2027年第1四半期を予定しています", pt: "Nada mudou quanto ao que o site afirma: continua sem produto, sem loja e sem conta, e a primeira tiragem — rashguards, shorts, kimono, camisetas e faixa juntos — continua prevista para o primeiro trimestre de 2027", ro: "Nu s-a schimbat nimic din ce afirmă site-ul: în continuare fără produs, fără magazin și fără cont, iar prima serie — rashguard-uri, pantaloni scurți, kimono, tricouri și centură împreună — este în continuare așteptată în primul trimestru din 2027" },
    ],
  },
  {
    date: "2026-08-23",
    title: { en: "Photographs, a bigger layout, and sound", fr: "Des photographies, une mise en page plus grande, et du son", ja: "写真、より大きなレイアウト、そして音", pt: "Fotografias, um layout maior e som", ro: "Fotografii, un aspect mai mare și sunet" },
    items: [
      { en: "The site has photographs for the first time — the crest on the back of a gi, a grip fight up close, two people touching fists before a round — running the full width of the page rather than boxed inside it", fr: "Le site accueille ses premières photographies — le blason au dos d'un kimono, une prise de garde en gros plan, deux pratiquants qui se touchent le poing avant un round — affichées sur toute la largeur de la page plutôt qu'enfermées dans un cadre", ja: "サイトに初めて写真を導入しました。道着の背中の紋章、組み手の接写、ラウンド前に拳を合わせる二人 — いずれも枠に収めず、ページの幅いっぱいに配置しています", pt: "O site tem fotografias pela primeira vez — o brasão nas costas de um kimono, uma disputa de pegada de perto, dois praticantes batendo os punhos antes de um round — ocupando toda a largura da página em vez de ficarem dentro de uma caixa", ro: "Site-ul are pentru prima dată fotografii — emblema de pe spatele kimonoului, o luptă de prize în prim-plan, doi practicanți care își ating pumnii înainte de o rundă — pe toată lățimea paginii, nu închise într-un chenar" },
      { en: "Sections now run edge to edge, headlines are set two to three times larger, and every button is bigger and easier to hit", fr: "Les sections s'étendent désormais d'un bord à l'autre, les titres sont deux à trois fois plus grands, et chaque bouton est plus grand et plus facile à atteindre", ja: "各セクションが画面の端から端まで広がり、見出しは従来の2〜3倍の大きさになりました。ボタンもすべて大きくなり、押しやすくなっています", pt: "As seções agora vão de ponta a ponta, os títulos estão duas a três vezes maiores, e todos os botões ficaram maiores e mais fáceis de acertar", ro: "Secțiunile se întind acum de la un capăt la altul, titlurile sunt de două-trei ori mai mari, iar fiecare buton este mai mare și mai ușor de atins" },
      { en: "Images that carry a headline are printed in two tones instead of full colour, so the text stays readable on top of them and the site keeps one palette rather than five", fr: "Les images qui portent un titre sont tirées en bichromie plutôt qu'en couleurs, afin que le texte reste lisible par-dessus et que le site conserve une seule palette au lieu de cinq", ja: "見出しが重なる写真は、フルカラーではなく二色刷りにしています。文字が読みやすくなり、サイト全体の色数も5系統から1系統に整いました", pt: "As imagens que carregam um título são impressas em duas tonalidades em vez de cores plenas, para que o texto continue legível sobre elas e o site mantenha uma paleta em vez de cinco", ro: "Imaginile peste care stă un titlu sunt tipărite în două tonuri, nu în culori depline, ca textul să rămână lizibil deasupra lor și site-ul să păstreze o singură paletă, nu cinci" },
      { en: "The technique map preview has moved next to the link that opens it, with a legend naming the three kinds of technique", fr: "L'aperçu de la carte des techniques a été déplacé à côté du lien qui l'ouvre, avec une légende nommant les trois types de technique", ja: "テクニックマップのプレビューを、マップを開くリンクの隣に移動しました。3種類の技術を示す凡例も添えています", pt: "A prévia do mapa de técnicas foi movida para junto do link que o abre, com uma legenda nomeando os três tipos de técnica", ro: "Previzualizarea hărții tehnicilor s-a mutat lângă linkul care o deschide, cu o legendă care numește cele trei tipuri de tehnică" },
      { en: "Our Story now opens with a photograph, matching the Mental Health page", fr: "La page Notre histoire s'ouvre désormais sur une photographie, comme la page Santé mentale", ja: "「私たちの物語」のページも写真から始まるようになり、「メンタルヘルス」のページと揃いました", pt: "A página Nossa História agora abre com uma fotografia, igual à página de Saúde Mental", ro: "Pagina Povestea noastră începe acum cu o fotografie, la fel ca pagina de Sănătate mintală" },
      { en: "The mission strip no longer appears on the mission page itself, where its \"Learn more\" link had nowhere left to go", fr: "Le bandeau mission ne s'affiche plus sur la page Mission elle-même, où son lien « En savoir plus » ne menait nulle part", ja: "ミッションの帯は、ミッションのページ自体には表示されなくなりました。そのページでは「詳しく見る」のリンクに移動先がなかったためです", pt: "A faixa da missão não aparece mais na própria página da missão, onde o link \"Saiba mais\" não tinha para onde ir", ro: "Banda misiunii nu mai apare chiar pe pagina misiunii, unde linkul „Află mai multe” nu mai avea unde să ducă" },
      { en: "Background music, with a speaker button in the header. It always starts off, so the button and the sound can never disagree — press it to play, press it again to stop. The track is only downloaded if you actually play it", fr: "Une musique de fond, avec un bouton haut-parleur dans l'en-tête. Elle démarre toujours à l'arrêt, si bien que le bouton et le son ne peuvent jamais se contredire : appuyez pour lancer, appuyez de nouveau pour arrêter. Le morceau n'est téléchargé que si vous le lisez réellement", ja: "背景音楽を追加し、ヘッダーのスピーカーボタンで操作できるようにしました。読み込み時は常に停止状態から始まるため、ボタンの表示と実際の音がずれることはありません。押すと再生、もう一度押すと停止します。音源は実際に再生した場合にのみ読み込まれます", pt: "Música de fundo, com um botão de alto-falante no cabeçalho. Ela sempre começa desligada, então o botão e o som nunca podem discordar — aperte para tocar, aperte de novo para parar. A faixa só é baixada se você realmente tocá-la", ro: "Muzică de fundal, cu un buton de difuzor în antet. Pornește întotdeauna oprită, așa că butonul și sunetul nu pot fi niciodată în dezacord — apeși ca să pornească, apeși din nou ca să se oprească. Piesa se descarcă doar dacă chiar o asculți" },
{ en: "Basic Concepts has been rebuilt around the four things jiu-jitsu is actually made of, in order — take it to the ground, pass the legs, pin and climb, submit — each with the reason it comes where it does and a photograph of the position beside it. Timing over force and tapping early stay, as advice on how to train the four", fr: "La page Concepts de base a été reconstruite autour des quatre éléments dont le jiu-jitsu est réellement fait, dans l'ordre — amener au sol, passer les jambes, immobiliser puis progresser, soumettre — chacun accompagné de la raison de sa place et d'une photographie de la position. Le timing plutôt que la force et taper tôt demeurent, comme conseils pour travailler ces quatre points", ja: "「基本概念」のページを、柔術を実際に構成する四つの要素を順に並べる形で作り直しました。寝技に持ち込む、脚を越える、抑えて上へ、極める。それぞれになぜその順序なのかの説明と、その局面の写真を添えています。「力よりタイミング」と「早めにタップ」は、四つをどう練習するかの助言として残しています", pt: "A página de Conceitos Básicos foi reconstruída em torno das quatro coisas de que o jiu-jitsu é realmente feito, em ordem — levar ao chão, passar as pernas, prender e subir, finalizar — cada uma com o motivo de estar onde está e uma fotografia da posição ao lado. Timing acima de força e bater cedo permanecem, como conselhos sobre como treinar os quatro", ro: "Pagina Concepte de bază a fost reconstruită în jurul celor patru lucruri din care este făcut de fapt jiu-jitsu, în ordine — du lupta la sol, treci de picioare, imobilizează și urcă, finalizează — fiecare cu motivul pentru care stă unde stă și cu o fotografie a poziției alături. Timingul în locul forței și bătutul din timp rămân, ca sfaturi despre cum antrenezi cele patru" },
{ en: "Two rashguards join the first drop and now open the shop — the Kintsugi Fighter design, cut long and short sleeve, shown front and back with its own spec panel. They used to sit further down under \"to be announced\"; there is artwork and a quarter for them now, so they have moved up and out of that list", fr: "Deux rashguards rejoignent la première collection et ouvrent désormais la boutique — le design Kintsugi Fighter, en manches longues et manches courtes, présenté de face et de dos avec son propre panneau de caractéristiques. Ils figuraient plus bas sous « à annoncer » ; il existe maintenant un visuel et un trimestre pour eux, ils quittent donc cette liste", ja: "ラッシュガード2型がファーストドロップに加わり、ショップの先頭に並びました。Kintsugi Fighterのデザインを長袖と半袖で、前面と背面ともに掲載し、専用のスペック表も添えています。これまでは下段の「近日発表」に置いていましたが、デザインと発売時期が決まったため、そのリストから移しました", pt: "Dois rashguards entram na primeira coleção e agora abrem a loja — o design Kintsugi Fighter, em manga longa e manga curta, mostrado de frente e de costas com seu próprio painel de especificações. Antes ficavam mais abaixo, sob \"a ser anunciado\"; agora há arte e um trimestre para eles, então saíram daquela lista", ro: "Două rashguard-uri se alătură primei colecții și deschid acum magazinul — modelul Kintsugi Fighter, în mânecă lungă și mânecă scurtă, arătat față și spate, cu propriul panou de specificații. Stăteau mai jos, la „urmează să fie anunțat”; acum există grafică și un trimestru pentru ele, așa că au ieșit din acea listă" },
            { en: "The t-shirts in the shop are shown on a model instead of as flat drawings — all four designs, in all three colourways, front and back. Still a mockup rather than a photograph of a shirt that exists, so the wording has not changed: nothing is for sale, and the first run is still expected in the first quarter of 2027", fr: "Les t-shirts de la boutique sont désormais présentés portés plutôt qu'en dessins à plat — les quatre designs, dans les trois coloris, de face et de dos. Il s'agit toujours d'une simulation et non de la photo d'un t-shirt existant : la formulation reste donc inchangée — rien n'est en vente, et la première série est toujours attendue au premier trimestre 2027", ja: "ショップのTシャツを、平面イラストではなく着用状態で掲載しました。4つのデザインすべてを、3色それぞれ、前面と背面で確認できます。実在するTシャツの写真ではなくモックアップである点は変わらないため、記載も変えていません。販売はしておらず、初回生産は2027年第1四半期を予定しています", pt: "As camisetas da loja agora aparecem vestidas em vez de desenhos planos — os quatro designs, nas três cores, de frente e de costas. Continua sendo uma simulação e não a foto de uma camiseta que existe, então o texto não mudou: nada está à venda, e a primeira tiragem continua prevista para o primeiro trimestre de 2027", ro: "Tricourile din magazin sunt acum arătate purtate, nu ca desene plate — toate cele patru modele, în toate cele trei culori, față și spate. Rămâne o simulare, nu fotografia unui tricou care există, așa că formularea nu s-a schimbat: nimic nu este de vânzare, iar prima serie este în continuare așteptată în primul trimestru din 2027" },
            { en: "Nothing has changed about what the site claims: still no product, no shop and no account, and the first t-shirt run is still expected in the first quarter of 2027", fr: "Rien ne change quant à ce que le site affirme : toujours aucun produit, aucune boutique et aucun compte, et le premier tirage de t-shirts est toujours attendu au premier trimestre 2027", ja: "サイトが述べている内容に変更はありません。製品も、ショップも、アカウントも依然としてなく、Tシャツの初回生産は2027年第1四半期を予定しています", pt: "Nada mudou quanto ao que o site afirma: continua sem produto, sem loja e sem conta, e a primeira tiragem de camisetas continua prevista para o primeiro trimestre de 2027", ro: "Nu s-a schimbat nimic din ce afirmă site-ul: în continuare fără produs, fără magazin și fără cont, iar prima serie de tricouri este în continuare așteptată în primul trimestru din 2027" },
    ],
  },
  {
    date: "2026-08-16",
    title: { en: "Clearer exercise diagrams, and the belt as a progress mark", fr: "Des schémas d'exercices plus clairs, et la ceinture comme repère de progression", ja: "より分かりやすい動作図と、進捗を示す帯", pt: "Diagramas de exercício mais claros e a faixa como marca de progresso", ro: "Diagrame de exerciții mai clare și centura ca semn de progres" },
    items: [
      { en: "Every exercise diagram has been redrawn: the figure now has a body rather than a wire outline, and the start position stays on screen behind the end position with an arrow showing the direction of travel", fr: "Tous les schémas d'exercices ont été redessinés : la silhouette a désormais un corps plutôt qu'un contour filaire, et la position de départ reste visible derrière la position finale, avec une flèche indiquant le sens du mouvement", ja: "動作図をすべて描き直しました。人物は線画ではなく身体を持つ形になり、開始姿勢が終了姿勢の背後に残り、動く方向を矢印で示します", pt: "Todos os diagramas de exercício foram redesenhados: a figura agora tem um corpo em vez de um contorno de arame, e a posição inicial permanece atrás da posição final, com uma seta indicando a direção do movimento", ro: "Toate diagramele de exerciții au fost redesenate: silueta are acum un corp, nu un contur filiform, iar poziția de start rămâne în spatele celei finale, cu o săgeată care arată direcția mișcării" },
      { en: "Exercises done on the floor are now drawn on a mat, with a contact shadow, so the figure stands on something", fr: "Les exercices au sol sont désormais dessinés sur un tapis, avec une ombre de contact, pour que la silhouette repose sur quelque chose", ja: "床で行う種目はマットの上に描かれ、接地部分に影が付きました。人物が何かの上に立っているように見えます", pt: "Os exercícios feitos no chão agora são desenhados sobre um tatame, com sombra de contato, para que a figura se apoie em algo", ro: "Exercițiile la sol sunt acum desenate pe o saltea, cu umbră de contact, ca silueta să stea pe ceva" },
      { en: "The level you pick in the programme builder is shown as a belt, and the technique map takes a stripe for each quarter you have drilled", fr: "Le niveau choisi dans le générateur de programme s'affiche sous forme de ceinture, et la carte des techniques gagne un degré par quart travaillé", ja: "プログラムビルダーで選んだレベルを帯で表示します。テクニックマップは、練習済みが4分の1進むごとに線が1本増えます", pt: "O nível escolhido no gerador de programa aparece como uma faixa, e o mapa de técnicas ganha um grau a cada quarto que você treinou", ro: "Nivelul ales în generatorul de program este arătat ca o centură, iar harta tehnicilor primește un grad pentru fiecare sfert exersat" },
      { en: "New textures across the site: a woven ground behind every page, and a cotton weave on the light sections", fr: "De nouvelles textures sur tout le site : un fond tissé derrière chaque page, et une trame de coton sur les sections claires", ja: "サイト全体に新しい質感を加えました。各ページの背景に織り目、明るいセクションには綿の織り地を敷いています", pt: "Novas texturas em todo o site: um fundo trançado atrás de cada página e uma trama de algodão nas seções claras", ro: "Texturi noi în tot site-ul: un fundal țesut în spatele fiecărei pagini și o tramă de bumbac pe secțiunile deschise" },
      { en: "The mission page has been rewritten around what the brand can state today, and the planned 1% donation has been removed from the site", fr: "La page Mission a été réécrite autour de ce que la marque peut affirmer aujourd'hui, et le don de 1% prévu a été retiré du site", ja: "「使命」のページを、現時点で確かに言えることを中心に書き直しました。予定していた1%の寄付についての記載はサイトから削除しました", pt: "A página da missão foi reescrita em torno do que a marca pode afirmar hoje, e a doação planejada de 1% foi removida do site", ro: "Pagina de misiune a fost rescrisă în jurul a ceea ce brandul poate afirma astăzi, iar donația planificată de 1% a fost eliminată din site" },
    ],
  },
  {
    date: "2026-08-12",
    title: { en: "A bigger map, and exercises that show you what to do", fr: "Une carte plus grande, et des exercices qui montrent quoi faire", ja: "より大きなマップと、動作を示すエクササイズ", pt: "Um mapa maior e exercícios que mostram o que fazer", ro: "O hartă mai mare și exerciții care îți arată ce ai de făcut" },
    items: [
      { en: "The technique map has grown from 34 techniques to 60 — spider and lasso guard, single leg X, deep half, the crucifix, D'Arce and anaconda chokes, kneebars, toe holds and more", fr: "La carte des techniques passe de 34 à 60 techniques — gardes spider et lasso, single leg X, demi-garde profonde, crucifix, étranglements D'Arce et anaconda, kneebars, toe holds et bien d'autres", ja: "テクニックマップを34から60の技術に拡張しました — スパイダーガード、ラッソーガード、シングルレッグX、ディープハーフ、クルシフィックス、ダースチョーク、アナコンダチョーク、ニーバー、トーホールドなど", pt: "O mapa de técnicas cresceu de 34 para 60 técnicas — guardas spider e lasso, single leg X, meia-guarda profunda, crucifixo, estrangulamentos D'Arce e anaconda, kneebars, toe holds e mais", ro: "Harta tehnicilor a crescut de la 34 la 60 de tehnici — gărzile spider și lasso, single leg X, half guard profund, crucifix, sufocările D'Arce și anaconda, kneebar, toe hold și altele" },
      { en: "Every exercise in the program builder now explains how to perform it, in all five languages", fr: "Chaque exercice du générateur de programme explique désormais comment l'exécuter, dans les cinq langues", ja: "プログラムビルダーのすべてのエクササイズに、5言語すべてで実施方法の解説を追加しました", pt: "Cada exercício do gerador de programa agora explica como executá-lo, nos cinco idiomas", ro: "Fiecare exercițiu din generatorul de program explică acum cum se execută, în toate cele cinci limbi" },
      { en: "Each one comes with a simple diagram of the movement, drawn rather than photographed so it reads the same in every language", fr: "Chacun est accompagné d'un schéma simple du mouvement, dessiné plutôt que photographié pour être lisible dans toutes les langues", ja: "各エクササイズには動作の簡単な図を添えています。写真ではなく図なので、どの言語でも同じように伝わります", pt: "Cada um vem com um diagrama simples do movimento, desenhado em vez de fotografado para ser igual em todos os idiomas", ro: "Fiecare vine cu o diagramă simplă a mișcării, desenată și nu fotografiată, ca să se citească la fel în orice limbă" },
      { en: "A set counter with a rest timer, so you can tick off each set as you go — it clears when you leave the page and nothing is saved", fr: "Un compteur de séries avec minuteur de repos, pour cocher chaque série au fur et à mesure — il s'efface en quittant la page et rien n'est enregistré", ja: "休憩タイマー付きのセットカウンターを追加しました。セットごとに記録できます。ページを離れると消去され、保存は行われません", pt: "Um contador de séries com temporizador de descanso, para marcar cada série conforme avança — ele é apagado ao sair da página e nada é salvo", ro: "Un contor de serii cu cronometru de pauză, ca să bifezi fiecare serie pe măsură ce o faci — se șterge când părăsești pagina și nimic nu este salvat" },
      { en: "The printed program now includes the instructions and diagrams instead of only the exercise names", fr: "Le programme imprimé inclut désormais les consignes et les schémas, et non plus seulement les noms des exercices", ja: "印刷版のプログラムに、種目名だけでなく解説と図も含まれるようになりました", pt: "O programa impresso agora inclui as instruções e os diagramas, não apenas os nomes dos exercícios", ro: "Programul tipărit include acum instrucțiunile și diagramele, nu doar denumirile exercițiilor" },
    ],
  },
  {
    date: "2026-08-01",
    title: { en: "The first t-shirts are on the site", fr: "Les premiers t-shirts sont en ligne", ja: "最初のTシャツを公開しました", pt: "As primeiras camisetas estão no site", ro: "Primele tricouri sunt pe site" },
    items: [
      { en: "Four t-shirt designs, shown front and back, in white, dark blue and jet black", fr: "Quatre designs de t-shirts, vus de face et de dos, en blanc, bleu foncé et noir intense", ja: "4つのTシャツデザインを、前面と背面の両方で、ホワイト・ダークブルー・ジェットブラックの3色で掲載", pt: "Quatro designs de camiseta, mostrados de frente e de costas, em branco, azul-escuro e preto", ro: "Patru modele de tricou, arătate față și spate, în alb, albastru închis și negru intens" },
      { en: "Pick a colour and the whole collection switches, or change one design on its own", fr: "Choisissez un coloris et toute la collection change, ou modifiez un seul design", ja: "色を選ぶとコレクション全体が切り替わります。デザインごとの個別変更も可能です", pt: "Escolha uma cor e toda a coleção muda, ou altere um design individualmente", ro: "Alege o culoare și toată colecția se schimbă, sau schimbă un singur model" },
      { en: "Fabric, price range and expected date stated plainly — the shirts are not for sale yet", fr: "Matière, fourchette de prix et date prévue indiquées clairement — les t-shirts ne sont pas encore en vente", ja: "素材・価格帯・発売予定時期を明記。Tシャツはまだ販売しておりません", pt: "Tecido, faixa de preço e data prevista informados claramente — as camisetas ainda não estão à venda", ro: "Material, interval de preț și dată estimată, spuse clar — tricourile nu sunt încă de vânzare" },
      { en: "The wider gear range moved below the shirts and is marked to be announced", fr: "Le reste de la gamme passe sous les t-shirts et est marqué « à annoncer »", ja: "その他のギアはTシャツの下に移動し、「近日発表」と表示されます", pt: "O restante da linha foi movido para baixo das camisetas e está marcado como a ser anunciado", ro: "Restul gamei a fost mutat sub tricouri și este marcat ca urmând să fie anunțat" },
    ],
  },
  {
    date: "2026-07-26",
    title: { en: "Rebuilt for phones, tablets and desktops", fr: "Reconstruit pour mobiles, tablettes et ordinateurs", ja: "スマートフォン・タブレット・PC向けに再構築", pt: "Reconstruído para celulares, tablets e desktops", ro: "Reconstruit pentru telefoane, tablete și desktop" },
    items: [
      { en: "Real addresses for every section, so Back and bookmarks work", fr: "Une adresse pour chaque section : le bouton Retour et les favoris fonctionnent", ja: "各セクションに固有のURLを付与。戻るボタンとブックマークが機能します", pt: "Endereços reais para cada seção, então Voltar e favoritos funcionam", ro: "Adrese reale pentru fiecare secțiune, deci Înapoi și favoritele funcționează" },
      { en: "Search across every technique and section (⌘K)", fr: "Recherche sur toutes les techniques et sections (⌘K)", ja: "全テクニック・セクションを横断検索（⌘K）", pt: "Busca em todas as técnicas e seções (⌘K)", ro: "Căutare în toate tehnicile și secțiunile (⌘K)" },
      { en: "The technique map now pans, zooms and finds routes between techniques", fr: "La carte se déplace, zoome et trouve des chemins entre techniques", ja: "テクニックマップの移動・拡大縮小と、技術間のルート検索に対応", pt: "O mapa agora move, amplia e encontra caminhos entre técnicas", ro: "Harta se deplasează, mărește și găsește trasee între tehnici" },
      { en: "Mark techniques as drilled and keep the count between visits", fr: "Marquez les techniques travaillées et conservez le compte entre visites", ja: "練習済みの技術を記録し、次回訪問時にも保持", pt: "Marque técnicas como treinadas e mantenha a contagem entre visitas", ro: "Marchează tehnicile exersate și păstrează progresul între vizite" },
    ],
  },
];

export default function WhatsNew({ lang }) {
  return (
    <div>
      <div className="page-header">
        <div className="eyebrow eyebrow--accent">{t(T.whatsNew.pageTag, lang)}</div>
        <h1 className="page-title">{t(T.whatsNew.pageTitle, lang)}</h1>
      </div>

      {RELEASES.map((r) => (
        <article className="card" key={r.date} style={{ maxWidth: "48rem", marginBottom: "0.875rem" }}>
          <p className="eyebrow" style={{ marginBottom: "0.5rem" }}>
            {new Intl.DateTimeFormat(lang === "pt" ? "pt-BR" : lang, { dateStyle: "long" }).format(new Date(r.date))}
          </p>
          <h2 className="concept__title" style={{ fontSize: "1.0625rem" }}>{t(r.title, lang)}</h2>
          <ul className="sc-list" style={{ marginTop: "0.75rem" }}>
            {r.items.map((item, i) => (
              <li key={i}>
                <span className="dot" aria-hidden="true" />
                {t(item, lang)}
              </li>
            ))}
          </ul>
        </article>
      ))}
    </div>
  );
}
