// ─── i18n.js — UI translations for SubmitologY ───────────────────────────────
// Languages: en (English), fr (French), ja (Japanese), pt (Brazilian Portuguese), ro (Romanian)
//
// Note: technique names and descriptions live in data/techmap.js and are
// English-only for now. Everything translated here is UI chrome.

import { UI } from "./i18n-additions";

export const LANGUAGES = [
  { code: "en", short: "EN", label: "English",   htmlLang: "en" },
  { code: "fr", short: "FR", label: "Français",  htmlLang: "fr" },
  { code: "ja", short: "JA", label: "日本語",     htmlLang: "ja" },
  { code: "pt", short: "PT", label: "Português", htmlLang: "pt-BR" },
  { code: "ro", short: "RO", label: "Română",    htmlLang: "ro" },
];

export const T = {

  // ── SITE-WIDE MISSION BANNER ────────────────────────────────────────────
  banner: {
    text: { en: "SubmitologY treats Brazilian Jiu-Jitsu as a mental health practice, not only a sport", fr: "SubmitologY considère le Jiu-Jitsu Brésilien comme une pratique de santé mentale, pas seulement comme un sport", ja: "SubmitologYはブラジリアン柔術を、単なるスポーツではなくメンタルヘルスの実践として捉えています", pt: "A SubmitologY trata o Brazilian Jiu-Jitsu como uma prática de saúde mental, não apenas um esporte", ro: "SubmitologY tratează Jiu-Jitsu Brazilian ca pe o practică de sănătate mintală, nu doar ca pe un sport" },
    cta:  { en: "Learn more →", fr: "En savoir plus →", ja: "詳しく見る →", pt: "Saiba mais →", ro: "Află mai multe →" },
  },

  // ── OVERVIEW ─────────────────────────────────────────────────────────────
  overview: {
    tag:         { en: "BJJ Apparel · Community · Mental Health Mission", fr: "Vêtements BJJ · Communauté · Mission Santé Mentale", ja: "BJJアパレル・コミュニティ・メンタルヘルスミッション", pt: "Vestuário BJJ · Comunidade · Missão de Saúde Mental", ro: "Îmbrăcăminte BJJ · Comunitate · Misiune Sănătate Mintală" },
    titleLine1:  { en: "The Study of Submission",  fr: "L'Étude de la Soumission",  ja: "サブミッションの探求",   pt: "O Estudo da Submissão",   ro: "Studiul Submisiei" },
    titleLine2:  { en: "The Science of Resilience", fr: "La Science de la Résilience", ja: "レジリエンスの科学",     pt: "A Ciência da Resiliência", ro: "Știința Rezilienței" },
    heroBody:    { en: "Sixty techniques mapped as a graph you can walk. Six concepts that explain why the graph is shaped that way. A brand in the making … stay tuned.", fr: "Soixante techniques cartographiées en un graphe que vous pouvez parcourir. Six concepts qui expliquent pourquoi le graphe a cette forme. Une marque en devenir … restez à l'écoute.", ja: "60の技術を、たどって歩けるグラフとして地図化。そのグラフがなぜその形をしているのかを説明する6つの概念。誕生に向けて準備中のブランドです … 続報をお待ちください。", pt: "Sessenta técnicas mapeadas como um grafo que você pode percorrer. Seis conceitos que explicam por que o grafo tem essa forma. Uma marca em construção … fique ligado.", ro: "Șaizeci de tehnici cartografiate ca un graf pe care îl poți parcurge. Șase concepte care explică de ce graful are această formă. Un brand în devenire … rămâi aproape." },
    // The line on the crest itself (frame 01, behind this exact section) —
    // added to i18n so it exists as real, translated site copy and not only
    // as pixels in a photograph. Sits as a gold kicker between the title and
    // the body line; see revamp-proposal-atos-direction.md and
    // photographic-revamp-implemented.md for why this was deferred, and the
    // 2026-09-10 marketing-plan note for why it can't stay deferred.
    heroKicker:  { en: "Kintsugi for the mind", fr: "Kintsugi pour l'esprit", ja: "心の金継ぎ", pt: "Kintsugi para a mente", ro: "Kintsugi pentru minte" },
    // Trial-phase banner under the hero CTAs. Says samples exist and are being
    // tested — and, in the same sentence, that nothing is on sale.
    trialTag:    { en: "Trial phase", fr: "Phase d'essai", ja: "試用フェーズ", pt: "Fase de testes", ro: "Fază de testare" },
    trialBody:   { en: "The first samples of our apparel — the Kintsugi Fighter rashguards — are now in their trial phase: worn and tested on the mats before anything goes on sale.", fr: "Les premiers échantillons de nos vêtements — les rashguards Kintsugi Fighter — sont en phase d'essai : portés et testés sur le tatami avant toute mise en vente.", ja: "アパレルの最初のサンプル、Kintsugi Fighterラッシュガードが試用フェーズに入りました。販売に先立ち、マットの上で実際に着用・テストしています。", pt: "As primeiras amostras das nossas peças — os rashguards Kintsugi Fighter — estão em fase de testes: vestidas e testadas no tatame antes de qualquer venda.", ro: "Primele mostre din colecția noastră — rashguard-urile Kintsugi Fighter — sunt în faza de testare: purtate și testate pe saltea înainte de a fi puse în vânzare." },
    body1:       { en: "SubmitologY is a Singapore-based Brazilian Jiu-Jitsu (BJJ) apparel and merchandise brand for the mid-range quality segment across Singapore and Southeast Asia. Every collection is built on a distinctive social mission: using BJJ as a vehicle for mental health awareness, recovery, and community resilience.", fr: "SubmitologY est une marque de vêtements et de produits dérivés de Jiu-Jitsu Brésilien (BJJ) basée à Singapour, pour le segment de qualité moyenne-supérieure à Singapour et en Asie du Sud-Est. Chaque collection repose sur une mission sociale distinctive : utiliser le BJJ comme vecteur de sensibilisation à la santé mentale, de rétablissement et de résilience communautaire.", ja: "SubmitologYはシンガポールを拠点とするブラジリアン柔術（BJJ）アパレル・グッズブランドで、シンガポールおよび東南アジア全域のミッドレンジ品質層向けです。すべてのコレクションは独自の社会的使命に基づいています：BJJをメンタルヘルスの啓発、回復、そしてコミュニティのレジリエンスを促進する手段として活用することです。", pt: "SubmitologY é uma marca de vestuário e produtos de Brazilian Jiu-Jitsu (BJJ) sediada em Singapura, para o segmento de qualidade intermediária em Singapura e no Sudeste Asiático. Cada coleção é construída sobre uma missão social distinta: usar o BJJ como veículo para a conscientização sobre saúde mental, recuperação e resiliência comunitária.", ro: "SubmitologY este un brand de îmbrăcăminte și produse pentru Jiu-Jitsu Brazilian (BJJ), cu sediul în Singapore, pentru segmentul de calitate medie din Singapore și Asia de Sud-Est. Fiecare colecție este construită pe o misiune socială distinctă: folosirea BJJ ca vehicul pentru conștientizarea sănătății mintale, recuperare și reziliență comunitară." },
    body2:       { en: "The name SubmitologY — \"the study of submission\" — carries a deliberate double meaning: the technical art of the submission in grappling, and the psychological act of submitting to one's struggles in order to grow through them. This dual identity forms the intellectual and emotional core of the brand.", fr: "Le nom SubmitologY — « l'étude de la soumission » — porte une double signification délibérée : l'art technique de la soumission en grappling, et l'acte psychologique de se soumettre à ses luttes afin d'en grandir. Cette double identité forme le cœur intellectuel et émotionnel de la marque.", ja: "SubmitologYという名前 —「サブミッションの探求」— には意図的な二重の意味が込められています：組技における技術的なサブミッション（極め技）の芸術と、困難を乗り越えて成長するために自らの苦闘に向き合い服従するという心理的な行為です。この二重のアイデンティティが、ブランドの知的・感情的な核を形成しています。", pt: "O nome SubmitologY — \"o estudo da submissão\" — carrega um duplo significado deliberado: a arte técnica da finalização (submissão) no grappling, e o ato psicológico de se submeter às próprias lutas para crescer através delas. Essa identidade dupla forma o núcleo intelectual e emocional da marca.", ro: "Numele SubmitologY — „studiul submisiei” — poartă un dublu sens deliberat: arta tehnică a submisiei în grappling și actul psihologic de a te supune propriilor lupte pentru a crește prin ele. Această identitate dublă formează nucleul intelectual și emoțional al brandului." },
    logoCaption: { en: "Our logo represents our core belief and mission, through the symbolism of kintsugi — the art of \"golden repair\" — applied to the mind and body.", fr: "Notre logo représente notre conviction fondamentale et notre mission, à travers le symbolisme du kintsugi — l'art de la « réparation dorée » — appliqué à l'esprit et au corps.", ja: "私たちのロゴは、「金継ぎ」— 金による修復の技法 — を心と身体に応用した象徴を通じて、私たちの核となる信念と使命を表しています。", pt: "Nosso logotipo representa nossa crença e missão fundamentais, através do simbolismo do kintsugi — a arte do \"reparo dourado\" — aplicado à mente e ao corpo.", ro: "Logo-ul nostru reprezintă convingerea și misiunea noastră fundamentală, prin simbolismul kintsugi — arta „reparației aurii” — aplicată minții și corpului." },
    statTechniques: { en: "techniques mapped", fr: "techniques cartographiées", ja: "の技術を地図化", pt: "técnicas mapeadas", ro: "tehnici cartografiate" },
    statPrograms:   { en: "S&C programs", fr: "programmes de préparation", ja: "のS&Cプログラム", pt: "programas de preparação", ro: "programe de pregătire" },
    statLanguages:  { en: "languages", fr: "langues", ja: "言語", pt: "idiomas", ro: "limbi" },
    statExercises:  { en: "exercises illustrated", fr: "exercices illustrés", ja: "の種目を図解", pt: "exercícios ilustrados", ro: "exerciții ilustrate" },
    taxEyebrow:     { en: "The technique map", fr: "La carte des techniques", ja: "テクニックマップ", pt: "O mapa de técnicas", ro: "Harta tehnicilor" },
    taxTitle:       { en: "Three kinds of thing, and every route between them.", fr: "Trois types d'éléments, et tous les chemins qui les relient.", ja: "3つの種類と、その間のあらゆる経路。", pt: "Três tipos de coisa, e todos os caminhos entre elas.", ro: "Trei tipuri de lucruri și toate rutele dintre ele." },
    taxCount:       { en: "mapped", fr: "cartographiées", ja: "件", pt: "mapeadas", ro: "cartografiate" },
    exploreCta:  { en: "Explore Techniques →", fr: "Explorer les Techniques →", ja: "技術を探索する →", pt: "Explorar Técnicas →", ro: "Explorează Tehnicile →" },
    merchCta:    { en: "Shop the Gear →",      fr: "Voir la Boutique →",        ja: "グッズを見る →",   pt: "Ver a Loja →",        ro: "Vezi Produsele →" },
    mapTag:      { en: "Interactive !",  fr: "Interactif !",   ja: "インタラクティブ！", pt: "Interativo !",  ro: "Interactiv !" },
    mapTitle:    { en: "Explore the Technique Map",  fr: "Explorez la Carte des Techniques", ja: "テクニックマップを見る", pt: "Explore o Mapa de Técnicas", ro: "Explorează Harta Tehnicilor" },
    mapBody:     { en: "See how positions, transitions and submissions actually connect to one another — click through the map instead of scrolling a list.", fr: "Découvrez comment les positions, transitions et soumissions se connectent réellement entre elles — naviguez dans la carte plutôt que dans une liste.", ja: "ポジション、トランジション、サブミッションが実際にどのように繋がっているかを見ることができます — リストをスクロールする代わりにマップをクリックして探索しましょう。", pt: "Veja como posições, transições e finalizações realmente se conectam entre si — navegue pelo mapa em vez de rolar uma lista.", ro: "Vezi cum se conectează cu adevărat pozițiile, tranzițiile și submisiile — navighează pe hartă în loc să derulezi o listă." },
    mapCta:      { en: "Open the Map →", fr: "Ouvrir la Carte →", ja: "マップを開く →", pt: "Abrir o Mapa →", ro: "Deschide Harta →" },
  },

  // ── CONCEPTS ─────────────────────────────────────────────────────────────
  concepts: {
    pageTitle:    { en: "Basic Concepts",  fr: "Concepts de base", ja: "基本概念",       pt: "Conceitos Básicos", ro: "Concepte de bază" },
    pageSubtitle: { en: "The mental models every BJJ practitioner should internalise from day one.", fr: "Les modèles mentaux que chaque pratiquant de BJJ devrait intérioriser dès le premier jour.", ja: "すべてのBJJ練習者が初日から内面化すべきメンタルモデル。", pt: "Os modelos mentais que todo praticante de BJJ deve internalizar desde o primeiro dia.", ro: "Modelele mentale pe care fiecare practicant de BJJ ar trebui să le internalizeze din prima zi." },
  },

  // ── CONCEPTS CONTENT ─────────────────────────────────────────────────────
  conceptItems: [
    {
      icon: "⚖️",
      title: { en: "Positional Hierarchy", fr: "Hiérarchie positionnelle", ja: "ポジション階層", pt: "Hierarquia Posicional", ro: "Ierarhia pozițională" },
      body:  { en: "BJJ ranks positions by dominance: back control → mount → knee-on-belly → side control → guard. The higher on the ladder, the more control and submission options you have.", fr: "Le BJJ classe les positions par dominance : contrôle du dos → montée → genou sur le ventre → contrôle latéral → garde. Plus on monte, plus on a de contrôle et d'options de soumission.", ja: "BJJは支配度でポジションを順位付けします：バックコントロール→マウント→ニーオンベリー→サイドコントロール→ガード。上位ほどコントロールとサブミッションの選択肢が多くなります。", pt: "O BJJ classifica as posições por dominância: controle das costas → montada → joelho na barriga → controle lateral → guarda. Quanto mais alto na hierarquia, mais controle e opções de finalização você tem.", ro: "BJJ clasifică pozițiile după dominanță: controlul spatelui → montare → genunchi pe burtă → control lateral → gardă. Cu cât ești mai sus, cu atât ai mai mult control și mai multe opțiuni de submisie." },
    },
    {
      icon: "🔄",
      title: { en: "The Guard", fr: "La Garde", ja: "ガード", pt: "A Guarda", ro: "Garda" },
      body:  { en: "Unique to BJJ — fighting effectively from your back. The guard is not defensive; it is an attacking platform. Developing a strong guard changed martial arts forever.", fr: "Unique au BJJ — se battre efficacement sur le dos. La garde n'est pas défensive ; c'est une plateforme d'attaque. Développer une garde solide a changé les arts martiaux pour toujours.", ja: "BJJに固有の技術 — 仰向けから効果的に戦う。ガードは防御的ではなく攻撃的なプラットフォームです。強いガードの開発は武道を永遠に変えました。", pt: "Único no BJJ — lutar efetivamente de costas para o chão. A guarda não é defensiva; é uma plataforma de ataque. Desenvolver uma guarda forte mudou as artes marciais para sempre.", ro: "Unic în BJJ — luptând eficient de pe spate. Garda nu este defensivă; este o platformă de atac. Dezvoltarea unei gărzi puternice a schimbat artele marțiale pentru totdeauna." },
    },
    {
      icon: "🌊",
      title: { en: "Flowing & Chaining", fr: "Fluidité et enchaînements", ja: "フローとチェーン", pt: "Fluxo e Encadeamento", ro: "Fluiditate și înlănțuire" },
      body:  { en: "Techniques are rarely isolated. A failed armbar should flow into a triangle; a blocked triangle feeds an omoplata. Train combinations, not just individual moves.", fr: "Les techniques sont rarement isolées. Un armbar raté devrait se transformer en triangle ; un triangle bloqué alimente une omoplata. Entraînez des combinaisons, pas seulement des mouvements individuels.", ja: "技術は孤立していることはほとんどありません。失敗したアームバーはトライアングルに流れ込むべきです。ブロックされたトライアングルはオモプラタにつながります。個々の動きだけでなく、コンビネーションを練習しましょう。", pt: "As técnicas raramente são isoladas. Um armbar falhado deve fluir para um triângulo; um triângulo bloqueado alimenta uma omoplata. Treine combinações, não apenas movimentos individuais.", ro: "Tehnicile sunt rar izolate. Un armbar eșuat ar trebui să curgă într-un triunghi; un triunghi blocat alimentează o omoplata. Antrenați combinații, nu doar mișcări individuale." },
    },
    {
      icon: "🎯",
      title: { en: "Base & Posture", fr: "Base et posture", ja: "ベースとポスチャー", pt: "Base e Postura", ro: "Bază și postură" },
      body:  { en: "Before attacking, establish base (hips low, weight distributed) and posture (spine neutral). Neglecting these fundamentals is the fastest way to get submitted.", fr: "Avant d'attaquer, établissez la base (hanches basses, poids réparti) et la posture (colonne vertébrale neutre). Négliger ces fondamentaux est le moyen le plus rapide d'être soumis.", ja: "攻撃する前に、ベース（腰を低く、体重を分散）とポスチャー（脊椎を中立）を確立します。これらの基本を怠ることは、サブミットされる最速の方法です。", pt: "Antes de atacar, estabeleça a base (quadris baixos, peso distribuído) e a postura (coluna neutra). Negligenciar esses fundamentos é a maneira mais rápida de ser finalizado.", ro: "Înainte de a ataca, stabiliți baza (șolduri joase, greutate distribuită) și postura (coloana neutră). Neglijarea acestor fundamente este cel mai rapid mod de a fi supus." },
    },
    {
      icon: "⏱️",
      title: { en: "Timing Over Force", fr: "Le timing plutôt que la force", ja: "力よりタイミング", pt: "Timing sobre Força", ro: "Timing înainte de forță" },
      body:  { en: "BJJ was designed so a smaller person can overcome a larger one. Timing, leverage, and technique consistently beat raw strength — especially over a long roll.", fr: "Le BJJ a été conçu pour qu'une personne plus petite puisse surmonter une plus grande. Le timing, l'effet de levier et la technique battent constamment la force brute — surtout sur un long assaut.", ja: "BJJは体の小さい人が大きな人を克服できるように設計されました。タイミング、レバレッジ、技術は一貫して生の力を打ち負かします — 特に長いロールでは。", pt: "O BJJ foi projetado para que uma pessoa menor possa superar uma maior. Timing, alavanca e técnica consistentemente superam a força bruta — especialmente em um rolar longo.", ro: "BJJ a fost conceput astfel încât o persoană mai mică să poată depăși una mai mare. Timing-ul, pârghia și tehnica înving în mod constant forța brută — mai ales într-un antrenament lung." },
    },
    {
      icon: "🦺",
      title: { en: "Tap Early, Tap Often", fr: "Tapoter tôt, tapoter souvent", ja: "早めにタップ、よくタップ", pt: "Toque cedo, toque com frequência", ro: "Tapează devreme, tapează des" },
      body:  { en: "Tapping is not failure — it's the mechanism that lets training continue safely. Pride in refusing to tap leads to injuries. The mats will always be there tomorrow.", fr: "Tapoter n'est pas un échec — c'est le mécanisme qui permet à l'entraînement de se poursuivre en toute sécurité. La fierté de refuser de tapoter entraîne des blessures. Les tatamis seront toujours là demain.", ja: "タップは失敗ではありません — 安全にトレーニングを続けるためのメカニズムです。タップを拒否することへの誇りはけがにつながります。マットは常に明日もそこにあります。", pt: "Tocar não é falha — é o mecanismo que permite que o treino continue com segurança. O orgulho em recusar tocar leva a lesões. Os tapetes sempre estarão lá amanhã.", ro: "Taparea nu este un eșec — este mecanismul care permite antrenamentul să continue în siguranță. Mândria de a refuza să tapezi duce la răni. Salteaua va fi întotdeauna acolo mâine." },
    },
  ],

  // ── DIFFICULTY NAMES ──────────────────────────────────────────────────────
  diffs: {
    All:          { en: "All",          fr: "Tous",          ja: "すべて",  pt: "Todos",       ro: "Toate"       },
    Beginner:     { en: "Beginner",     fr: "Débutant",      ja: "初心者",  pt: "Iniciante",   ro: "Începător"   },
    Intermediate: { en: "Intermediate", fr: "Intermédiaire", ja: "中級者",  pt: "Intermediário",ro: "Intermediar" },
    Advanced:     { en: "Advanced",     fr: "Avancé",        ja: "上級者",  pt: "Avançado",    ro: "Avansat"     },
  },

  // ── ABOUT PAGE ────────────────────────────────────────────────────────────
  about: {
    pageTitle:   { en: "About SubmitologY", fr: "À propos de SubmitologY", ja: "SubmitologYについて", pt: "Sobre o SubmitologY", ro: "Despre SubmitologY" },
    mission:     { en: "To build a BJJ brand that equips athletes on and off the mat — through quality gear, purposeful design, community sharing and a commitment to mental health advocacy.", fr: "Construire une marque de BJJ qui équipe les athlètes sur et en dehors du tatami — à travers un équipement de qualité, un design porteur de sens, le partage communautaire et un engagement envers la défense de la santé mentale.", ja: "マットの上でもマットの外でも、アスリートを支えるBJJブランドを築くこと — 高品質なギア、意義あるデザイン、コミュニティの共有、そしてメンタルヘルス支援への取り組みを通じて。", pt: "Construir uma marca de BJJ que equipa atletas dentro e fora do tatame — por meio de equipamentos de qualidade, design com propósito, compartilhamento comunitário e um compromisso com a defesa da saúde mental.", ro: "Să construim un brand BJJ care echipează sportivii pe și în afara saltelei — prin echipament de calitate, design cu scop, împărtășire comunitară și un angajament față de susținerea sănătății mintale." },
    body1:       { en: "SubmitologY is a structured BJJ knowledge base built to help practitioners of all levels explore positions, submissions and transitions, in an organised, visual way.", fr: "SubmitologY est une base de connaissances BJJ structurée pour aider les pratiquants de tous niveaux à explorer les positions, soumissions et transitions, de manière organisée et visuelle.", ja: "SubmitologYは、あらゆるレベルの練習者がポジション、サブミッション、トランジションを整理された視覚的な方法で探索できるように作られた構造化されたBJJナレッジベースです。", pt: "O SubmitologY é uma base de conhecimento de BJJ estruturada para ajudar praticantes de todos os níveis a explorar posições, finalizações e transições, de forma organizada e visual.", ro: "SubmitologY este o bază de cunoștințe BJJ structurată, concepută pentru a ajuta practicanții de toate nivelurile să exploreze pozițiile, submisiile și tranzițiile, într-un mod organizat și vizual." },
    body2:       { en: "Explore techniques in a unique way using our interactive BJJ map, guiding you through various inter-related techniques in an intuitive way.", fr: "Découvrez les techniques d'une manière unique grâce à notre carte BJJ interactive, qui vous guide à travers diverses techniques interconnectées de façon intuitive.", ja: "インタラクティブなBJJマップを使って、これまでにない方法でテクニックを探索できます。相互に関連するさまざまなテクニックを直感的にガイドします。", pt: "Explore as técnicas de uma forma única com nosso mapa interativo de BJJ, guiando você por diversas técnicas inter-relacionadas de forma intuitiva.", ro: "Explorează tehnicile într-un mod unic folosind harta noastră interactivă de BJJ, care te ghidează printr-o varietate de tehnici interconectate, într-un mod intuitiv." },
    catsTitle:   { en: "Categories Explained", fr: "Catégories expliquées", ja: "カテゴリーの説明", pt: "Categorias Explicadas", ro: "Categorii explicate" },
    typeDescs: {
      position:   { en: "Guards, dominant control.",           fr: "Gardes, contrôle dominant.",             ja: "ガード、支配的コントロール。",   pt: "Guardas, controle dominante.",        ro: "Gărzi, control dominant." },
      transition: { en: "Guard passes, sweeps, escapes.",      fr: "Passages de garde, renversements, échappées.", ja: "ガードパス、スイープ、エスケープ。", pt: "Passagens de guarda, raspagens, fugas.", ro: "Treceri de gardă, răsturnări, evadări." },
      submission: { en: "Chokes and strangles, joint locks.",  fr: "Étranglements, clés articulaires.",     ja: "絞め技、関節技。",             pt: "Estrangulamentos, chaves de articulação.", ro: "Sufocări, blocaje articulare." },
    },
    linksTitle:  { en: "More from SubmitologY", fr: "Plus de SubmitologY", ja: "SubmitologYのその他", pt: "Mais da SubmitologY", ro: "Mai multe de la SubmitologY" },
    linksBody:   { en: "SubmitologY is also an apparel brand in the making and a mental health advocate — the mission page sets out what that means, and where to find real support.", fr: "SubmitologY est aussi une marque de vêtements en devenir et un défenseur de la santé mentale — la page Mission explique ce que cela signifie, et où trouver un véritable soutien.", ja: "SubmitologYは準備中のアパレルブランドであり、メンタルヘルスの支援者でもあります — その意味と、実際に頼れる支援先については「使命」のページをご覧ください。", pt: "A SubmitologY também é uma marca de vestuário em construção e defensora da saúde mental — a página da missão explica o que isso significa e onde encontrar apoio real.", ro: "SubmitologY este, de asemenea, un brand de îmbrăcăminte în devenire și un susținător al sănătății mintale — pagina de misiune explică ce înseamnă asta și unde poți găsi sprijin real." },
    shopLink:    { en: "Shop the Gear →", fr: "Voir la Boutique →", ja: "グッズを見る →", pt: "Ver a Loja →", ro: "Vezi Produsele →" },
    missionLink: { en: "Our Mission →", fr: "Notre Mission →", ja: "私たちの使命 →", pt: "Nossa Missão →", ro: "Misiunea noastră →" },
    invitationTitle: { en: "The Invitation", fr: "L'Invitation", ja: "招待", pt: "O Convite", ro: "Invitația" },
    invitation:  { en: "We are not just building a gear brand. We are building a community that trains hard, talks openly, and submits to nothing except growth. Welcome to SubmitologY.", fr: "Nous ne construisons pas seulement une marque d'équipement. Nous construisons une communauté qui s'entraîne dur, qui parle ouvertement, et qui ne se soumet à rien d'autre qu'à la croissance. Bienvenue chez SubmitologY.", ja: "私たちは単なるギアブランドを作っているのではありません。ハードにトレーニングし、オープンに語り合い、成長以外の何ものにも屈しないコミュニティを築いています。SubmitologYへようこそ。", pt: "Não estamos apenas construindo uma marca de equipamentos. Estamos construindo uma comunidade que treina duro, fala abertamente e não se submete a nada além do crescimento. Bem-vindo à SubmitologY.", ro: "Nu construim doar un brand de echipamente. Construim o comunitate care se antrenează intens, vorbește deschis și nu se supune nimic altceva decât creșterii. Bine ai venit la SubmitologY." },
  },

  // ── MERCHANDISE / SHOP ────────────────────────────────────────────────────
  // The whole shop is the first drop now: rashguards, shorts, the gi, tees,
  // then the belt. Strings are grouped in that order so the copy reads
  // top-to-bottom in this file the same way it does on the page.
  merch: {
    pageTag:      { en: "First Drop · Q1 2027", fr: "Première Collection · T1 2027", ja: "ファーストドロップ · 2027年第1四半期", pt: "Primeira Coleção · T1 2027", ro: "Prima Colecție · T1 2027" },
    pageTitle:    { en: "The First Drop. Built for the Mat.", fr: "La Première Collection. Conçue pour le Tatami.", ja: "ファーストドロップ。マットのために。", pt: "A Primeira Coleção. Feita para o Tatame.", ro: "Prima Colecție. Construită pentru Saltea." },
    pageSubtitle: { en: "This is where SubmitologY steps beyond the study of submission and into what you wear while pursuing it.", fr: "C'est ici que SubmitologY va au-delà de l'étude de la soumission, pour devenir ce que l'on porte en la poursuivant.", ja: "SubmitologYが「サブミッションの探求」という原点を超え、それを追い求める者が身にまとうものへと踏み出す場所です。", pt: "É aqui que a SubmitologY vai além do estudo da submissão e se torna aquilo que se veste ao persegui-la.", ro: "Aici SubmitologY trece dincolo de studiul submisiei, devenind ceea ce porți în timp ce o urmărești." },
    pageIntroPhilosophy: { en: "The inaugural collection is built around the Kintsugi philosophy: strength shaped through pressure, resilience refined through repetition, and the marks left by the journey becoming part of the story.", fr: "La collection inaugurale est construite autour de la philosophie Kintsugi : une force façonnée par la pression, une résilience affinée par la répétition, et les marques laissées par le parcours qui deviennent partie intégrante de l'histoire.", ja: "この最初のコレクションは、金継ぎの哲学を軸に据えています。圧力によって鍛えられる強さ、反復によって磨かれるレジリエンス、そして歩んできた道のりが残す傷跡もまた物語の一部となること。", pt: "A coleção inaugural é construída em torno da filosofia Kintsugi: força moldada pela pressão, resiliência refinada pela repetição, e as marcas deixadas pela jornada que se tornam parte da história.", ro: "Colecția inaugurală este construită în jurul filosofiei Kintsugi: forța modelată de presiune, reziliența rafinată prin repetiție, iar urmele lăsate de drum devin parte din poveste." },
    pageIntroLineup: { en: "From the Kintsugi Fighter rashguards — available in long and short sleeve — to NoGi shorts designed for movement and performance, every piece is made with life on the mats in mind. The collection continues with the Kintsugi Gi, crafted in premium pearl weave and available in black, blue, pink and white, alongside a heavyweight 200GSM, 100% natural cotton t-shirt and tank top made for life beyond training.", fr: "Des rashguards Kintsugi Fighter — disponibles en manches longues et manches courtes — aux shorts NoGi pensés pour le mouvement et la performance, chaque pièce est conçue pour la vie sur le tatami. La collection se poursuit avec le Kintsugi Gi, façonné en pearl weave premium et décliné en noir, bleu, rose et blanc, aux côtés d'un t-shirt et d'un débardeur en coton épais 200 g/m², 100 % naturel, pensés pour la vie en dehors de l'entraînement.", ja: "長袖・半袖から選べるKintsugi Fighterラッシュガードから、動きとパフォーマンスのために設計されたNoGiショーツまで、すべてのピースはマットの上での日々を見据えて作られています。コレクションはさらに、プレミアムパールウィーブで仕立て、ブラック・ブルー・ピンク・ホワイトの4色を展開するKintsugi Giへと続き、トレーニングを超えた日常のための、厚手の200g/m²・100%天然コットンのTシャツとタンクトップも揃えています。", pt: "Dos rashguards Kintsugi Fighter — disponíveis em manga longa e manga curta — aos shorts NoGi projetados para movimento e desempenho, cada peça é feita pensando na vida sobre o tatame. A coleção continua com o Kintsugi Gi, confeccionado em pearl weave premium e disponível em preto, azul, rosa e branco, ao lado de uma camiseta e uma regata encorpadas em algodão 200 g/m², 100% natural, feitas para a vida além do treino.", ro: "De la rashguard-urile Kintsugi Fighter — disponibile cu mânecă lungă și scurtă — la pantalonii scurți NoGi gândiți pentru mișcare și performanță, fiecare piesă este făcută cu gândul la viața de pe saltea. Colecția continuă cu Kintsugi Gi, realizat din pearl weave premium și disponibil în negru, albastru, roz și alb, alături de un tricou și un maiou groase din bumbac 200 g/m², 100% natural, făcute pentru viața de dincolo de antrenament." },
    pageIntroBelt: { en: "Completing the first chapter: the Kintsugi Belt, available across all five adult ranks.", fr: "Pour compléter ce premier chapitre : la Ceinture Kintsugi, disponible dans les cinq grades adultes.", ja: "この最初の章を締めくくるのはKintsugi Belt。成人の5階級すべてに対応しています。", pt: "Completando este primeiro capítulo: a Faixa Kintsugi, disponível nas cinco faixas adultas.", ro: "Pentru a încheia acest prim capitol: Centura Kintsugi, disponibilă în toate cele cinci centuri pentru adulți." },
    pageIntroTagline: { en: "This isn't just merchandise. It's the first uniform of the SubmitologY philosophy.", fr: "Ce n'est pas simplement du merchandising. C'est le premier uniforme de la philosophie SubmitologY.", ja: "これは単なるグッズではありません。SubmitologYという哲学の、最初のユニフォームです。", pt: "Isto não é apenas produto de marca. É o primeiro uniforme da filosofia SubmitologY.", ro: "Nu este doar marfă promoțională. Este prima uniformă a filosofiei SubmitologY." },
    pageIntroDate: { en: "Coming in Q1 2027 — the Kintsugi Gi follows in Q2 2027.", fr: "Disponible au premier trimestre 2027 — le Kintsugi Gi suivra au deuxième trimestre 2027.", ja: "2027年第1四半期発売予定。Kintsugi Giは2027年第2四半期に続きます。", pt: "Chegando no primeiro trimestre de 2027 — o Kintsugi Gi chega no segundo trimestre de 2027.", ro: "Disponibil în primul trimestru din 2027 — Kintsugi Gi urmează în al doilea trimestru din 2027." },

    // ── T-shirt collection ──────────────────────────────────────────────
    colourLbl:    { en: "Colour", fr: "Couleur", ja: "カラー", pt: "Cor", ro: "Culoare" },
    colourAll:    { en: "Show the whole collection in this colour", fr: "Afficher toute la collection dans ce coloris", ja: "コレクション全体をこの色で表示", pt: "Ver toda a coleção nesta cor", ro: "Vezi toată colecția în această culoare" },
    colours: {
      white: { en: "White",     fr: "Blanc",         ja: "ホワイト",         pt: "Branco",      ro: "Alb" },
      navy:  { en: "Dark Blue", fr: "Bleu foncé",    ja: "ダークブルー",     pt: "Azul-escuro", ro: "Albastru închis" },
      black: { en: "Jet Black", fr: "Noir intense",  ja: "ジェットブラック", pt: "Preto",       ro: "Negru intens" },
    },
    frontBack:    { en: "Shown front and back.", fr: "Vue avant et arrière.", ja: "前面と背面。", pt: "Frente e costas.", ro: "Față și spate." },
    frontSideBack: { en: "Shown front, side and back.", fr: "Vue avant, profil et arrière.", ja: "前面・側面・背面。", pt: "Frente, lado e costas.", ro: "Față, profil și spate." },
    /* Section headings. The h1 now names two product families, so each grid
       needs its own h2 — previously the tee grid ran under the h1 alone,
       which was right when it was the only thing on the page. */
    teesSection:  { en: "T-Shirt & Tank Top", fr: "T-Shirt & Débardeur", ja: "Tシャツ＆タンクトップ", pt: "Camiseta e Regata", ro: "Tricou și Maiou" },
    rgSection:    { en: "Rashguards", fr: "Rashguards", ja: "ラッシュガード", pt: "Rashguards", ro: "Rashguard-uri" },
    rgSpecsTitle: { en: "The Rashguard", fr: "Le Rashguard", ja: "ラッシュガードについて", pt: "O Rashguard", ro: "Rashguard-ul" },
    rgFabricVal:  { en: "Quality material, 230 – 260 GSM", fr: "Matière de qualité, 230 – 260 g/m²", ja: "高品質素材 230〜260g/m²", pt: "Material de qualidade, 230 – 260 g/m²", ro: "Material de calitate, 230 – 260 g/m²" },
    buildLbl:     { en: "Construction", fr: "Fabrication", ja: "仕様", pt: "Construção", ro: "Construcție" },
    rgBuildVal:   { en: "Poly-spandex sublimation, flatlock stitch", fr: "Sublimation polyester-élasthanne, coutures flatlock", ja: "ポリエステル・スパンデックス昇華プリント、フラットロック縫製", pt: "Sublimação poliéster-elastano, costura flatlock", ro: "Sublimare poliester-elastan, cusătură flatlock" },
    rgPriceBoth:  { en: "60 – 80 SGD long · 55 – 75 SGD short", fr: "60 – 80 SGD manches longues · 55 – 75 SGD manches courtes", ja: "長袖 60〜80 SGD · 半袖 55〜75 SGD", pt: "60 – 80 SGD manga longa · 55 – 75 SGD manga curta", ro: "60 – 80 SGD mânecă lungă · 55 – 75 SGD mânecă scurtă" },
    cutLs:        { en: "Long sleeve", fr: "Manches longues", ja: "長袖", pt: "Manga longa", ro: "Mânecă lungă" },
    cutSs:        { en: "Short sleeve", fr: "Manches courtes", ja: "半袖", pt: "Manga curta", ro: "Mânecă scurtă" },
    // Sampling status for a single garment, not a date: says the physical
    // item exists and is being tried, and in the same breath that it still
    // can't be bought.
    rgSamplingNote: { en: "First items available for sampling (not for sale yet)", fr: "Premières pièces disponibles pour des essais (pas encore en vente)", ja: "最初のサンプルを試用中（まだ販売していません）", pt: "Primeiras peças disponíveis para teste (ainda não estão à venda)", ro: "Primele piese disponibile pentru testare (încă nu sunt de vânzare)" },
    // Size guides — the dialog a shop card's "Size guide" button opens
    // (components/SizeGuideDialog.jsx, numbers in data/sizes.js). These were
    // the long-sleeve rashguard's strings (prefixed rg) until 2026-10-05, when
    // the shorts, the t-shirt and the tank top got charts too.
    //
    // The "how" lines follow the maker's sheets. For the tops the sheet
    // describes A and B as measured on the body; the shorts' sheets describe
    // the waistline and the leg opening.
    sizeTitle:    { en: "Size chart", fr: "Tableau des tailles", ja: "サイズ表", pt: "Tabela de medidas", ro: "Tabel de mărimi" },
    sizeCol:      { en: "Size", fr: "Taille", ja: "サイズ", pt: "Tamanho", ro: "Mărime" },
    sizeLength:   { en: "A · Body length", fr: "A · Longueur du corps", ja: "A · 着丈", pt: "A · Comprimento do corpo", ro: "A · Lungimea corpului" },
    sizeChest:    { en: "B · ½ chest width", fr: "B · ½ largeur de poitrine", ja: "B · ½ 胸幅", pt: "B · ½ largura do peito", ro: "B · ½ lățime piept" },
    sizeNote:     { en: "All measurements are in centimetres and approximate — expect some variation from piece to piece, and consider your personal fit preference as well.", fr: "Toutes les mesures sont en centimètres et approximatives — de légères variations d'une pièce à l'autre sont possibles ; tenez aussi compte de la coupe que vous préférez.", ja: "寸法はすべてcm表記の目安で、個体差が多少あります。お好みのフィット感も考慮してお選びください。", pt: "Todas as medidas estão em centímetros e são aproximadas — pode haver pequenas variações de uma peça para outra; considere também o ajuste que você prefere.", ro: "Toate măsurătorile sunt în centimetri și sunt aproximative — pot exista mici variații de la o piesă la alta; ține cont și de cât de strâns preferi să stea." },
    sizeHowA:     { en: "A — Body length: measure from your shoulder down to your waist. Your waist sits about four fingers below your belly button.", fr: "A — Longueur du corps : mesurez de l'épaule jusqu'à la taille. La taille se situe environ quatre doigts sous le nombril.", ja: "A — 着丈：肩からウエストまでを測ります。ウエストの位置は、おへそから指4本分ほど下です。", pt: "A — Comprimento do corpo: meça do ombro até a cintura. A cintura fica cerca de quatro dedos abaixo do umbigo.", ro: "A — Lungimea corpului: măsoară de la umăr până la talie. Talia se află la aproximativ patru degete sub buric." },
    sizeHowB:     { en: "B — Chest width: measure around your chest, under the armpits and in line with the nipples, keeping the tape level all the way around.", fr: "B — Largeur de poitrine : mesurez le tour de poitrine, sous les aisselles et à hauteur des mamelons, en gardant le ruban bien horizontal sur tout le tour.", ja: "B — 胸幅：脇の下を通り、乳頭の高さで胸まわりを測ります。メジャーは一周とも水平に保ってください。", pt: "B — Largura do peito: meça em volta do peito, abaixo das axilas e na altura dos mamilos, mantendo a fita nivelada em toda a volta.", ro: "B — Lățimea pieptului: măsoară în jurul pieptului, sub axile și la nivelul mameloanelor, ținând centimetrul drept de jur împrejur." },
    sizeGuide:    { en: "Size guide", fr: "Guide des tailles", ja: "サイズガイド", pt: "Guia de medidas", ro: "Ghid de mărimi" },
    sizeWaist:    { en: "A · Waist", fr: "A · Tour de taille", ja: "A · ウエスト", pt: "A · Cintura", ro: "A · Talie" },
    sizeShortsLength: { en: "B · Length", fr: "B · Longueur", ja: "B · 丈", pt: "B · Comprimento", ro: "B · Lungime" },
    sizeHowWaist: { en: "A — Waist: measure around the natural waistline, just above the hips.", fr: "A — Tour de taille : mesurez autour de la taille naturelle, juste au-dessus des hanches.", ja: "A — ウエスト：腰骨のすぐ上、自然なウエストラインの周囲を測ります。", pt: "A — Cintura: meça em volta da cintura natural, logo acima dos quadris.", ro: "A — Talie: măsoară în jurul taliei naturale, chiar deasupra șoldurilor." },
    sizeHowShortsLength: { en: "B — Length: measure from the top of the waistband to the bottom of the leg opening.", fr: "B — Longueur : mesurez du haut de la ceinture jusqu'au bas de l'ouverture de jambe.", ja: "B — 丈：ウエストバンドの上端から裾の下端までを測ります。", pt: "B — Comprimento: meça do topo do cós até a barra da perna.", ro: "B — Lungime: măsoară de la marginea de sus a betelei până la tivul cracului." },
    sizeBothCuts: { en: "The long sleeve and the short sleeve share this chart.", fr: "Les manches longues et les manches courtes partagent ce tableau.", ja: "長袖・半袖共通のサイズ表です。", pt: "A manga longa e a manga curta usam a mesma tabela.", ro: "Mâneca lungă și mâneca scurtă folosesc același tabel." },
    // Tester feedback — the chrome around reviews. The quotes themselves live
    // in data/reviews.js and stay in the language the tester wrote them in.
    reviewsTitle:  { en: "From the Mat — Tester Feedback", fr: "Depuis le tatami — Retours des testeurs", ja: "マットから — テスターの声", pt: "Do Tatame — Opinião dos Testadores", ro: "De pe saltea — Părerile testerilor" },
    reviewsIntro:  { en: "The first samples are with people who train. What they tell us appears here in their own words — including what still needs work.", fr: "Les premiers échantillons sont portés par des pratiquants. Ce qu'ils nous disent apparaît ici, avec leurs propres mots — y compris ce qui reste à améliorer.", ja: "最初のサンプルは、実際にトレーニングをしている人たちが着用しています。寄せられた声は、改善すべき点も含めて、本人の言葉のままここに掲載します。", pt: "As primeiras amostras estão com quem treina. O que nos dizem aparece aqui com as próprias palavras — incluindo o que ainda precisa melhorar.", ro: "Primele mostre sunt purtate de oameni care se antrenează. Ce ne spun apare aici, cu propriile lor cuvinte — inclusiv ce mai trebuie îmbunătățit." },
    reviewsEmpty:  { en: "No feedback published yet — the trial has only just started.", fr: "Aucun retour publié pour l'instant — l'essai vient de commencer.", ja: "まだ掲載できる声はありません。試用は始まったばかりです。", pt: "Nenhuma opinião publicada ainda — o teste acabou de começar.", ro: "Nicio părere publicată încă — testarea abia a început." },
    reviewsGifted: { en: "Sample provided free of charge for testing", fr: "Échantillon fourni gratuitement pour les essais", ja: "試用のためサンプルを無償提供", pt: "Amostra fornecida gratuitamente para teste", ro: "Mostră oferită gratuit pentru testare" },

    // ── Shorts ───────────────────────────────────────────────────────────
    // Joined the first drop 2026-08-30 — see data/shorts.js. Two products,
    // one spec strip, same pattern the rashguard's two cuts already use for
    // a combined price line.
    shortsSection:    { en: "Shorts", fr: "Shorts", ja: "ショーツ", pt: "Shorts", ro: "Pantaloni Scurți" },
    shortsSpecsTitle: { en: "The Shorts", fr: "Le Short", ja: "ショーツについて", pt: "O Shorts", ro: "Pantalonii Scurți" },
    shortsFabricVal:  { en: "Stretch ripstop (shorts) · poly-spandex (compression)", fr: "Ripstop stretch (short) · poly-élasthanne (compression)", ja: "ストレッチリップストップ（ショーツ）・ポリエステル・スパンデックス（コンプレッション）", pt: "Ripstop com elastano (shorts) · poliéster-elastano (compressão)", ro: "Ripstop elastic (pantaloni) · poliester-elastan (compresie)" },
    shortsBuildVal:   { en: "Moisture-wicking, flatlock stitch, built for jiu-jitsu", fr: "Évacuation de l'humidité, coutures flatlock, conçu pour le jiu-jitsu", ja: "吸湿速乾、フラットロック縫製、柔術のために設計", pt: "Tecido que absorve umidade, costura flatlock, feito para o jiu-jitsu", ro: "Absoarbe umiditatea, cusătură flatlock, construit pentru jiu-jitsu" },
    shortsPriceBoth:  { en: "65 – 85 SGD shorts · 60 – 75 SGD compression", fr: "65 – 85 SGD short · 60 – 75 SGD compression", ja: "ショーツ 65〜85 SGD · コンプレッション 60〜75 SGD", pt: "65 – 85 SGD shorts · 60 – 75 SGD compressão", ro: "65 – 85 SGD pantaloni · 60 – 75 SGD compresie" },

    // ── Gi ───────────────────────────────────────────────────────────────
    // Joined the first drop 2026-08-30 — see data/gis.js. One design, four
    // colourways, all shown at once rather than behind a picker.
    giSection:    { en: "Gi", fr: "Kimono", ja: "柔術衣", pt: "Kimono", ro: "Kimono" },
    giSpecsTitle: { en: "The Gi", fr: "Le Kimono", ja: "柔術衣について", pt: "O Kimono", ro: "Kimono-ul" },
    giBlurb:      { en: "The back crest split by a gold kintsugi seam, matching patches on both sleeves, and 金継ぎ embroidered at the cuff and down the pant leg.", fr: "Le blason dans le dos traversé par une couture kintsugi dorée, les mêmes patchs sur les deux manches, et 金継ぎ brodé au poignet et le long de la jambe du pantalon.", ja: "背中のクレストを金色の金継ぎの継ぎ目が貫き、両袖には同じパッチを配置。袖口とパンツの裾には金継ぎの刺繍を入れています。", pt: "O brasão nas costas atravessado por uma emenda kintsugi dourada, os mesmos patches nas duas mangas, e 金継ぎ bordado no punho e ao longo da perna da calça.", ro: "Emblema de pe spate străbătută de o cusătură kintsugi aurie, aceleași embleme pe ambele mâneci, și 金継ぎ brodat la manșetă și de-a lungul crăcii pantalonului." },
    giColours: {
      black: { en: "Black", fr: "Noir",  ja: "ブラック", pt: "Preto", ro: "Negru" },
      blue:  { en: "Blue",  fr: "Bleu",  ja: "ブルー",   pt: "Azul",  ro: "Albastru" },
      pink:  { en: "Pink",  fr: "Rose",  ja: "ピンク",   pt: "Rosa",  ro: "Roz" },
      white: { en: "White", fr: "Blanc", ja: "ホワイト", pt: "Branco", ro: "Alb" },
    },
    giWomensCut:  { en: "Women's cut for comfort and performance.", fr: "Coupe femme, pensée pour le confort et la performance.", ja: "快適性とパフォーマンスを追求した女性用カット。", pt: "Corte feminino, pensado para conforto e desempenho.", ro: "Croială pentru femei, gândită pentru confort și performanță." },
    giFabricVal:  { en: "Premium pearl weave, 350 – 450 GSM jacket", fr: "Tissu pearl weave premium, veste 350 – 450 g/m²", ja: "プレミアムパールウィーブ、350〜450g/m²ジャケット", pt: "Pearl weave premium, japona 350 – 450 g/m²", ro: "Țesătură pearl weave premium, jachetă 350 – 450 g/m²" },
    giBuildVal:   { en: "Reinforced stitching, built for jiu-jitsu", fr: "Coutures renforcées, conçu pour le jiu-jitsu", ja: "補強縫製、柔術のために設計", pt: "Costuras reforçadas, feito para o jiu-jitsu", ro: "Cusături întărite, construit pentru jiu-jitsu" },
    giPrice:      { en: "160 – 220 SGD", fr: "160 – 220 SGD", ja: "160 – 220 SGD", pt: "160 – 220 SGD", ro: "160 – 220 SGD" },
    // The gi moved back a quarter on 2026-09-30, so it no longer shares the
    // drop-wide comingSoon/availVal strings — it carries its own pair. The
    // rest of the drop is still Q1 2027; don't fold these back into the
    // shared keys unless every garment moves together again.
    giComingSoon: { en: "Coming Q2 2027", fr: "Disponible T2 2027", ja: "2027年第2四半期発売", pt: "Chegando no T2 2027", ro: "Disponibil T2 2027" },
    giAvailVal:   { en: "Expected Q2 2027", fr: "Prévu T2 2027", ja: "2027年第2四半期予定", pt: "Previsto para o T2 2027", ro: "Estimat T2 2027" },

    specsTitle:   { en: "The T-Shirt & Tank Top", fr: "Le T-Shirt & le Débardeur", ja: "Tシャツ・タンクトップについて", pt: "A Camiseta e a Regata", ro: "Tricoul și Maioul" },
    fabricLbl:    { en: "Fabric", fr: "Matière", ja: "素材", pt: "Tecido", ro: "Material" },
    fabricVal:    { en: "Premium quality 200GSM cotton, 100% natural", fr: "Coton 200 g/m² de qualité premium, 100 % naturel", ja: "プレミアム品質 200g/m² コットン（100%天然）", pt: "Algodão 200 g/m² de qualidade premium, 100% natural", ro: "Bumbac de 200 g/m² de calitate premium, 100% natural" },
    rangeLbl:     { en: "Collection", fr: "Collection", ja: "コレクション", pt: "Coleção", ro: "Colecție" },
    rangeVal:     { en: "One design · two cuts · three colourways", fr: "Un design · deux coupes · trois coloris", ja: "1デザイン · 2タイプ · 3カラー", pt: "Um design · dois cortes · três cores", ro: "Un model · două croieli · trei culori" },
    teePrice:     { en: "30 – 50 SGD", fr: "30 – 50 SGD", ja: "30 – 50 SGD", pt: "30 – 50 SGD", ro: "30 – 50 SGD" },
    availLbl:     { en: "Availability", fr: "Disponibilité", ja: "発売時期", pt: "Disponibilidade", ro: "Disponibilitate" },
    availVal:     { en: "Expected Q1 2027", fr: "Prévu T1 2027", ja: "2027年第1四半期予定", pt: "Previsto para o T1 2027", ro: "Estimat T1 2027" },
    // ── Belt ─────────────────────────────────────────────────────────────
    // Joined the first drop 2026-08-30, alongside the shorts — see
    // data/belt.js. One product, one photograph, last of the apparel
    // sections on the page.
    beltSection:    { en: "Belts", fr: "Ceintures", ja: "帯", pt: "Faixas", ro: "Centuri" },
    beltSpecsTitle: { en: "The Belt", fr: "La Ceinture", ja: "帯について", pt: "A Faixa", ro: "Centura" },
    beltRanks:      { en: "White, blue, purple, brown and black.", fr: "Blanc, bleu, violet, marron et noir.", ja: "白・青・紫・茶・黒。", pt: "Branca, azul, roxa, marrom e preta.", ro: "Albă, albastră, mov, maro și neagră." },
    beltFabricVal:  { en: "Cotton weave, custom woven label", fr: "Tissage coton, étiquette tissée sur mesure", ja: "コットン織り、専用織りネーム", pt: "Trama de algodão, etiqueta tecida personalizada", ro: "Țesătură de bumbac, etichetă țesută personalizată" },
    beltBuildVal:   { en: "Bar-tacked stitching, all five adult ranks", fr: "Coutures renforcées, les cinq grades adultes", ja: "閂止め補強縫製、成人の5階級すべてに対応", pt: "Costura reforçada, todas as cinco faixas adultas", ro: "Cusături întărite, toate cele cinci centuri pentru adulți" },

    // ── Shared labels ───────────────────────────────────────────────────
    priceLbl:     { en: "Target Price",  fr: "Prix cible",        ja: "目標価格",        pt: "Preço-alvo",       ro: "Preț țintă"     },
    comingSoon:   { en: "Coming Q1 2027",fr: "Disponible T1 2027",ja: "2027年第1四半期発売", pt: "Chegando no T1 2027", ro: "Disponibil T1 2027" },
    pillarsTitle: { en: "Why SubmitologY Gear",  fr: "Pourquoi le matériel SubmitologY", ja: "SubmitologYギアの理由", pt: "Por que o Equipamento SubmitologY", ro: "De ce echipamentul SubmitologY" },
    pillars: [
      { title: { en: "Quality Without Compromise", fr: "Qualité sans compromis", ja: "妥協なき品質", pt: "Qualidade sem Compromisso", ro: "Calitate fără compromis" },
        body:  { en: "Natural fibres and honest construction, built to last through years of training.", fr: "Fibres naturelles et fabrication honnête, conçues pour durer des années d'entraînement.", ja: "天然素材と誠実な作り。何年ものトレーニングに耐える一枚です。", pt: "Fibras naturais e construção honesta, feitas para durar anos de treino.", ro: "Fibre naturale și o construcție onestă, făcute să reziste ani de antrenament." } },
      { title: { en: "Purpose-Driven Design", fr: "Design porteur de sens", ja: "目的を持ったデザイン", pt: "Design com Propósito", ro: "Design cu un scop" },
        body:  { en: "Every collection is tied to a mental health theme or story — not decoration for its own sake.", fr: "Chaque collection est liée à un thème ou une histoire de santé mentale — pas de la décoration gratuite.", ja: "すべてのコレクションはメンタルヘルスのテーマやストーリーと結びついています — 単なる装飾ではありません。", pt: "Cada coleção está ligada a um tema ou história de saúde mental — não é decoração pela decoração.", ro: "Fiecare colecție este legată de o temă sau o poveste despre sănătatea mintală — nu e decor gratuit." } },
      { title: { en: "Community Over Commerce", fr: "La communauté avant le commerce", ja: "商業よりコミュニティ", pt: "Comunidade Acima do Comércio", ro: "Comunitatea înaintea comerțului" },
        body:  { en: "The free tools come first — the technique map, the concepts and the programme builder are open to anyone, with no account and no charge.", fr: "Les outils gratuits d'abord — la carte des techniques, les concepts et le générateur de programme sont ouverts à tous, sans compte et sans frais.", ja: "無料のツールが先です — テクニックマップ、基本概念、プログラムビルダーは、アカウントも料金も不要で誰でも使えます。", pt: "As ferramentas gratuitas vêm primeiro — o mapa de técnicas, os conceitos e o gerador de programa são abertos a qualquer pessoa, sem conta e sem custo.", ro: "Instrumentele gratuite vin primele — harta tehnicilor, conceptele și generatorul de program sunt deschise oricui, fără cont și fără costuri." } },
      { title: { en: "Southeast Asian Roots", fr: "Racines d'Asie du Sud-Est", ja: "東南アジアのルーツ", pt: "Raízes do Sudeste Asiático", ro: "Rădăcini din Asia de Sud-Est" },
        body:  { en: "Built in Singapore, celebrating the growing regional BJJ scene.", fr: "Conçu à Singapour, célébrant la scène BJJ régionale en pleine croissance.", ja: "シンガポールで生まれ、成長する地域のBJJシーンを称えます。", pt: "Criado em Singapura, celebrando a crescente cena de BJJ regional.", ro: "Creat în Singapore, celebrând scena BJJ regională în creștere." } },
    ],
  },

  // ── MENTAL HEALTH PAGE ───────────────────────────────────────────────────
  mh: {
    pageTag:      { en: "Our Mission", fr: "Notre Mission", ja: "私たちの使命", pt: "Nossa Missão", ro: "Misiunea noastră" },
    pageTitle:    { en: "Mental Health on the Mats", fr: "La Santé Mentale sur le Tatami", ja: "マットの上のメンタルヘルス", pt: "Saúde Mental no Tatame", ro: "Sănătatea mintală pe saltea" },
    planNote:     { en: "SubmitologY has not yet launched. This site is live and free; everything below marked as planned is intended to begin in 2027, alongside the brand's launch.", fr: "SubmitologY n'a pas encore été lancée. Ce site est en ligne et gratuit ; tout ce qui est marqué comme prévu ci-dessous devrait commencer en 2027, en même temps que le lancement de la marque.", ja: "SubmitologYはまだ設立されていません。このサイトは公開中で、無料でご利用いただけます。以下で「予定」と記した取り組みは、ブランドのローンチと同時に2027年より開始する見込みです。", pt: "A SubmitologY ainda não foi lançada. Este site está no ar e é gratuito; tudo o que estiver marcado abaixo como planejado deve começar em 2027, junto com o lançamento da marca.", ro: "SubmitologY nu a fost încă lansată. Acest site este activ și gratuit; tot ce este marcat mai jos ca planificat urmează să înceapă în 2027, odată cu lansarea brandului." },
    lead:         { en: "The mental health benefits of Brazilian Jiu-Jitsu are well-documented and deeply felt within the community. Practitioners consistently report reductions in anxiety, depression, and PTSD symptoms. The mat is frequently described as \"the best therapy\" — a space where the mind is forced to be fully present, ego is checked, and resilience is built one roll at a time.", fr: "Les bienfaits du Jiu-Jitsu Brésilien sur la santé mentale sont bien documentés et profondément ressentis au sein de la communauté. Les pratiquants rapportent constamment une réduction de l'anxiété, de la dépression et des symptômes de stress post-traumatique. Le tatami est souvent décrit comme « la meilleure thérapie » — un espace où l'esprit est contraint d'être pleinement présent, où l'ego est mis de côté, et où la résilience se construit combat après combat.", ja: "ブラジリアン柔術がメンタルヘルスにもたらす効果は十分に文書化されており、コミュニティ内で深く実感されています。練習者は不安、うつ、PTSD症状の軽減を一貫して報告しています。マットはしばしば「最高のセラピー」と表現されます — 心が完全に「今」に集中させられ、エゴが抑えられ、レジリエンスが一つ一つのロールの中で築かれる場所です。", pt: "Os benefícios do Brazilian Jiu-Jitsu para a saúde mental são bem documentados e profundamente sentidos dentro da comunidade. Os praticantes relatam consistentemente reduções na ansiedade, depressão e sintomas de TEPT. O tatame é frequentemente descrito como \"a melhor terapia\" — um espaço onde a mente é forçada a estar totalmente presente, o ego é contido, e a resiliência é construída round a round.", ro: "Beneficiile Jiu-Jitsu Brazilian asupra sănătății mintale sunt bine documentate și resimțite profund în comunitate. Practicanții raportează constant reduceri ale anxietății, depresiei și simptomelor de stres post-traumatic. Salteaua este adesea descrisă drept „cea mai bună terapie” — un spațiu în care mintea este forțată să fie complet prezentă, ego-ul este ținut în frâu, iar reziliența se construiește rundă cu rundă." },
    lead2:        { en: "SubmitologY is building its brand identity around this truth, positioning BJJ not just as a sport, but as a mental health practice — one that deserves the same recognition as mindfulness, therapy, and exercise.", fr: "SubmitologY construit son identité de marque autour de cette vérité, positionnant le BJJ non seulement comme un sport, mais comme une pratique de santé mentale — méritant la même reconnaissance que la pleine conscience, la thérapie et l'exercice physique.", ja: "SubmitologYはこの真実を中心にブランドアイデンティティを構築しており、BJJを単なるスポーツとしてではなく、マインドフルネスやセラピー、運動と同様に認識されるべきメンタルヘルスの実践として位置づけています。", pt: "A SubmitologY está construindo sua identidade de marca em torno dessa verdade, posicionando o BJJ não apenas como um esporte, mas como uma prática de saúde mental — que merece o mesmo reconhecimento que mindfulness, terapia e exercício físico.", ro: "SubmitologY își construiește identitatea de brand în jurul acestui adevăr, poziționând BJJ nu doar ca sport, ci ca practică de sănătate mintală — care merită aceeași recunoaștere ca mindfulness-ul, terapia și exercițiul fizic." },
    stanceTitle:  { en: "Why It Matters", fr: "Pourquoi Cela Compte", ja: "なぜこれが大切なのか", pt: "Por Que Isso Importa", ro: "De Ce Contează" },
    stanceBody:   { en: "Whether at work or in our private lives, stress has become something almost no one escapes. World news, social issues, intergenerational tensions, the grip of social media, and many other factors are piling pressure on everyone's mind. It is therefore not surprising to see a growing number of mental health issues in our societies, no matter where we live. Most of us are not psychologists, but everyone can — and must — play a part in noticing, reaching out, and getting help when someone around us is struggling.", fr: "Que ce soit au travail ou dans la vie privée, le stress est devenu un facteur auquel presque personne n'échappe. L'actualité mondiale, les enjeux sociétaux, les tensions intergénérationnelles, l'emprise des réseaux sociaux, et bien d'autres facteurs accentuent la pression sur l'esprit de chacun. Il n'est donc pas étonnant de voir croître le nombre de problèmes de santé mentale dans nos sociétés, où que l'on vive. La plupart d'entre nous ne sont pas psychologues, mais chacun peut — et doit — jouer un rôle : remarquer, tendre la main, et aider quelqu'un à obtenir du soutien lorsqu'il traverse une période difficile.", ja: "職場であれ、プライベートであれ、ストレスから逃れられる人はほとんどいない時代になりました。世界情勢、社会問題、世代間の関係、ソーシャルメディアの影響など、数多くの要因が誰の心にも重くのしかかっています。そのため、私たちがどこに住んでいようと、社会の中でメンタルヘルスに関する問題が増えているのも不思議ではありません。私たちの多くは心理の専門家ではありませんが、誰もが、苦しんでいる人に気づき、手を差し伸べ、助けを得られるようサポートする役割を担うことができますし、担うべきです。", pt: "Seja no trabalho ou na vida pessoal, o estresse se tornou algo do qual quase ninguém consegue escapar. As notícias mundiais, as questões sociais, as tensões entre gerações, o domínio das redes sociais, entre muitos outros fatores, aumentam a pressão sobre a mente de todos. Por isso, não é surpreendente ver um número cada vez maior de questões relacionadas à saúde mental em nossas sociedades, não importa onde vivamos. A maioria de nós não é psicóloga, mas todos podem — e devem — desempenhar um papel: perceber, se aproximar e ajudar alguém a buscar apoio quando estiver sofrendo.", ro: "Fie la muncă, fie în viața privată, stresul a devenit ceva de care aproape nimeni nu mai poate scăpa. Știrile din lume, problemele sociale, tensiunile dintre generații, influența rețelelor sociale și mulți alți factori sporesc presiunea asupra minții fiecăruia dintre noi. Nu este așadar surprinzător să vedem un număr tot mai mare de probleme de sănătate mintală în societățile noastre, indiferent unde trăim. Cei mai mulți dintre noi nu suntem psihologi, dar oricine poate — și trebuie — să joace un rol: să observe, să întindă o mână de ajutor și să sprijine pe cineva aflat în suferință să primească ajutor." },
    stanceBody2:  { en: "My own experience with this was dramatic, and I still regret not having been able to help more at the time. Now it's too late. That is why we placed mental health at the heart of our mission. BJJ offers such a wonderful platform to socialize and connect, to learn to fail and start again, to see yourself grow in both mind and body in ways you never expected — connecting BJJ with mental health was a natural step. Break and repair. Kintsugi. Body and mind. This is what SubmitologY is all about.", fr: "Mon expérience personnelle avec ce sujet a été douloureuse, et je regrette encore de ne pas avoir pu aider davantage à l'époque. Aujourd'hui, il est trop tard. C'est pourquoi nous avons placé la santé mentale au cœur de notre mission. Le BJJ offre une formidable plateforme pour se socialiser et créer des liens, pour apprendre à échouer et à recommencer, pour se voir progresser à la fois dans son corps et dans son esprit, souvent d'une manière que l'on n'aurait jamais imaginée — relier le BJJ à la santé mentale s'est imposé naturellement. Se briser et se réparer. Kintsugi. Le corps et l'esprit. C'est là toute l'essence de SubmitologY.", ja: "私自身、この問題との関わりは痛切な経験でした。あの時、もっと力になれなかったことを、今でも悔やんでいます。もう取り返しはつきません。だからこそ、私たちはメンタルヘルスをミッションの中心に据えました。柔術は、人とつながり、失敗してもまた立ち上がることを学び、思いもしなかったような形で心と体が成長していく自分を見つめる、素晴らしい場を提供してくれます。柔術とメンタルヘルスを結びつけることは、私たちにとって自然な流れでした。壊れて、直す。金継ぎ。心と体。それが、SubmitologYのすべてです。", pt: "Minha própria experiência com esse tema foi dolorosa, e ainda hoje lamento não ter conseguido ajudar mais naquele momento. Agora já é tarde demais. É por isso que colocamos a saúde mental no centro da nossa missão. O BJJ oferece uma plataforma maravilhosa para socializar e se conectar, para aprender a falhar e recomeçar, para se ver crescer tanto na mente quanto no corpo, de formas que nunca imaginamos — conectar o BJJ à saúde mental foi um passo natural. Quebrar e reparar. Kintsugi. Corpo e mente. É disso que a SubmitologY trata.", ro: "Experiența mea personală cu acest subiect a fost dureroasă, și încă regret că nu am putut ajuta mai mult atunci. Acum e prea târziu. De aceea am pus sănătatea mintală în centrul misiunii noastre. BJJ oferă o platformă minunată pentru a socializa și a te conecta, pentru a învăța să eșuezi și să o iei de la capăt, pentru a te vedea crescând deopotrivă la nivel mental și fizic, în moduri pe care nici nu le-ai fi anticipat — conectarea BJJ cu sănătatea mintală a fost un pas firesc. A te sparge și a te repara. Kintsugi. Corp și minte. Aceasta este, în esență, SubmitologY." },
    pillarsTitle: { en: "What the Mission Looks Like", fr: "À quoi ressemble la mission", ja: "この使命が形になるとき", pt: "Como a Missão se Traduz na Prática", ro: "Cum arată misiunea în practică" },
    pillars: [
      { icon: "📖", title: { en: "Free by Design", fr: "Gratuit par choix", ja: "無料であることの設計", pt: "Gratuito por Escolha", ro: "Gratuit prin proiectare" },
        body: { en: "Live today: the technique map, the six concepts and the programme builder are free, in five languages, and need no account.", fr: "En ligne aujourd'hui : la carte des techniques, les six concepts et le générateur de programme sont gratuits, en cinq langues, et sans compte.", ja: "現在公開中：テクニックマップ、6つの基本概念、プログラムビルダーは無料。5言語対応で、アカウント登録も不要です。", pt: "No ar hoje: o mapa de técnicas, os seis conceitos e o gerador de programa são gratuitos, em cinco idiomas, e não exigem conta.", ro: "Activ astăzi: harta tehnicilor, cele șase concepte și generatorul de program sunt gratuite, în cinci limbi, și nu necesită cont." } },
      { icon: "🎙️", title: { en: "\"Tap Out to Talk\"", fr: "« Tap Out to Talk »", ja: "「Tap Out to Talk」", pt: "\"Tap Out to Talk\"", ro: "„Tap Out to Talk”" },
        body: { en: "Planned: a content series featuring BJJ practitioners sharing their mental health journeys.", fr: "Prévu : une série de contenus mettant en avant des pratiquants de BJJ qui partagent leur parcours en santé mentale.", ja: "予定：BJJ練習者がメンタルヘルスの経験を語るコンテンツシリーズ。", pt: "Planejado: uma série de conteúdos com praticantes de BJJ compartilhando suas jornadas de saúde mental.", ro: "Planificat: o serie de conținut în care practicanți de BJJ își împărtășesc parcursul legat de sănătatea mintală." } },
      { icon: "🤝", title: { en: "Academy Partnerships", fr: "Partenariats avec les académies", ja: "アカデミーパートナーシップ", pt: "Parcerias com Academias", ro: "Parteneriate cu academii" },
        body: { en: "Planned: working with academies that already run mental health initiatives, and sharing what they learn with the wider community.", fr: "Prévu : travailler avec les académies qui mènent déjà des initiatives de santé mentale, et partager leurs enseignements avec la communauté.", ja: "予定：すでにメンタルヘルスの取り組みを行っているアカデミーと協働し、その知見を広くコミュニティに共有します。", pt: "Planejado: trabalhar com academias que já realizam iniciativas de saúde mental e compartilhar o que aprendem com a comunidade.", ro: "Planificat: colaborarea cu academiile care derulează deja inițiative de sănătate mintală și împărtășirea celor învățate cu întreaga comunitate." } },
      { icon: "🥋", title: { en: "The Mental Health Roll", fr: "Le \"Mental Health Roll\"", ja: "メンタルヘルス・ロール", pt: "O \"Mental Health Roll\"", ro: "„Mental Health Roll”" },
        body: { en: "Planned: an annual open mat given over to mental health awareness — every belt, every academy, one afternoon a year.", fr: "Prévu : un open mat annuel consacré à la sensibilisation à la santé mentale — toutes ceintures, toutes académies, un après-midi par an.", ja: "予定：メンタルヘルスの啓発に充てる年次オープンマット。すべての帯、すべてのアカデミーに開かれた、年に一度の午後です。", pt: "Planejado: um tatame aberto anual dedicado à conscientização sobre saúde mental — todas as faixas, todas as academias, uma tarde por ano.", ro: "Planificat: un open mat anual dedicat conștientizării sănătății mintale — toate centurile, toate academiile, o după-amiază pe an." } },
    ],
    designTitle:  { en: "Design Language", fr: "Langage de design", ja: "デザイン言語", pt: "Linguagem de Design", ro: "Limbaj de design" },
    designBody:   { en: "Collections draw on visual themes from neuroscience and psychology — neural network and synaptic patterns, brain anatomy reimagined through the lens of BJJ, and clinical, academic typography that reinforces the \"study of\" concept. Dark, premium colourways with high-contrast accents — minimal, purposeful, never loud.", fr: "Les collections s'inspirent de thèmes visuels issus des neurosciences et de la psychologie — motifs de réseaux neuronaux et synaptiques, anatomie du cerveau réinterprétée à travers le prisme du BJJ, et typographie clinique et académique renforçant le concept d'« étude ». Des teintes sombres et haut de gamme avec des accents à fort contraste — minimalistes, réfléchies, jamais criardes.", ja: "コレクションは神経科学と心理学からの視覚的テーマを取り入れています — ニューラルネットワークやシナプスのパターン、BJJの視点から再解釈された脳解剖学、そして「探求」というコンセプトを強調する臨床的・学術的なタイポグラフィ。ダークで上質なカラーウェイに高コントラストのアクセント — ミニマルで意図的、決して派手ではありません。", pt: "As coleções se inspiram em temas visuais da neurociência e da psicologia — padrões de redes neurais e sinápticas, anatomia cerebral reimaginada pela lente do BJJ, e tipografia clínica e acadêmica que reforça o conceito de \"estudo\". Paletas escuras e premium com acentos de alto contraste — minimalistas, propositais, nunca exageradas.", ro: "Colecțiile se inspiră din teme vizuale din neuroștiințe și psihologie — modele de rețele neuronale și sinaptice, anatomie cerebrală reinterpretată prin prisma BJJ și tipografie clinică, academică, ce reîntărește conceptul de „studiu”. Culori închise, premium, cu accente de contrast ridicat — minimaliste, cu scop, niciodată stridente." },
    supportNote:  { en: "Remember to help if you see someone in need — you can reach out to various associations such as the Samaritans of Singapore (SOS) @ 1-767 · 24 hours.", fr: "N'oubliez pas d'aider si vous voyez quelqu'un en difficulté — vous pouvez contacter diverses associations telles que les Samaritans of Singapore (SOS) @ 1-767 · 24h/24.", ja: "困っている人を見かけたら、手を差し伸べることを忘れないでください。Samaritans of Singapore (SOS) をはじめ、さまざまな団体に連絡できます @ 1-767・24時間対応。", pt: "Lembre-se de ajudar se vir alguém precisando — você pode procurar diversas associações, como a Samaritans of Singapore (SOS) @ 1-767 · 24 horas.", ro: "Nu uita să ajuți dacă vezi pe cineva în nevoie — poți contacta diverse asociații, precum Samaritans of Singapore (SOS) @ 1-767 · non-stop." },
  },

  // ── STRENGTH & CONDITIONING ─────────────────────────────────────────────
  sc: {
    pageTag:      { en: "Program Builder", fr: "Générateur de Programme", ja: "プログラムビルダー", pt: "Gerador de Programa", ro: "Generator de Program" },
    pageTitle:    { en: "Strength & Conditioning", fr: "Force & Préparation Physique", ja: "筋力・コンディショニング", pt: "Força & Condicionamento", ro: "Forță & Pregătire Fizică" },
    pageSubtitle: { en: "A conditioning program built for the demands of BJJ — not a generic gym plan. Tell us your age range, fitness level and available equipment, and we'll build the specific session for you.", fr: "Un programme de préparation physique pensé pour les exigences du BJJ — pas un plan de salle générique. Indiquez votre tranche d'âge, votre niveau et votre équipement disponible, et nous construirons la séance qui vous correspond.", ja: "BJJの要求に特化したコンディショニングプログラムです — 一般的なジムプランではありません。年齢層、フィットネスレベル、使用可能な器具を選択すると、あなた専用のセッションを作成します。", pt: "Um programa de condicionamento feito para as exigências do BJJ — não um plano genérico de academia. Informe sua faixa etária, nível de condicionamento e equipamento disponível, e montaremos a sessão específica para você.", ro: "Un program de pregătire fizică construit pentru cerințele BJJ — nu un plan generic de sală. Spune-ne intervalul tău de vârstă, nivelul de fitness și echipamentul disponibil, iar noi vom construi sesiunea potrivită pentru tine." },
    ageLabel:     { en: "Age",     fr: "Âge",       ja: "年齢",     pt: "Idade",       ro: "Vârstă" },
    levelLabel:   { en: "Level",   fr: "Niveau",    ja: "レベル",   pt: "Nível",       ro: "Nivel" },
    typeLabel:    { en: "Equipment", fr: "Équipement", ja: "器具",   pt: "Equipamento", ro: "Echipament" },
    ageOptions: {
      "<20":  { en: "Under 20",   fr: "Moins de 20 ans", ja: "20歳未満",   pt: "Menos de 20", ro: "Sub 20 de ani" },
      "20-30":{ en: "20 – 30",    fr: "20 – 30 ans",     ja: "20〜30歳",   pt: "20 – 30",     ro: "20 – 30 de ani" },
      "30-40":{ en: "30 – 40",    fr: "30 – 40 ans",     ja: "30〜40歳",   pt: "30 – 40",     ro: "30 – 40 de ani" },
      "40-50":{ en: "40 – 50",    fr: "40 – 50 ans",     ja: "40〜50歳",   pt: "40 – 50",     ro: "40 – 50 de ani" },
      "50-60":{ en: "50 – 60",    fr: "50 – 60 ans",     ja: "50〜60歳",   pt: "50 – 60",     ro: "50 – 60 de ani" },
      ">60":  { en: "Over 60",    fr: "Plus de 60 ans",  ja: "60歳以上",   pt: "Mais de 60",  ro: "Peste 60 de ani" },
    },
    typeOptions: {
      Calisthenics: { en: "No Equipment",  fr: "Sans Équipement",  ja: "器具なし",       pt: "Sem Equipamento", ro: "Fără Echipament" },
      Equipment:    { en: "With Equipment", fr: "Avec Équipement", ja: "器具あり",       pt: "Com Equipamento", ro: "Cu Echipament" },
    },
    generateBtn:  { en: "Build My Program", fr: "Générer mon Programme", ja: "プログラムを作成", pt: "Gerar Meu Programa", ro: "Generează Programul" },
    incomplete:   { en: "Select an age range, a fitness level, and an equipment option to generate your program.", fr: "Sélectionnez une tranche d'âge, un niveau et une option d'équipement pour générer votre programme.", ja: "年齢層、フィットネスレベル、器具オプションを選択してプログラムを作成してください。", pt: "Selecione uma faixa etária, um nível e uma opção de equipamento para gerar seu programa.", ro: "Selectează un interval de vârstă, un nivel și o opțiune de echipament pentru a genera programul." },
    resultTag:    { en: "Your Program", fr: "Votre Programme", ja: "あなたのプログラム", pt: "Seu Programa", ro: "Programul Tău" },
    editBtn:      { en: "← Change Inputs", fr: "← Modifier les critères", ja: "← 入力を変更", pt: "← Alterar Critérios", ro: "← Modifică Criteriile" },
    frequencyLbl: { en: "Suggested Frequency", fr: "Fréquence Suggérée", ja: "推奨頻度", pt: "Frequência Sugerida", ro: "Frecvență Sugerată" },
    perWeek:      { en: "sessions / week", fr: "séances / semaine", ja: "回／週", pt: "sessões / semana", ro: "sesiuni / săptămână" },
    warmupTitle:  { en: "Warm-Up", fr: "Échauffement", ja: "ウォームアップ", pt: "Aquecimento", ro: "Încălzire" },
    lowerTitle:   { en: "Lower Body", fr: "Bas du Corps", ja: "下半身", pt: "Membros Inferiores", ro: "Partea Inferioară" },
    upperPushTitle:{ en: "Upper Body — Push", fr: "Haut du Corps — Poussée", ja: "上半身（プッシュ）", pt: "Superior — Empurrar", ro: "Partea Superioară — Împins" },
    upperPullTitle:{ en: "Upper Body — Pull", fr: "Haut du Corps — Tirage", ja: "上半身（プル）", pt: "Superior — Puxar", ro: "Partea Superioară — Tras" },
    coreTitle:    { en: "Core", fr: "Gainage", ja: "体幹", pt: "Core", ro: "Trunchi" },
    conditioningTitle: { en: "Conditioning", fr: "Préparation Physique", ja: "コンディショニング", pt: "Condicionamento", ro: "Pregătire Fizică" },
    cooldownTitle:{ en: "Cooldown & Mobility", fr: "Retour au Calme & Mobilité", ja: "クールダウン・可動域", pt: "Volta à Calma & Mobilidade", ro: "Revenire & Mobilitate" },
    notesTitle:   { en: "Notes for Your Age Group", fr: "Remarques pour votre tranche d'âge", ja: "年齢層別の注意事項", pt: "Notas para sua Faixa Etária", ro: "Observații pentru grupa ta de vârstă" },
    disclaimer:   { en: "This is general fitness guidance, not medical advice. Stop any exercise that causes pain and consult a physician before starting a new training program, especially if you have an existing injury or health condition.", fr: "Ceci est une orientation générale, pas un avis médical. Arrêtez tout exercice provoquant une douleur et consultez un médecin avant de commencer un nouveau programme, surtout en cas de blessure ou de problème de santé existant.", ja: "これは一般的なフィットネス指針であり、医学的助言ではありません。痛みを伴う運動は中止し、新しいトレーニングプログラムを開始する前に、特に既往症や健康上の問題がある場合は医師にご相談ください。", pt: "Esta é uma orientação geral de condicionamento físico, não um conselho médico. Interrompa qualquer exercício que cause dor e consulte um médico antes de iniciar um novo programa, especialmente se tiver uma lesão ou condição de saúde existente.", ro: "Acesta este un ghid general de fitness, nu un sfat medical. Oprește orice exercițiu care provoacă durere și consultă un medic înainte de a începe un program nou, mai ales dacă ai o accidentare sau o afecțiune medicală existentă." },
    restLbl:      { en: "Rest", fr: "Repos", ja: "休憩", pt: "Descanso", ro: "Odihnă" },
    ageNotes: {
      "<20":  { en: "Prioritise movement quality and full range of motion over load — your body is still developing. Technique before intensity.", fr: "Privilégiez la qualité du mouvement et l'amplitude complète plutôt que la charge — votre corps est encore en développement. La technique avant l'intensité.", ja: "身体はまだ発達段階にあるため、負荷よりも動作の質と可動域を優先してください。強度よりも技術を重視しましょう。", pt: "Priorize a qualidade do movimento e a amplitude completa em vez da carga — seu corpo ainda está se desenvolvendo. Técnica antes da intensidade.", ro: "Acordă prioritate calității mișcării și amplitudinii complete în locul încărcăturii — corpul tău este încă în dezvoltare. Tehnica înaintea intensității." },
      "20-30":{ en: "This is typically peak physical capacity — a good window to push intensity and volume, provided recovery keeps pace with training.", fr: "C'est généralement le pic de capacité physique — une bonne fenêtre pour augmenter l'intensité et le volume, à condition que la récupération suive l'entraînement.", ja: "一般的に身体能力のピークにあたる時期です — 回復がトレーニングに見合っていれば、強度と量を高める良い機会です。", pt: "Esta é tipicamente a capacidade física máxima — uma boa janela para aumentar intensidade e volume, desde que a recuperação acompanhe o treino.", ro: "Aceasta este de obicei perioada de vârf a capacității fizice — o fereastră bună pentru a crește intensitatea și volumul, cu condiția ca recuperarea să țină pasul cu antrenamentul." },
      "30-40":{ en: "Consistency matters more than peak intensity now. Add a few extra minutes of mobility work before heavy training days.", fr: "La régularité compte désormais plus que l'intensité maximale. Ajoutez quelques minutes de mobilité supplémentaires avant les journées d'entraînement intense.", ja: "今の時期は最大強度よりも継続性が重要です。強度の高いトレーニング日の前には、数分間可動域トレーニングを追加しましょう。", pt: "Consistência importa mais que intensidade máxima agora. Adicione alguns minutos extras de mobilidade antes dos dias de treino intenso.", ro: "Consecvența contează acum mai mult decât intensitatea maximă. Adaugă câteva minute suplimentare de mobilitate înainte de zilele de antrenament intens." },
      "40-50":{ en: "Recovery matters more than it used to — prioritise sleep, don't skip warm-ups, and back off if joints feel irritated rather than just tired.", fr: "La récupération compte plus qu'avant — privilégiez le sommeil, ne sautez pas l'échauffement, et levez le pied si les articulations semblent irritées plutôt que simplement fatiguées.", ja: "以前よりも回復が重要になります — 睡眠を優先し、ウォームアップを省略せず、関節に単なる疲労以上の違和感がある場合は強度を落としましょう。", pt: "A recuperação importa mais do que antes — priorize o sono, não pule o aquecimento e reduza a intensidade se as articulações parecerem irritadas, não apenas cansadas.", ro: "Recuperarea contează acum mai mult decât înainte — acordă prioritate somnului, nu sări peste încălzire și redu intensitatea dacă articulațiile par iritate, nu doar obosite." },
      "50-60":{ en: "High-impact and explosive movements have been swapped for joint-friendly alternatives below. If you're new to structured exercise, check with a physician before starting.", fr: "Les mouvements à fort impact et explosifs ont été remplacés ci-dessous par des alternatives plus douces pour les articulations. Si vous débutez l'exercice structuré, consultez un médecin avant de commencer.", ja: "以下では、高衝撃・爆発的な動作を関節に優しい代替種目に置き換えています。構造化されたトレーニングが初めての場合は、開始前に医師にご相談ください。", pt: "Movimentos de alto impacto e explosivos foram substituídos abaixo por alternativas mais amigáveis às articulações. Se você é novo em exercícios estruturados, consulte um médico antes de começar.", ro: "Mișcările cu impact ridicat și explozive au fost înlocuite mai jos cu alternative prietenoase pentru articulații. Dacă ești nou în exercițiul structurat, consultă un medic înainte de a începe." },
      ">60":  { en: "This program is built around control, balance and joint health rather than load. Please consult a physician before beginning, especially if returning to training after a break.", fr: "Ce programme est construit autour du contrôle, de l'équilibre et de la santé articulaire plutôt que de la charge. Veuillez consulter un médecin avant de commencer, surtout en cas de reprise après une pause.", ja: "このプログラムは負荷よりもコントロール、バランス、関節の健康を中心に構成されています。特に休止期間後にトレーニングを再開する場合は、開始前に必ず医師にご相談ください。", pt: "Este programa é construído em torno de controle, equilíbrio e saúde articular, em vez de carga. Consulte um médico antes de começar, especialmente se estiver retomando o treino após uma pausa.", ro: "Acest program este construit în jurul controlului, echilibrului și sănătății articulațiilor, nu al încărcăturii. Te rugăm să consulți un medic înainte de a începe, mai ales dacă reiei antrenamentul după o pauză." },
    },
    ex: {
      armLegSwings:      { en: "Arm & leg swings",          fr: "Balancés bras & jambes",       ja: "腕・脚振り",              pt: "Balanços de braço e perna", ro: "Balansări brațe și picioare" },
      hipRotations:      { en: "Hip 90/90 rotations",        fr: "Rotations de hanche 90/90",    ja: "股関節90/90回旋",         pt: "Rotações de quadril 90/90", ro: "Rotații de șold 90/90" },
      neckShoulderRolls: { en: "Neck & shoulder rolls",      fr: "Rotations nuque & épaules",    ja: "首・肩回し",              pt: "Rotações de pescoço e ombro", ro: "Rotații gât și umeri" },
      bodyweightSquat:   { en: "Bodyweight squat",           fr: "Squat au poids du corps",      ja: "自重スクワット",          pt: "Agachamento livre",        ro: "Genuflexiune cu greutate proprie" },
      bulgarianSplitSquat:{ en: "Bulgarian split squat",     fr: "Fente bulgare",                ja: "ブルガリアンスクワット", pt: "Agachamento búlgaro",      ro: "Genuflexiune bulgărească" },
      broadJump:         { en: "Broad jump",                 fr: "Saut en longueur",             ja: "幅跳び",                  pt: "Salto em distância",       ro: "Săritură în lungime" },
      stepUp:            { en: "Step-up",                    fr: "Montée sur banc",              ja: "ステップアップ",          pt: "Subida no banco",          ro: "Urcare pe bancă" },
      wallSit:           { en: "Wall sit",                   fr: "Chaise contre le mur",         ja: "ウォールシット",          pt: "Cadeira na parede",        ro: "Scaun la perete" },
      gobletSquat:       { en: "Goblet squat",                fr: "Squat goblet",                 ja: "ゴブレットスクワット",   pt: "Agachamento goblet",       ro: "Genuflexiune goblet" },
      romanianDeadliftDB:{ en: "Dumbbell Romanian deadlift", fr: "Soulevé de terre roumain haltères", ja: "ダンベル・ルーマニアンデッドリフト", pt: "Levantamento terra romeno com halteres", ro: "Îndreptări românești cu gantere" },
      walkingLunge:      { en: "Walking lunge",               fr: "Fente marchée",                ja: "ウォーキングランジ",     pt: "Avanço caminhando",        ro: "Fandare în mers" },
      dbStepUp:          { en: "Dumbbell step-up",            fr: "Montée sur banc haltères",     ja: "ダンベル・ステップアップ", pt: "Subida no banco com halteres", ro: "Urcare pe bancă cu gantere" },
      pushUp:            { en: "Push-up",                     fr: "Pompe",                        ja: "腕立て伏せ",              pt: "Flexão de braço",          ro: "Flotare" },
      pikePushUp:        { en: "Pike push-up",                 fr: "Pompe piquée",                 ja: "パイクプッシュアップ",   pt: "Flexão pike",              ro: "Flotare pike" },
      benchDip:          { en: "Bench dip",                    fr: "Dips sur banc",                 ja: "ベンチディップス",       pt: "Mergulho no banco",        ro: "Flotări la bancă (triceps)" },
      dbBenchPress:      { en: "Dumbbell bench press",        fr: "Développé couché haltères",    ja: "ダンベルベンチプレス",   pt: "Supino com halteres",      ro: "Împins la piept cu gantere" },
      dbOverheadPress:   { en: "Dumbbell overhead press",     fr: "Développé militaire haltères", ja: "ダンベルショルダープレス", pt: "Desenvolvimento com halteres", ro: "Împins deasupra capului cu gantere" },
      tricepExtension:   { en: "Dumbbell tricep extension",   fr: "Extension triceps haltère",    ja: "ダンベル・トライセップエクステンション", pt: "Extensão de tríceps com halteres", ro: "Extensii triceps cu ganteră" },
      towelRow:          { en: "Doorway towel row",            fr: "Tirage serviette porte",        ja: "タオルドア・ロウ",       pt: "Remada com toalha na porta", ro: "Tracțiune cu prosop la ușă" },
      supermanHold:      { en: "Superman hold",                fr: "Gainage superman",              ja: "スーパーマンホールド",   pt: "Prancha superman",         ro: "Extensie superman" },
      invertedRowChair:  { en: "Table/sturdy-edge inverted row", fr: "Tirage inversé sous table",  ja: "テーブル・インバーテッドロウ", pt: "Remada invertida na mesa", ro: "Tracțiune inversată la masă" },
      bentOverRow:       { en: "Dumbbell bent-over row",       fr: "Rowing buste penché haltères", ja: "ダンベル・ベントオーバーロウ", pt: "Remada curvada com halteres", ro: "Ramat aplecat cu gantere" },
      latPulldownOrPullup:{ en: "Pull-up / lat pulldown",      fr: "Traction / tirage vertical",   ja: "懸垂／ラットプルダウン", pt: "Barra fixa / puxada alta", ro: "Tracțiuni / tras la helcometru" },
      facePullBand:      { en: "Band face pull",               fr: "Face pull élastique",           ja: "バンド・フェイスプル",   pt: "Face pull com elástico",   ro: "Tracțiune la față cu bandă" },
      plank:             { en: "Plank",                        fr: "Gainage planche",               ja: "プランク",               pt: "Prancha",                  ro: "Scândură (plank)" },
      deadBug:           { en: "Dead bug",                     fr: "Dead bug",                       ja: "デッドバグ",             pt: "Dead bug",                 ro: "Dead bug" },
      sidePlank:         { en: "Side plank",                   fr: "Gainage latéral",                ja: "サイドプランク",         pt: "Prancha lateral",          ro: "Scândură laterală" },
      weightedPlank:     { en: "Weighted plank",                fr: "Planche lestée",                 ja: "加重プランク",           pt: "Prancha com peso",         ro: "Scândură cu greutate" },
      palloffPress:      { en: "Band Pallof press",             fr: "Pallof press élastique",         ja: "バンド・パロフプレス",   pt: "Pallof press com elástico", ro: "Pallof press cu bandă" },
      farmerCarry:       { en: "Farmer's carry",                fr: "Marche du fermier",              ja: "ファーマーズキャリー",   pt: "Farmer's carry",           ro: "Farmer's carry" },
      burpee:            { en: "Burpee",                        fr: "Burpee",                         ja: "バーピー",               pt: "Burpee",                   ro: "Burpee" },
      mountainClimber:   { en: "Mountain climber",              fr: "Mountain climber",               ja: "マウンテンクライマー",   pt: "Mountain climber",         ro: "Mountain climber" },
      jumpingJack:       { en: "Jumping jack",                  fr: "Jumping jack",                   ja: "ジャンピングジャック",   pt: "Polichinelo",              ro: "Jumping jack" },
      marchInPlace:      { en: "March in place",                fr: "Marche sur place",                ja: "その場足踏み",           pt: "Marcha estacionária",      ro: "Mers pe loc" },
      sitToStand:        { en: "Sit-to-stand",                  fr: "Assis-debout",                    ja: "サイド・トゥ・スタンド", pt: "Sentar e levantar",        ro: "Așezat-ridicat" },
      stepTouch:         { en: "Step-touch",                    fr: "Pas chassé",                      ja: "ステップタッチ",         pt: "Passo lateral",            ro: "Pas lateral" },
      kettlebellSwing:   { en: "Kettlebell swing",              fr: "Kettlebell swing",                ja: "ケトルベルスイング",     pt: "Kettlebell swing",         ro: "Kettlebell swing" },
      rowMachineInterval:{ en: "Rowing machine intervals",     fr: "Intervalles rameur",              ja: "ローイングマシン・インターバル", pt: "Intervalos no remo", ro: "Intervale la vâslă" },
      battleRopes:       { en: "Battle ropes",                  fr: "Battle ropes",                    ja: "バトルロープ",           pt: "Battle ropes",             ro: "Battle ropes" },
      kettlebellSwingLight:{ en: "Light kettlebell swing",     fr: "Kettlebell swing léger",          ja: "軽量ケトルベルスイング", pt: "Kettlebell swing leve",    ro: "Kettlebell swing ușor" },
      rowMachineSteady:  { en: "Rowing machine, steady pace",  fr: "Rameur, allure régulière",        ja: "ローイングマシン（一定ペース）", pt: "Remo em ritmo constante", ro: "Vâslă, ritm constant" },
      farmerCarryInterval:{ en: "Farmer's carry intervals",    fr: "Intervalles marche du fermier",   ja: "ファーマーズキャリー・インターバル", pt: "Intervalos de farmer's carry", ro: "Intervale farmer's carry" },
      childsPose:        { en: "Child's pose",                  fr: "Posture de l'enfant",             ja: "チャイルドポーズ",       pt: "Postura da criança",       ro: "Poziția copilului" },
      hamstringStretch:  { en: "Hamstring stretch",             fr: "Étirement ischio-jambiers",       ja: "ハムストリングストレッチ", pt: "Alongamento de posterior de coxa", ro: "Întindere ischiogambieri" },
      hip9090Stretch:    { en: "90/90 hip stretch",             fr: "Étirement hanche 90/90",          ja: "90/90ヒップストレッチ", pt: "Alongamento de quadril 90/90", ro: "Întindere șold 90/90" },
      boxBreathing:      { en: "Box breathing",                 fr: "Respiration carrée",              ja: "ボックスブリージング",   pt: "Respiração quadrada",      ro: "Respirație în cutie" },
    },
  },

  // ── TECHNIQUE MAP ────────────────────────────────────────────────────────
  techmap: {
    pageTag:      { en: "Interactive", fr: "Interactif", ja: "インタラクティブ", pt: "Interativo", ro: "Interactiv" },
    pageTitle:    { en: "Technique Map", fr: "Carte des Techniques", ja: "テクニックマップ", pt: "Mapa de Técnicas", ro: "Harta Tehnicilor" },
    pageSubtitle: { en: "Techniques by type and relationship — click any technique to see its description and what it connects to.", fr: "Les techniques par type et par relation — cliquez sur une technique pour voir sa description et ses connexions.", ja: "タイプと関連性によるテクニック一覧 — テクニックをクリックすると説明と関連するテクニックが表示されます。", pt: "Técnicas por tipo e relação — clique em qualquer técnica para ver sua descrição e conexões.", ro: "Tehnici după tip și relație — apasă pe o tehnică pentru a-i vedea descrierea și conexiunile." },
    filterLbl:    { en: "Show", fr: "Afficher", ja: "表示", pt: "Mostrar", ro: "Afișează" },
    typePosition:   { en: "Positions",   fr: "Positions",     ja: "ポジション",   pt: "Posições",     ro: "Poziții" },
    typeTransition: { en: "Transitions", fr: "Transitions",   ja: "トランジション", pt: "Transições",   ro: "Tranziții" },
    typeSubmission: { en: "Submissions", fr: "Soumissions",   ja: "サブミッション", pt: "Finalizações", ro: "Submisii" },
    legendPosition:   { en: "Positions — guards, dominant control", fr: "Positions — gardes, contrôle dominant", ja: "ポジション — ガード、支配的コントロール", pt: "Posições — guardas, controle dominante", ro: "Poziții — gărzi, control dominant" },
    legendTransition: { en: "Transitions — passes, sweeps, escapes", fr: "Transitions — passages, renversements, échappées", ja: "トランジション — パス、スイープ、エスケープ", pt: "Transições — passagens, raspagens, fugas", ro: "Tranziții — treceri, răsturnări, evadări" },
    legendSubmission: { en: "Submissions — chokes, joint locks", fr: "Soumissions — étranglements, clés articulaires", ja: "サブミッション — 絞め技、関節技", pt: "Finalizações — estrangulamentos, chaves de articulação", ro: "Submisii — sufocări, blocaje articulare" },
    emptyPanel:   { en: "Select a technique on the map to see its description and connections.", fr: "Sélectionnez une technique sur la carte pour voir sa description et ses connexions.", ja: "マップ上のテクニックを選択すると、説明と関連するテクニックが表示されます。", pt: "Selecione uma técnica no mapa para ver sua descrição e conexões.", ro: "Selectează o tehnică pe hartă pentru a-i vedea descrierea și conexiunile." },
    connectsTo:   { en: "Connects to", fr: "Se connecte à", ja: "接続先", pt: "Conecta-se a", ro: "Se conectează la" },
    footNote:     { en: "Node positions are generated by a small force-directed layout so related techniques cluster naturally. Relationships shown are common, representative transitions — not exhaustive or purely directional.", fr: "La position des nœuds est générée par un algorithme de disposition à forces qui regroupe naturellement les techniques liées. Les relations affichées sont des transitions courantes et représentatives — non exhaustives ni strictement directionnelles.", ja: "ノードの配置は簡易的な力学レイアウトによって生成されており、関連するテクニックが自然にクラスター化されます。表示されている関連性は代表的で一般的な遷移であり、網羅的または一方向的なものではありません。", pt: "As posições dos nós são geradas por um layout de força simples, para que técnicas relacionadas se agrupem naturalmente. As relações mostradas são transições comuns e representativas — não exaustivas nem estritamente direcionais.", ro: "Pozițiile nodurilor sunt generate printr-un algoritm simplu bazat pe forțe, astfel încât tehnicile înrudite se grupează natural. Relațiile afișate sunt tranziții comune, reprezentative — nu exhaustive și nu strict direcționale." },
    subcats: {
      guard:     { en: "Guards",             fr: "Gardes",              ja: "ガード",             pt: "Guardas",              ro: "Gărzi" },
      dominant:  { en: "Dominant Control",   fr: "Contrôle Dominant",   ja: "支配的コントロール", pt: "Controle Dominante",   ro: "Control Dominant" },
      guardPass: { en: "Guard Passes",       fr: "Passages de Garde",   ja: "ガードパス",         pt: "Passagens de Guarda",  ro: "Treceri de Gardă" },
      sweep:     { en: "Sweeps",             fr: "Renversements",       ja: "スイープ",           pt: "Raspagens",            ro: "Răsturnări" },
      escape:    { en: "Escapes",            fr: "Échappées",           ja: "エスケープ",         pt: "Fugas",                ro: "Evadări" },
      choke:     { en: "Chokes & Strangles", fr: "Étranglements",       ja: "絞め技",             pt: "Estrangulamentos",     ro: "Sufocări" },
      jointLock: { en: "Joint Locks",        fr: "Clés Articulaires",   ja: "関節技",             pt: "Chaves de Articulação",ro: "Blocaje Articulare" },
    },
  },

  // ── WHAT'S NEW ───────────────────────────────────────────────────────────
  whatsNew: {
    pageTag:   { en: "Updates", fr: "Mises à jour", ja: "更新情報", pt: "Atualizações", ro: "Actualizări" },
    pageTitle: { en: "What's New?", fr: "Nouveautés", ja: "更新情報", pt: "Novidades", ro: "Noutăți" },
    // ── News page, 2026-10-03 ───────────────────────────────────────────
    // What's New stopped being only a site changelog: see data/updates.js.
    pageSub:   { en: "News from the mats, changes to the range, and updates to this site. Newest first.", fr: "Les nouvelles du tatami, les changements de gamme et les mises à jour du site. Du plus récent au plus ancien.", ja: "マットからのニュース、ラインナップの変更、サイトの更新。新しい順に掲載しています。", pt: "Notícias do tatame, mudanças na linha e atualizações deste site. Das mais recentes às mais antigas.", ro: "Vești de pe saltea, schimbări în gamă și actualizări ale site-ului. Cele mai noi primele." },
    filterLbl: { en: "Filter updates", fr: "Filtrer les nouveautés", ja: "更新を絞り込む", pt: "Filtrar novidades", ro: "Filtrează noutățile" },
    kinds: {
      all:   { en: "All", fr: "Tout", ja: "すべて", pt: "Tudo", ro: "Toate" },
      mat:   { en: "From the mat", fr: "Depuis le tatami", ja: "マットから", pt: "Do tatame", ro: "De pe saltea" },
      range: { en: "The range", fr: "La gamme", ja: "ラインナップ", pt: "A linha", ro: "Gama" },
      site:  { en: "The site", fr: "Le site", ja: "サイト", pt: "O site", ro: "Site-ul" },
    },
    siteNote:   { en: "What changed on this website, kept as a plain log.", fr: "Ce qui a changé sur ce site, tenu comme un simple journal.", ja: "このサイトの変更点を、シンプルな記録として残しています。", pt: "O que mudou neste site, mantido como um registro simples.", ro: "Ce s-a schimbat pe acest site, păstrat ca un jurnal simplu." },
    readUpdate: { en: "Read the update", fr: "Lire l'actualité", ja: "記事を読む", pt: "Ler a notícia", ro: "Citește știrea" },
    allUpdates: { en: "All updates", fr: "Toutes les nouveautés", ja: "すべての更新", pt: "Todas as novidades", ro: "Toate noutățile" },
    details:    { en: "Details", fr: "Détails", ja: "詳細", pt: "Detalhes", ro: "Detalii" },
    // "Not for sale" is on the photograph itself, not only in the text
    // beside it: a picture of someone wearing a garment is the strongest
    // "you can buy this" signal on the site, and nothing can be bought.
    trialBadge: { en: "Trial phase · Not for sale", fr: "Phase d'essai · Pas en vente", ja: "試用フェーズ · 未販売", pt: "Fase de testes · Não está à venda", ro: "Fază de testare · Nu este de vânzare" },
    // {n} is replaced with the number. Japanese puts it mid-phrase, which
    // is why this is a pattern and not a number followed by a word.
    photoCount: { en: "{n} photographs", fr: "{n} photographies", ja: "写真{n}枚", pt: "{n} fotografias", ro: "{n} fotografii" },
    morePhotos: { en: "+ {n} more", fr: "+ {n} autres", ja: "他{n}枚", pt: "+ {n} mais", ro: "+ încă {n}" },
    seePhotos:  { en: "See the photos", fr: "Voir les photos", ja: "写真を見る", pt: "Ver as fotos", ro: "Vezi fotografiile" },
    glanceTitle:      { en: "At a glance", fr: "En bref", ja: "概要", pt: "Em resumo", ro: "Pe scurt" },
    glanceGarment:    { en: "Garment", fr: "Pièce", ja: "アイテム", pt: "Peça", ro: "Articol" },
    glanceStatus:     { en: "Status", fr: "Statut", ja: "状況", pt: "Status", ro: "Stare" },
    glanceStatusVal:  { en: "Trial samples, worn and tested", fr: "Échantillons d'essai, portés et testés", ja: "試用サンプル（着用・テスト中）", pt: "Amostras de teste, vestidas e testadas", ro: "Mostre de test, purtate și testate" },
    glanceForSale:    { en: "For sale", fr: "En vente", ja: "販売", pt: "À venda", ro: "De vânzare" },
    glanceForSaleVal: { en: "Not yet", fr: "Pas encore", ja: "まだ販売していません", pt: "Ainda não", ro: "Nu încă" },
    glanceDrop:       { en: "First drop", fr: "Première collection", ja: "ファーストドロップ", pt: "Primeira coleção", ro: "Prima colecție" },
    galleryTitle: { en: "From the sessions", fr: "Pendant les séances", ja: "練習の様子", pt: "Dos treinos", ro: "De la antrenamente" },
    facesNote:    { en: "Faces are blurred on purpose. The people in these photographs are training, not modelling.", fr: "Les visages sont floutés volontairement. Les personnes sur ces photographies s'entraînent, elles ne posent pas.", ja: "顔は意図的にぼかしています。写っているのはモデルではなく、練習している人たちです。", pt: "Os rostos foram desfocados de propósito. As pessoas nestas fotografias estão treinando, não posando.", ro: "Fețele sunt estompate intenționat. Oamenii din aceste fotografii se antrenează, nu pozează." },
    seeRashguard: { en: "See the rashguard in the shop", fr: "Voir le rashguard dans la boutique", ja: "ショップでラッシュガードを見る", pt: "Ver o rashguard na loja", ro: "Vezi rashguard-ul în magazin" },
  },

  // Strings added by the 2026-07 revamp — see i18n-additions.js
  ui: UI,

};

// Helper: get translation for current language
export function t(obj, lang) {
  if (!obj) return "";
  return obj[lang] || obj["en"] || "";
}
