// ─── i18n.js — All UI translations for SubmitologY ───────────────────────────
// Languages: en (English), fr (French), ja (Japanese), pt (Brazilian Portuguese), ro (Romanian)

export const LANGUAGES = [
  { code: "en", label: "English",    flag: "🇬🇧" },
  { code: "fr", label: "Français",   flag: "🇫🇷" },
  { code: "ja", label: "日本語",      flag: "🇯🇵" },
  { code: "pt", label: "Português",  flag: "🇧🇷" },
  { code: "ro", label: "Română",     flag: "🇷🇴" },
];

export const T = {

  // ── NAV ──────────────────────────────────────────────────────────────────
  nav: {
    overview:   { en: "Overview",   fr: "Accueil",   ja: "概要",     pt: "Visão Geral", ro: "Prezentare" },
    concepts:   { en: "Concepts",   fr: "Concepts",  ja: "概念",     pt: "Conceitos",   ro: "Concepte"   },
    techniques: { en: "Techniques", fr: "Techniques",ja: "技術",     pt: "Técnicas",    ro: "Tehnici"    },
    about:      { en: "About",      fr: "À propos",  ja: "について", pt: "Sobre",       ro: "Despre"     },
    merchandise:{ en: "Shop",       fr: "Boutique",  ja: "グッズ",   pt: "Loja",        ro: "Produse"    },
    mentalHealth:{ en: "Mental Health", fr: "Santé Mentale", ja: "メンタルヘルス", pt: "Saúde Mental", ro: "Sănătate Mintală" },
    strength:   { en: "Strength & Conditioning", fr: "Force & Préparation Physique", ja: "筋力・コンディショニング", pt: "Força & Condicionamento", ro: "Forță & Pregătire Fizică" },
  },

  // ── SITE-WIDE MISSION BANNER ────────────────────────────────────────────
  banner: {
    text: { en: "SubmitologY plans to donate 1% of profits to mental health causes across Singapore & SEA, starting 2027", fr: "SubmitologY prévoit de reverser 1% de ses profits à des causes de santé mentale à Singapour et en Asie du Sud-Est, à partir de 2027", ja: "SubmitologYは2027年より、利益の1%をシンガポールおよび東南アジアのメンタルヘルス関連団体に寄付する予定です", pt: "A SubmitologY planeja doar 1% dos lucros a causas de saúde mental em Singapura e no Sudeste Asiático, a partir de 2027", ro: "SubmitologY planifică să doneze 1% din profit unor cauze de sănătate mintală din Singapore și Asia de Sud-Est, începând cu 2027" },
    cta:  { en: "Learn more →", fr: "En savoir plus →", ja: "詳しく見る →", pt: "Saiba mais →", ro: "Află mai multe →" },
  },

  // ── OVERVIEW ─────────────────────────────────────────────────────────────
  overview: {
    tag:         { en: "BJJ Apparel · Community · Mental Health Mission", fr: "Vêtements BJJ · Communauté · Mission Santé Mentale", ja: "BJJアパレル・コミュニティ・メンタルヘルスミッション", pt: "Vestuário BJJ · Comunidade · Missão de Saúde Mental", ro: "Îmbrăcăminte BJJ · Comunitate · Misiune Sănătate Mintală" },
    titleLine1:  { en: "The Study of Submission",  fr: "L'Étude de la Soumission",  ja: "サブミッションの探求",   pt: "O Estudo da Submissão",   ro: "Studiul Submisiei" },
    titleLine2:  { en: "The Science of Resilience", fr: "La Science de la Résilience", ja: "レジリエンスの科学",     pt: "A Ciência da Resiliência", ro: "Știința Rezilienței" },
    body1:       { en: "SubmitologY is a Singapore-based Brazilian Jiu-Jitsu (BJJ) apparel and merchandise brand for the mid-range quality segment across Singapore and Southeast Asia. Every collection is built on a distinctive social mission: using BJJ as a vehicle for mental health awareness, recovery, and community resilience — with 1% of profits planned to be donated to mental health causes once the company launches.", fr: "SubmitologY est une marque de vêtements et de produits dérivés de Jiu-Jitsu Brésilien (BJJ) basée à Singapour, pour le segment de qualité moyenne-supérieure à Singapour et en Asie du Sud-Est. Chaque collection repose sur une mission sociale distinctive : utiliser le BJJ comme vecteur de sensibilisation à la santé mentale, de rétablissement et de résilience communautaire — avec 1% des profits qu'il est prévu de reverser à des causes de santé mentale une fois l'entreprise lancée.", ja: "SubmitologYはシンガポールを拠点とするブラジリアン柔術（BJJ）アパレル・グッズブランドで、シンガポールおよび東南アジア全域のミッドレンジ品質層向けです。すべてのコレクションは独自の社会的使命に基づいています：BJJをメンタルヘルスの啓発、回復、そしてコミュニティのレジリエンスを促進する手段として活用し、会社の設立後、利益の1%をメンタルヘルス関連の活動に寄付する計画です。", pt: "SubmitologY é uma marca de vestuário e produtos de Brazilian Jiu-Jitsu (BJJ) sediada em Singapura, para o segmento de qualidade intermediária em Singapura e no Sudeste Asiático. Cada coleção é construída sobre uma missão social distinta: usar o BJJ como veículo para a conscientização sobre saúde mental, recuperação e resiliência comunitária — com o plano de doar 1% dos lucros a causas de saúde mental assim que a empresa for lançada.", ro: "SubmitologY este un brand de îmbrăcăminte și produse pentru Jiu-Jitsu Brazilian (BJJ), cu sediul în Singapore, pentru segmentul de calitate medie din Singapore și Asia de Sud-Est. Fiecare colecție este construită pe o misiune socială distinctă: folosirea BJJ ca vehicul pentru conștientizarea sănătății mintale, recuperare și reziliență comunitară — cu planul de a dona 1% din profit unor cauze de sănătate mintală odată ce compania va fi lansată." },
    body2:       { en: "The name SubmitologY — \"the study of submission\" — carries a deliberate double meaning: the technical art of the submission in grappling, and the psychological act of submitting to one's struggles in order to grow through them. This dual identity forms the intellectual and emotional core of the brand.", fr: "Le nom SubmitologY — « l'étude de la soumission » — porte une double signification délibérée : l'art technique de la soumission en grappling, et l'acte psychologique de se soumettre à ses luttes afin d'en grandir. Cette double identité forme le cœur intellectuel et émotionnel de la marque.", ja: "SubmitologYという名前 —「サブミッションの探求」— には意図的な二重の意味が込められています：組技における技術的なサブミッション（極め技）の芸術と、困難を乗り越えて成長するために自らの苦闘に向き合い服従するという心理的な行為です。この二重のアイデンティティが、ブランドの知的・感情的な核を形成しています。", pt: "O nome SubmitologY — \"o estudo da submissão\" — carrega um duplo significado deliberado: a arte técnica da finalização (submissão) no grappling, e o ato psicológico de se submeter às próprias lutas para crescer através delas. Essa identidade dupla forma o núcleo intelectual e emocional da marca.", ro: "Numele SubmitologY — „studiul submisiei” — poartă un dublu sens deliberat: arta tehnică a submisiei în grappling și actul psihologic de a te supune propriilor lupte pentru a crește prin ele. Această identitate dublă formează nucleul intelectual și emoțional al brandului." },
    exploreCta:  { en: "Explore Techniques →", fr: "Explorer les Techniques →", ja: "技術を探索する →", pt: "Explorar Técnicas →", ro: "Explorează Tehnicile →" },
    conceptsCta: { en: "Basic Concepts",       fr: "Concepts de base",          ja: "基本概念",         pt: "Conceitos Básicos",   ro: "Concepte de bază" },
    merchCta:    { en: "Shop the Gear →",      fr: "Voir la Boutique →",        ja: "グッズを見る →",   pt: "Ver a Loja →",        ro: "Vezi Produsele →" },
    missionCta:  { en: "Our Mission",          fr: "Notre Mission",             ja: "私たちの使命",     pt: "Nossa Missão",        ro: "Misiunea noastră" },
    scCta:       { en: "Strength & Conditioning", fr: "Force & Préparation Physique", ja: "筋力・コンディショニング", pt: "Força & Condicionamento", ro: "Forță & Pregătire Fizică" },
    statTech:    { en: "Techniques Indexed",   fr: "Techniques indexées",       ja: "技術収録数",       pt: "Técnicas Indexadas",  ro: "Tehnici indexate" },
    statCats:    { en: "Categories",           fr: "Catégories",                ja: "カテゴリー",       pt: "Categorias",          ro: "Categorii" },
    statDiffs:   { en: "Difficulty Levels",    fr: "Niveaux de difficulté",     ja: "難易度レベル",     pt: "Níveis de Dificuldade",ro: "Niveluri de dificultate" },
    statCombo:   { en: "Combinations",         fr: "Combinaisons",              ja: "組み合わせ",       pt: "Combinações",         ro: "Combinații" },
    statGive:    { en: "Profits to Mental Health (from 2027)", fr: "Des profits pour la santé mentale (dès 2027)", ja: "利益をメンタルヘルスへ（2027年より）", pt: "Do Lucro para Saúde Mental (a partir de 2027)", ro: "Din profit pentru sănătate mintală (din 2027)" },
    techCount:   { en: "Techniques",           fr: "Techniques",                ja: "技術",             pt: "Técnicas",            ro: "Tehnici" },
  },

  // ── CONCEPTS ─────────────────────────────────────────────────────────────
  concepts: {
    pageTitle:    { en: "Basic Concepts",  fr: "Concepts de base", ja: "基本概念",       pt: "Conceitos Básicos", ro: "Concepte de bază" },
    pageSubtitle: { en: "The mental models every BJJ practitioner should internalise from day one.", fr: "Les modèles mentaux que chaque pratiquant de BJJ devrait intérioriser dès le premier jour.", ja: "すべてのBJJ練習者が初日から内面化すべきメンタルモデル。", pt: "Os modelos mentais que todo praticante de BJJ deve internalizar desde o primeiro dia.", ro: "Modelele mentale pe care fiecare practicant de BJJ ar trebui să le internalizeze din prima zi." },
  },

  // ── CONCEPTS CONTENT ─────────────────────────────────────────────────────
  conceptItems: [
    {
      icon: "⚖️",
      title: { en: "Positional Hierarchy", fr: "Hiérarchie positionnelle", ja: "ポジション階層", pt: "Hierarquia Posicional", ro: "Ierarhia pozițională" },
      body:  { en: "BJJ ranks positions by dominance: back control → mount → knee-on-belly → side control → guard. The higher on the ladder, the more control and submission options you have.", fr: "Le BJJ classe les positions par dominance : contrôle du dos → montée → genou sur le ventre → contrôle latéral → garde. Plus on monte, plus on a de contrôle et d'options de soumission.", ja: "BJJは支配度でポジションを順位付けします：バックコントロール→マウント→ニーオンベリー→サイドコントロール→ガード。上位ほどコントロールとサブミッションの選択肢が多くなります。", pt: "O BJJ classifica as posições por dominância: controle das costas → montada → joelho na barriga → controle lateral → guarda. Quanto mais alto na hierarquia, mais controle e opções de finalização você tem.", ro: "BJJ clasifică pozițiile după dominanță: controlul spatelui → montare → genunchi pe burtă → control lateral → gardă. Cu cât ești mai sus, cu atât ai mai mult control și mai multe opțiuni de submisie." },
    },
    {
      icon: "🔄",
      title: { en: "The Guard", fr: "La Garde", ja: "ガード", pt: "A Guarda", ro: "Garda" },
      body:  { en: "Unique to BJJ — fighting effectively from your back. The guard is not defensive; it is an attacking platform. Developing a strong guard changed martial arts forever.", fr: "Unique au BJJ — se battre efficacement sur le dos. La garde n'est pas défensive ; c'est une plateforme d'attaque. Développer une garde solide a changé les arts martiaux pour toujours.", ja: "BJJに固有の技術 — 仰向けから効果的に戦う。ガードは防御的ではなく攻撃的なプラットフォームです。強いガードの開発は武道を永遠に変えました。", pt: "Único no BJJ — lutar efetivamente de costas para o chão. A guarda não é defensiva; é uma plataforma de ataque. Desenvolver uma guarda forte mudou as artes marciais para sempre.", ro: "Unic în BJJ — luptând eficient de pe spate. Garda nu este defensivă; este o platformă de atac. Dezvoltarea unei gărzi puternice a schimbat artele marțiale pentru totdeauna." },
    },
    {
      icon: "🌊",
      title: { en: "Flowing & Chaining", fr: "Fluidité et enchaînements", ja: "フローとチェーン", pt: "Fluxo e Encadeamento", ro: "Fluiditate și înlănțuire" },
      body:  { en: "Techniques are rarely isolated. A failed armbar should flow into a triangle; a blocked triangle feeds an omoplata. Train combinations, not just individual moves.", fr: "Les techniques sont rarement isolées. Un armbar raté devrait se transformer en triangle ; un triangle bloqué alimente une omoplata. Entraînez des combinaisons, pas seulement des mouvements individuels.", ja: "技術は孤立していることはほとんどありません。失敗したアームバーはトライアングルに流れ込むべきです。ブロックされたトライアングルはオモプラタにつながります。個々の動きだけでなく、コンビネーションを練習しましょう。", pt: "As técnicas raramente são isoladas. Um armbar falhado deve fluir para um triângulo; um triângulo bloqueado alimenta uma omoplata. Treine combinações, não apenas movimentos individuais.", ro: "Tehnicile sunt rar izolate. Un armbar eșuat ar trebui să curgă într-un triunghi; un triunghi blocat alimentează o omoplata. Antrenați combinații, nu doar mișcări individuale." },
    },
    {
      icon: "🎯",
      title: { en: "Base & Posture", fr: "Base et posture", ja: "ベースとポスチャー", pt: "Base e Postura", ro: "Bază și postură" },
      body:  { en: "Before attacking, establish base (hips low, weight distributed) and posture (spine neutral). Neglecting these fundamentals is the fastest way to get submitted.", fr: "Avant d'attaquer, établissez la base (hanches basses, poids réparti) et la posture (colonne vertébrale neutre). Négliger ces fondamentaux est le moyen le plus rapide d'être soumis.", ja: "攻撃する前に、ベース（腰を低く、体重を分散）とポスチャー（脊椎を中立）を確立します。これらの基本を怠ることは、サブミットされる最速の方法です。", pt: "Antes de atacar, estabeleça a base (quadris baixos, peso distribuído) e a postura (coluna neutra). Negligenciar esses fundamentos é a maneira mais rápida de ser finalizado.", ro: "Înainte de a ataca, stabiliți baza (șolduri joase, greutate distribuită) și postura (coloana neutră). Neglijarea acestor fundamente este cel mai rapid mod de a fi supus." },
    },
    {
      icon: "⏱️",
      title: { en: "Timing Over Force", fr: "Le timing plutôt que la force", ja: "力よりタイミング", pt: "Timing sobre Força", ro: "Timing înainte de forță" },
      body:  { en: "BJJ was designed so a smaller person can overcome a larger one. Timing, leverage, and technique consistently beat raw strength — especially over a long roll.", fr: "Le BJJ a été conçu pour qu'une personne plus petite puisse surmonter une plus grande. Le timing, l'effet de levier et la technique battent constamment la force brute — surtout sur un long assaut.", ja: "BJJは体の小さい人が大きな人を克服できるように設計されました。タイミング、レバレッジ、技術は一貫して生の力を打ち負かします — 特に長いロールでは。", pt: "O BJJ foi projetado para que uma pessoa menor possa superar uma maior. Timing, alavanca e técnica consistentemente superam a força bruta — especialmente em um rolar longo.", ro: "BJJ a fost conceput astfel încât o persoană mai mică să poată depăși una mai mare. Timing-ul, pârghia și tehnica înving în mod constant forța brută — mai ales într-un antrenament lung." },
    },
    {
      icon: "🦺",
      title: { en: "Tap Early, Tap Often", fr: "Tapoter tôt, tapoter souvent", ja: "早めにタップ、よくタップ", pt: "Toque cedo, toque com frequência", ro: "Tapează devreme, tapează des" },
      body:  { en: "Tapping is not failure — it's the mechanism that lets training continue safely. Pride in refusing to tap leads to injuries. The mats will always be there tomorrow.", fr: "Tapoter n'est pas un échec — c'est le mécanisme qui permet à l'entraînement de se poursuivre en toute sécurité. La fierté de refuser de tapoter entraîne des blessures. Les tatamis seront toujours là demain.", ja: "タップは失敗ではありません — 安全にトレーニングを続けるためのメカニズムです。タップを拒否することへの誇りはけがにつながります。マットは常に明日もそこにあります。", pt: "Tocar não é falha — é o mecanismo que permite que o treino continue com segurança. O orgulho em recusar tocar leva a lesões. Os tapetes sempre estarão lá amanhã.", ro: "Taparea nu este un eșec — este mecanismul care permite antrenamentul să continue în siguranță. Mândria de a refuza să tapezi duce la răni. Salteaua va fi întotdeauna acolo mâine." },
    },
  ],

  // ── TECHNIQUES PAGE ───────────────────────────────────────────────────────
  techniques: {
    typeLabel:    { en: "Type",    fr: "Type",       ja: "タイプ",    pt: "Tipo",     ro: "Tip"     },
    levelLabel:   { en: "Level",   fr: "Niveau",     ja: "レベル",    pt: "Nível",    ro: "Nivel"   },
    results:      { en: "results", fr: "résultats",  ja: "件",        pt: "resultados",ro: "rezultate" },
    result:       { en: "result",  fr: "résultat",   ja: "件",        pt: "resultado", ro: "rezultat"  },
    noResults:    { en: "No techniques match these filters.", fr: "Aucune technique ne correspond à ces filtres.", ja: "フィルターに一致する技術がありません。", pt: "Nenhuma técnica corresponde a esses filtros.", ro: "Nicio tehnică nu corespunde acestor filtre." },
    openCta:      { en: "Open →",  fr: "Ouvrir →",  ja: "開く →",   pt: "Abrir →",  ro: "Deschide →" },
  },

  // ── CATEGORY NAMES (used in filters + pills) ──────────────────────────────
  cats: {
    All:         { en: "All",        fr: "Tous",       ja: "すべて",   pt: "Todos",     ro: "Toate"     },
    Guards:      { en: "Guards",     fr: "Gardes",     ja: "ガード",   pt: "Guardas",   ro: "Gărzi"     },
    Submissions: { en: "Submissions",fr: "Soumissions",ja: "サブミッション", pt: "Finalizações", ro: "Submisii" },
    Transitions: { en: "Transitions",fr: "Transitions",ja: "トランジション", pt: "Transições",  ro: "Tranziții" },
    Takedowns:   { en: "Takedowns",  fr: "Projections",ja: "テイクダウン",   pt: "Quedas",      ro: "Proiectări" },
    "Dark BJJ":  { en: "Dark BJJ",   fr: "BJJ Sombre", ja: "ダークBJJ",     pt: "BJJ Negro",   ro: "BJJ Întunecat" },
  },

  // ── DIFFICULTY NAMES ──────────────────────────────────────────────────────
  diffs: {
    All:          { en: "All",          fr: "Tous",          ja: "すべて",  pt: "Todos",       ro: "Toate"       },
    Beginner:     { en: "Beginner",     fr: "Débutant",      ja: "初心者",  pt: "Iniciante",   ro: "Începător"   },
    Intermediate: { en: "Intermediate", fr: "Intermédiaire", ja: "中級者",  pt: "Intermediário",ro: "Intermediar" },
    Advanced:     { en: "Advanced",     fr: "Avancé",        ja: "上級者",  pt: "Avançado",    ro: "Avansat"     },
  },

  // ── MODAL ─────────────────────────────────────────────────────────────────
  modal: {
    keyPoints:  { en: "Key Points",           fr: "Points clés",          ja: "重要ポイント",   pt: "Pontos-chave",        ro: "Puncte cheie"         },
    watchYT:    { en: "▶ Watch on YouTube",   fr: "▶ Voir sur YouTube",   ja: "▶ YouTubeで見る", pt: "▶ Ver no YouTube",   ro: "▶ Urmărește pe YouTube"},
  },

  // ── ABOUT PAGE ────────────────────────────────────────────────────────────
  about: {
    pageTitle:   { en: "About SubmitologY", fr: "À propos de SubmitologY", ja: "SubmitologYについて", pt: "Sobre o SubmitologY", ro: "Despre SubmitologY" },
    mission:     { en: "To build a BJJ brand that equips athletes on and off the mat — through quality gear, purposeful design, community sharing and a commitment to mental health advocacy.", fr: "Construire une marque de BJJ qui équipe les athlètes sur et en dehors du tatami — à travers un équipement de qualité, un design porteur de sens, le partage communautaire et un engagement envers la défense de la santé mentale.", ja: "マットの上でもマットの外でも、アスリートを支えるBJJブランドを築くこと — 高品質なギア、意義あるデザイン、コミュニティの共有、そしてメンタルヘルス支援への取り組みを通じて。", pt: "Construir uma marca de BJJ que equipa atletas dentro e fora do tatame — por meio de equipamentos de qualidade, design com propósito, compartilhamento comunitário e um compromisso com a defesa da saúde mental.", ro: "Să construim un brand BJJ care echipează sportivii pe și în afara saltelei — prin echipament de calitate, design cu scop, împărtășire comunitară și un angajament față de susținerea sănătății mintale." },
    body1:       { en: "SubmitologY is a structured BJJ knowledge base built to help practitioners of all levels explore positions, submissions, transitions, and takedowns in an organised, visual way.", fr: "SubmitologY est une base de connaissances BJJ structurée pour aider les pratiquants de tous niveaux à explorer les positions, soumissions, transitions et projections de manière organisée et visuelle.", ja: "SubmitologYは、あらゆるレベルの練習者がポジション、サブミッション、トランジション、テイクダウンを整理された視覚的な方法で探索できるように作られた構造化されたBJJナレッジベースです。", pt: "O SubmitologY é uma base de conhecimento de BJJ estruturada para ajudar praticantes de todos os níveis a explorar posições, finalizações, transições e quedas de forma organizada e visual.", ro: "SubmitologY este o bază de cunoștințe BJJ structurată, concepută pentru a ajuta practicanții de toate nivelurile să exploreze pozițiile, submisiile, tranzițiile și proiectările într-un mod organizat și vizual." },
    body2:       { en: "Each technique entry includes a description, coaching key points, difficulty rating, and a link to external video resources.", fr: "Chaque entrée de technique comprend une description, des points clés d'entraînement, une évaluation de difficulté et un lien vers des ressources vidéo externes.", ja: "各技術エントリーには、説明、コーチングのキーポイント、難易度評価、外部ビデオリソースへのリンクが含まれています。", pt: "Cada entrada de técnica inclui uma descrição, pontos-chave de treino, classificação de dificuldade e um link para recursos de vídeo externos.", ro: "Fiecare intrare de tehnică include o descriere, puncte cheie de antrenament, evaluare a dificultății și un link către resurse video externe." },
    catsTitle:   { en: "Categories Explained", fr: "Catégories expliquées", ja: "カテゴリーの説明", pt: "Categorias Explicadas", ro: "Categorii explicate" },
    catDescs: {
      Guards:      { en: "Bottom positions to control, sweep, or submit.", fr: "Positions au sol pour contrôler, sweeper ou soumettre.", ja: "コントロール、スイープ、またはサブミットするための底部ポジション。", pt: "Posições de baixo para controlar, sweepear ou finalizar.", ro: "Poziții inferioare pentru a controla, mătura sau supune." },
      Submissions: { en: "Force a tap via joint locks or chokes.", fr: "Forcer un tapotement via des clés articulaires ou des étranglements.", ja: "関節技や絞め技でタップを強要する。", pt: "Forçar um toque via travamentos de articulação ou estrangulamentos.", ro: "Forțați taparea prin blocaje articulare sau sugrumări." },
      Transitions: { en: "Movement between positions — where grappling really lives.", fr: "Mouvement entre les positions — c'est là que vit vraiment le grappling.", ja: "ポジション間の移動 — グラップリングが本当に生きる場所。", pt: "Movimentação entre posições — onde o grappling realmente vive.", ro: "Mișcarea între poziții — unde trăiește cu adevărat grappling-ul." },
      Takedowns:   { en: "Getting the fight to the ground on your terms.", fr: "Amener le combat au sol selon vos conditions.", ja: "自分のペースで試合を地上に持ち込む。", pt: "Levar a luta ao chão nos seus termos.", ro: "Ducerea luptei la sol în condițiile tale." },
      "Dark BJJ":  { en: "High-risk techniques — study carefully, apply with control.", fr: "Techniques à haut risque — étudiez attentivement, appliquez avec contrôle.", ja: "高リスクな技術 — 注意深く研究し、コントロールして適用する。", pt: "Técnicas de alto risco — estude com cuidado, aplique com controle.", ro: "Tehnici cu risc ridicat — studiați cu atenție, aplicați cu control." },
    },
    footer:      { en: "Built with React · Images via Unsplash · Video links via YouTube", fr: "Construit avec React · Images via Unsplash · Liens vidéo via YouTube", ja: "Reactで構築 · 画像はUnsplash · 動画リンクはYouTube", pt: "Construído com React · Imagens via Unsplash · Links de vídeo via YouTube", ro: "Construit cu React · Imagini via Unsplash · Linkuri video via YouTube" },
    linksTitle:  { en: "More from SubmitologY", fr: "Plus de SubmitologY", ja: "SubmitologYのその他", pt: "Mais da SubmitologY", ro: "Mai multe de la SubmitologY" },
    linksBody:   { en: "SubmitologY is also a growing apparel brand and mental health advocate — 1% of profits are planned to be donated to mental health causes from 2027.", fr: "SubmitologY est aussi une marque de vêtements en pleine croissance et un défenseur de la santé mentale — 1% des profits devrait être reversé à des causes de santé mentale à partir de 2027.", ja: "SubmitologYは成長中のアパレルブランドでもあり、メンタルヘルスの支援者でもあります — 2027年より、利益の1%をメンタルヘルス関連の活動に寄付する計画です。", pt: "A SubmitologY também é uma marca de vestuário em crescimento e defensora da saúde mental — está previsto que 1% dos lucros seja doado a causas de saúde mental a partir de 2027.", ro: "SubmitologY este, de asemenea, un brand de îmbrăcăminte în creștere și un susținător al sănătății mintale — este planificat ca 1% din profit să fie donat unor cauze de sănătate mintală, începând cu 2027." },
    shopLink:    { en: "Shop the Gear →", fr: "Voir la Boutique →", ja: "グッズを見る →", pt: "Ver a Loja →", ro: "Vezi Produsele →" },
    missionLink: { en: "Our Mission →", fr: "Notre Mission →", ja: "私たちの使命 →", pt: "Nossa Missão →", ro: "Misiunea noastră →" },
    invitationTitle: { en: "The Invitation", fr: "L'Invitation", ja: "招待", pt: "O Convite", ro: "Invitația" },
    invitation:  { en: "We are not just building a gear brand. We are building a community that trains hard, talks openly, and submits to nothing except growth. Welcome to SubmitologY.", fr: "Nous ne construisons pas seulement une marque d'équipement. Nous construisons une communauté qui s'entraîne dur, qui parle ouvertement, et qui ne se soumet à rien d'autre qu'à la croissance. Bienvenue chez SubmitologY.", ja: "私たちは単なるギアブランドを作っているのではありません。ハードにトレーニングし、オープンに語り合い、成長以外の何ものにも屈しないコミュニティを築いています。SubmitologYへようこそ。", pt: "Não estamos apenas construindo uma marca de equipamentos. Estamos construindo uma comunidade que treina duro, fala abertamente e não se submete a nada além do crescimento. Bem-vindo à SubmitologY.", ro: "Nu construim doar un brand de echipamente. Construim o comunitate care se antrenează intens, vorbește deschis și nu se supune nimic altceva decât creșterii. Bine ai venit la SubmitologY." },
  },

  // ── MERCHANDISE / SHOP ────────────────────────────────────────────────────
  merch: {
    pageTag:      { en: "Launch Collection · Q1 2027", fr: "Collection de Lancement · T1 2027", ja: "ローンチコレクション · 2027年第1四半期", pt: "Coleção de Lançamento · T1 2027", ro: "Colecția de Lansare · T1 2027" },
    pageTitle:    { en: "Gear Built for the Mats",   fr: "Équipement Conçu pour le Tatami",       ja: "マットのために作られたギア",  pt: "Equipamento Feito para o Tatame",  ro: "Echipament Creat pentru Saltea" },
    pageSubtitle: { en: "Mid-range quality apparel — IBJJF-legal, durably built, and designed around the idea that every roll is also a rep for your mind. 1% of every sale goes to mental health causes.", fr: "Vêtements de qualité moyenne-supérieure — conformes IBJJF, durables, et pensés autour de l'idée que chaque combat est aussi un exercice pour l'esprit. 1% de chaque vente est reversé à des causes de santé mentale.", ja: "ミッドレンジ品質のアパレル — IBJJF準拠、耐久性のある作り、そして「すべてのロールは心のトレーニングでもある」という考えのもとにデザインされています。売上の1%はメンタルヘルス関連の活動に寄付されます。", pt: "Vestuário de qualidade intermediária — em conformidade com o IBJJF, construção durável, e pensado a partir da ideia de que cada round também treina a mente. 1% de cada venda é doado a causas de saúde mental.", ro: "Îmbrăcăminte de calitate medie — conformă IBJJF, construită durabil, gândită pornind de la ideea că fiecare rundă antrenează și mintea. 1% din fiecare vânzare este donat unor cauze de sănătate mintală." },
    notify:       { en: "Notify Me at Launch", fr: "Prévenez-moi au lancement", ja: "ローンチ時に通知を受け取る", pt: "Avise-me no Lançamento", ro: "Anunță-mă la lansare" },
    priceLbl:     { en: "Target Price",  fr: "Prix cible",        ja: "目標価格",        pt: "Preço-alvo",       ro: "Preț țintă"     },
    specLbl:      { en: "Spec",          fr: "Caractéristiques",  ja: "スペック",        pt: "Especificação",    ro: "Specificații"   },
    comingSoon:   { en: "Coming Q1 2027",fr: "Disponible T1 2027",ja: "2027年第1四半期発売", pt: "Chegando no T1 2027", ro: "Disponibil T1 2027" },
    pillarsTitle: { en: "Why SubmitologY Gear",  fr: "Pourquoi le matériel SubmitologY", ja: "SubmitologYギアの理由", pt: "Por que o Equipamento SubmitologY", ro: "De ce echipamentul SubmitologY" },
    pillars: [
      { title: { en: "Quality Without Compromise", fr: "Qualité sans compromis", ja: "妥協なき品質", pt: "Qualidade sem Compromisso", ro: "Calitate fără compromis" },
        body:  { en: "IBJJF-compliant, mid-range gear built to last through years of training.", fr: "Équipement conforme IBJJF, milieu de gamme, conçu pour durer des années d'entraînement.", ja: "IBJJF準拠、何年ものトレーニングに耐えるミッドレンジギア。", pt: "Equipamento em conformidade com o IBJJF, de qualidade intermediária, feito para durar anos de treino.", ro: "Echipament conform IBJJF, de calitate medie, creat să reziste ani de antrenament." } },
      { title: { en: "Purpose-Driven Design", fr: "Design porteur de sens", ja: "目的を持ったデザイン", pt: "Design com Propósito", ro: "Design cu un scop" },
        body:  { en: "Every collection is tied to a mental health theme or story — not decoration for its own sake.", fr: "Chaque collection est liée à un thème ou une histoire de santé mentale — pas de la décoration gratuite.", ja: "すべてのコレクションはメンタルヘルスのテーマやストーリーと結びついています — 単なる装飾ではありません。", pt: "Cada coleção está ligada a um tema ou história de saúde mental — não é decoração pela decoração.", ro: "Fiecare colecție este legată de o temă sau o poveste despre sănătatea mintală — nu e decor gratuit." } },
      { title: { en: "Community Over Commerce", fr: "La communauté avant le commerce", ja: "商業よりコミュニティ", pt: "Comunidade Acima do Comércio", ro: "Comunitatea înaintea comerțului" },
        body:  { en: "Profits are reinvested into the BJJ and mental health community, not just the brand.", fr: "Les profits sont réinvestis dans la communauté BJJ et santé mentale, pas seulement dans la marque.", ja: "利益はブランドだけでなく、BJJとメンタルヘルスのコミュニティに再投資されます。", pt: "Os lucros são reinvestidos na comunidade de BJJ e saúde mental, não apenas na marca.", ro: "Profiturile sunt reinvestite în comunitatea BJJ și de sănătate mintală, nu doar în brand." } },
      { title: { en: "Southeast Asian Roots", fr: "Racines d'Asie du Sud-Est", ja: "東南アジアのルーツ", pt: "Raízes do Sudeste Asiático", ro: "Rădăcini din Asia de Sud-Est" },
        body:  { en: "Built in Singapore, celebrating the growing regional BJJ scene.", fr: "Conçu à Singapour, célébrant la scène BJJ régionale en pleine croissance.", ja: "シンガポールで生まれ、成長する地域のBJJシーンを称えます。", pt: "Criado em Singapura, celebrando a crescente cena de BJJ regional.", ro: "Creat în Singapore, celebrând scena BJJ regională în creștere." } },
    ],
  },

  // ── MENTAL HEALTH PAGE ───────────────────────────────────────────────────
  mh: {
    pageTag:      { en: "Our Mission", fr: "Notre Mission", ja: "私たちの使命", pt: "Nossa Missão", ro: "Misiunea noastră" },
    pageTitle:    { en: "Mental Health on the Mats", fr: "La Santé Mentale sur le Tatami", ja: "マットの上のメンタルヘルス", pt: "Saúde Mental no Tatame", ro: "Sănătatea mintală pe saltea" },
    planNote:     { en: "SubmitologY has not yet launched. The commitments below are planned to begin in 2027, alongside the brand's launch.", fr: "SubmitologY n'a pas encore été lancée. Les engagements ci-dessous sont prévus à partir de 2027, en même temps que le lancement de la marque.", ja: "SubmitologYはまだ設立されていません。以下の取り組みは、ブランドのローンチと同時に2027年より開始予定です。", pt: "A SubmitologY ainda não foi lançada. Os compromissos abaixo estão previstos para começar em 2027, junto com o lançamento da marca.", ro: "SubmitologY nu a fost încă lansată. Angajamentele de mai jos sunt planificate să înceapă în 2027, odată cu lansarea brandului." },
    lead:         { en: "The mental health benefits of Brazilian Jiu-Jitsu are well-documented and deeply felt within the community. Practitioners consistently report reductions in anxiety, depression, and PTSD symptoms. The mat is frequently described as \"the best therapy\" — a space where the mind is forced to be fully present, ego is checked, and resilience is built one roll at a time.", fr: "Les bienfaits du Jiu-Jitsu Brésilien sur la santé mentale sont bien documentés et profondément ressentis au sein de la communauté. Les pratiquants rapportent constamment une réduction de l'anxiété, de la dépression et des symptômes de stress post-traumatique. Le tatami est souvent décrit comme « la meilleure thérapie » — un espace où l'esprit est contraint d'être pleinement présent, où l'ego est mis de côté, et où la résilience se construit combat après combat.", ja: "ブラジリアン柔術がメンタルヘルスにもたらす効果は十分に文書化されており、コミュニティ内で深く実感されています。練習者は不安、うつ、PTSD症状の軽減を一貫して報告しています。マットはしばしば「最高のセラピー」と表現されます — 心が完全に「今」に集中させられ、エゴが抑えられ、レジリエンスが一つ一つのロールの中で築かれる場所です。", pt: "Os benefícios do Brazilian Jiu-Jitsu para a saúde mental são bem documentados e profundamente sentidos dentro da comunidade. Os praticantes relatam consistentemente reduções na ansiedade, depressão e sintomas de TEPT. O tatame é frequentemente descrito como \"a melhor terapia\" — um espaço onde a mente é forçada a estar totalmente presente, o ego é contido, e a resiliência é construída round a round.", ro: "Beneficiile Jiu-Jitsu Brazilian asupra sănătății mintale sunt bine documentate și resimțite profund în comunitate. Practicanții raportează constant reduceri ale anxietății, depresiei și simptomelor de stres post-traumatic. Salteaua este adesea descrisă drept „cea mai bună terapie” — un spațiu în care mintea este forțată să fie complet prezentă, ego-ul este ținut în frâu, iar reziliența se construiește rundă cu rundă." },
    lead2:        { en: "SubmitologY is building its brand identity around this truth, positioning BJJ not just as a sport, but as a mental health practice — one that deserves the same recognition as mindfulness, therapy, and exercise.", fr: "SubmitologY construit son identité de marque autour de cette vérité, positionnant le BJJ non seulement comme un sport, mais comme une pratique de santé mentale — méritant la même reconnaissance que la pleine conscience, la thérapie et l'exercice physique.", ja: "SubmitologYはこの真実を中心にブランドアイデンティティを構築しており、BJJを単なるスポーツとしてではなく、マインドフルネスやセラピー、運動と同様に認識されるべきメンタルヘルスの実践として位置づけています。", pt: "A SubmitologY está construindo sua identidade de marca em torno dessa verdade, posicionando o BJJ não apenas como um esporte, mas como uma prática de saúde mental — que merece o mesmo reconhecimento que mindfulness, terapia e exercício físico.", ro: "SubmitologY își construiește identitatea de brand în jurul acestui adevăr, poziționând BJJ nu doar ca sport, ci ca practică de sănătate mintală — care merită aceeași recunoaștere ca mindfulness-ul, terapia și exercițiul fizic." },
    donationTitle:{ en: "1% for Mental Health — Planned from 2027", fr: "1% pour la santé mentale — Prévu dès 2027", ja: "メンタルヘルスへの1%（2027年より予定）", pt: "1% para Saúde Mental — Previsto a partir de 2027", ro: "1% pentru sănătate mintală — planificat din 2027" },
    donationBody: { en: "Once SubmitologY launches, 1% of all revenue will be donated to mental health charities in Singapore and Southeast Asia, including organisations such as Samaritans of Singapore and the IMH Foundation. As the company has not yet launched, no donations have been made to date.", fr: "Une fois SubmitologY lancée, 1% de tous les revenus sera reversé à des associations de santé mentale à Singapour et en Asie du Sud-Est, notamment des organisations telles que Samaritans of Singapore et l'IMH Foundation. L'entreprise n'ayant pas encore été lancée, aucun don n'a été effectué à ce jour.", ja: "SubmitologYのローンチ後、全収益の1%は、Samaritans of SingaporeやIMH Foundationなど、シンガポールおよび東南アジアのメンタルヘルス関連団体に寄付される予定です。会社はまだ設立されていないため、現時点で寄付の実績はありません。", pt: "Assim que a SubmitologY for lançada, 1% de toda a receita será doado a instituições de saúde mental em Singapura e no Sudeste Asiático, incluindo organizações como a Samaritans of Singapore e a IMH Foundation. Como a empresa ainda não foi lançada, nenhuma doação foi feita até o momento.", ro: "Odată ce SubmitologY va fi lansată, 1% din toate veniturile va fi donat unor organizații caritabile de sănătate mintală din Singapore și Asia de Sud-Est, printre care Samaritans of Singapore și IMH Foundation. Deoarece compania nu a fost încă lansată, nu au fost făcute donații până în prezent." },
    pillarsTitle: { en: "The Social Impact Programme — Planned Initiatives", fr: "Le programme d'impact social — Initiatives prévues", ja: "社会貢献プログラム（予定されている取り組み）", pt: "O Programa de Impacto Social — Iniciativas Planejadas", ro: "Programul de impact social — inițiative planificate" },
    pillars: [
      { icon: "💛", title: { en: "1% Revenue Donation", fr: "1% des revenus reversé", ja: "収益の1%を寄付", pt: "Doação de 1% da Receita", ro: "Donație de 1% din venituri" },
        body: { en: "Planned from 2027: 1% of all revenue will be donated to mental health charities in Singapore and SEA.", fr: "Prévu à partir de 2027 : 1% de tous les revenus sera reversé à des associations de santé mentale à Singapour et en Asie du Sud-Est.", ja: "2027年より予定：全収益の1%をシンガポールおよび東南アジアのメンタルヘルス団体に寄付します。", pt: "Previsto a partir de 2027: 1% de toda a receita será doado a instituições de saúde mental em Singapura e no Sudeste Asiático.", ro: "Planificat din 2027: 1% din toate veniturile va fi donat unor organizații caritabile de sănătate mintală din Singapore și Asia de Sud-Est." } },
      { icon: "🎙️", title: { en: "\"Tap Out to Talk\"", fr: "« Tap Out to Talk »", ja: "「Tap Out to Talk」", pt: "\"Tap Out to Talk\"", ro: "„Tap Out to Talk”" },
        body: { en: "Planned: a content series featuring BJJ practitioners sharing their mental health journeys.", fr: "Prévu : une série de contenus mettant en avant des pratiquants de BJJ qui partagent leur parcours en santé mentale.", ja: "予定：BJJ練習者がメンタルヘルスの経験を語るコンテンツシリーズ。", pt: "Planejado: uma série de conteúdos com praticantes de BJJ compartilhando suas jornadas de saúde mental.", ro: "Planificat: o serie de conținut în care practicanți de BJJ își împărtășesc parcursul legat de sănătatea mintală." } },
      { icon: "🤝", title: { en: "Academy Partnerships", fr: "Partenariats avec les académies", ja: "アカデミーパートナーシップ", pt: "Parcerias com Academias", ro: "Parteneriate cu academii" },
        body: { en: "Planned: subsidised gear for BJJ programmes running mental health initiatives.", fr: "Prévu : équipement subventionné pour les programmes de BJJ menant des initiatives de santé mentale.", ja: "予定：メンタルヘルス活動を行うBJJプログラムへのギア支援。", pt: "Planejado: equipamento subsidiado para programas de BJJ com iniciativas de saúde mental.", ro: "Planificat: echipament subvenționat pentru programele de BJJ care derulează inițiative de sănătate mintală." } },
      { icon: "🥋", title: { en: "The Mental Health Roll", fr: "Le \"Mental Health Roll\"", ja: "メンタルヘルス・ロール", pt: "O \"Mental Health Roll\"", ro: "„Mental Health Roll”" },
        body: { en: "Planned: an annual charity open mat, with proceeds to support local mental health organisations.", fr: "Prévu : un tournoi caritatif annuel en accès libre, dont les recettes soutiendront des organisations locales de santé mentale.", ja: "予定：地元のメンタルヘルス団体を支援する年次チャリティーオープンマット。", pt: "Planejado: um evento de tatame aberto anual beneficente, com receitas para apoiar organizações locais de saúde mental.", ro: "Planificat: un eveniment caritabil anual de antrenament liber, cu încasările care vor susține organizații locale de sănătate mintală." } },
    ],
    designTitle:  { en: "Design Language", fr: "Langage de design", ja: "デザイン言語", pt: "Linguagem de Design", ro: "Limbaj de design" },
    designBody:   { en: "Collections draw on visual themes from neuroscience and psychology — neural network and synaptic patterns, brain anatomy reimagined through the lens of BJJ, and clinical, academic typography that reinforces the \"study of\" concept. Dark, premium colourways with high-contrast accents — minimal, purposeful, never loud.", fr: "Les collections s'inspirent de thèmes visuels issus des neurosciences et de la psychologie — motifs de réseaux neuronaux et synaptiques, anatomie du cerveau réinterprétée à travers le prisme du BJJ, et typographie clinique et académique renforçant le concept d'« étude ». Des teintes sombres et haut de gamme avec des accents à fort contraste — minimalistes, réfléchies, jamais criardes.", ja: "コレクションは神経科学と心理学からの視覚的テーマを取り入れています — ニューラルネットワークやシナプスのパターン、BJJの視点から再解釈された脳解剖学、そして「探求」というコンセプトを強調する臨床的・学術的なタイポグラフィ。ダークで上質なカラーウェイに高コントラストのアクセント — ミニマルで意図的、決して派手ではありません。", pt: "As coleções se inspiram em temas visuais da neurociência e da psicologia — padrões de redes neurais e sinápticas, anatomia cerebral reimaginada pela lente do BJJ, e tipografia clínica e acadêmica que reforça o conceito de \"estudo\". Paletas escuras e premium com acentos de alto contraste — minimalistas, propositais, nunca exageradas.", ro: "Colecțiile se inspiră din teme vizuale din neuroștiințe și psihologie — modele de rețele neuronale și sinaptice, anatomie cerebrală reinterpretată prin prisma BJJ și tipografie clinică, academică, ce reîntărește conceptul de „studiu”. Culori închise, premium, cu accente de contrast ridicat — minimaliste, cu scop, niciodată stridente." },
    supportNote:  { en: "If you or someone you know is struggling, support is available. Samaritans of Singapore (SOS): 1-767, 24 hours.", fr: "Si vous ou une personne de votre entourage traversez une période difficile, de l'aide est disponible. Samaritans of Singapore (SOS) : 1-767, 24h/24.", ja: "もしあなたや身近な人が困難を抱えている場合、サポートを受けることができます。Samaritans of Singapore (SOS)：1-767、24時間対応。", pt: "Se você ou alguém que você conhece estiver enfrentando dificuldades, há apoio disponível. Samaritans of Singapore (SOS): 1-767, 24 horas.", ro: "Dacă tu sau cineva pe care îl cunoști treci printr-o perioadă dificilă, există sprijin disponibil. Samaritans of Singapore (SOS): 1-767, non-stop." },
  },

  // ── STRENGTH & CONDITIONING ─────────────────────────────────────────────
  sc: {
    pageTag:      { en: "Program Builder", fr: "Générateur de Programme", ja: "プログラムビルダー", pt: "Gerador de Programa", ro: "Generator de Program" },
    pageTitle:    { en: "Strength & Conditioning", fr: "Force & Préparation Physique", ja: "筋力・コンディショニング", pt: "Força & Condicionamento", ro: "Forță & Pregătire Fizică" },
    pageSubtitle: { en: "A conditioning program built for the demands of BJJ — not a generic gym plan. Tell us your age range, fitness level and available equipment, and we'll build the specific session for you.", fr: "Un programme de préparation physique pensé pour les exigences du BJJ — pas un plan de salle générique. Indiquez votre tranche d'âge, votre niveau et votre équipement disponible, et nous construirons la séance qui vous correspond.", ja: "BJJの要求に特化したコンディショニングプログラムです — 一般的なジムプランではありません。年齢層、フィットネスレベル、使用可能な器具を選択すると、あなた専用のセッションを作成します。", pt: "Um programa de condicionamento feito para as exigências do BJJ — não um plano genérico de academia. Informe sua faixa etária, nível de condicionamento e equipamento disponível, e montaremos a sessão específica para você.", ro: "Un program de pregătire fizică construit pentru cerințele BJJ — nu un plan generic de sală. Spune-ne intervalul tău de vârstă, nivelul de fitness și echipamentul disponibil, iar noi vom construi sesiunea potrivită pentru tine." },
    ageLabel:     { en: "Age",     fr: "Âge",       ja: "年齢",     pt: "Idade",       ro: "Vârstă" },
    levelLabel:   { en: "Level",   fr: "Niveau",    ja: "レベル",   pt: "Nível",       ro: "Nivel" },
    typeLabel:    { en: "Equipment", fr: "Équipement", ja: "器具",   pt: "Equipamento", ro: "Echipament" },
    ageOptions: {
      "<20":  { en: "Under 20",   fr: "Moins de 20 ans", ja: "20歳未満",   pt: "Menos de 20", ro: "Sub 20 de ani" },
      "20-30":{ en: "20 – 30",    fr: "20 – 30 ans",     ja: "20〜30歳",   pt: "20 – 30",     ro: "20 – 30 de ani" },
      "30-40":{ en: "30 – 40",    fr: "30 – 40 ans",     ja: "30〜40歳",   pt: "30 – 40",     ro: "30 – 40 de ani" },
      "40-50":{ en: "40 – 50",    fr: "40 – 50 ans",     ja: "40〜50歳",   pt: "40 – 50",     ro: "40 – 50 de ani" },
      "50-60":{ en: "50 – 60",    fr: "50 – 60 ans",     ja: "50〜60歳",   pt: "50 – 60",     ro: "50 – 60 de ani" },
      ">60":  { en: "Over 60",    fr: "Plus de 60 ans",  ja: "60歳以上",   pt: "Mais de 60",  ro: "Peste 60 de ani" },
    },
    typeOptions: {
      Calisthenics: { en: "No Equipment",  fr: "Sans Équipement",  ja: "器具なし",       pt: "Sem Equipamento", ro: "Fără Echipament" },
      Equipment:    { en: "With Equipment", fr: "Avec Équipement", ja: "器具あり",       pt: "Com Equipamento", ro: "Cu Echipament" },
    },
    generateBtn:  { en: "Build My Program", fr: "Générer mon Programme", ja: "プログラムを作成", pt: "Gerar Meu Programa", ro: "Generează Programul" },
    incomplete:   { en: "Select an age range, a fitness level, and an equipment option to generate your program.", fr: "Sélectionnez une tranche d'âge, un niveau et une option d'équipement pour générer votre programme.", ja: "年齢層、フィットネスレベル、器具オプションを選択してプログラムを作成してください。", pt: "Selecione uma faixa etária, um nível e uma opção de equipamento para gerar seu programa.", ro: "Selectează un interval de vârstă, un nivel și o opțiune de echipament pentru a genera programul." },
    resultTag:    { en: "Your Program", fr: "Votre Programme", ja: "あなたのプログラム", pt: "Seu Programa", ro: "Programul Tău" },
    editBtn:      { en: "← Change Inputs", fr: "← Modifier les critères", ja: "← 入力を変更", pt: "← Alterar Critérios", ro: "← Modifică Criteriile" },
    frequencyLbl: { en: "Suggested Frequency", fr: "Fréquence Suggérée", ja: "推奨頻度", pt: "Frequência Sugerida", ro: "Frecvență Sugerată" },
    perWeek:      { en: "sessions / week", fr: "séances / semaine", ja: "回／週", pt: "sessões / semana", ro: "sesiuni / săptămână" },
    warmupTitle:  { en: "Warm-Up", fr: "Échauffement", ja: "ウォームアップ", pt: "Aquecimento", ro: "Încălzire" },
    lowerTitle:   { en: "Lower Body", fr: "Bas du Corps", ja: "下半身", pt: "Membros Inferiores", ro: "Partea Inferioară" },
    upperPushTitle:{ en: "Upper Body — Push", fr: "Haut du Corps — Poussée", ja: "上半身（プッシュ）", pt: "Superior — Empurrar", ro: "Partea Superioară — Împins" },
    upperPullTitle:{ en: "Upper Body — Pull", fr: "Haut du Corps — Tirage", ja: "上半身（プル）", pt: "Superior — Puxar", ro: "Partea Superioară — Tras" },
    coreTitle:    { en: "Core", fr: "Gainage", ja: "体幹", pt: "Core", ro: "Trunchi" },
    conditioningTitle: { en: "Conditioning", fr: "Préparation Physique", ja: "コンディショニング", pt: "Condicionamento", ro: "Pregătire Fizică" },
    cooldownTitle:{ en: "Cooldown & Mobility", fr: "Retour au Calme & Mobilité", ja: "クールダウン・可動域", pt: "Volta à Calma & Mobilidade", ro: "Revenire & Mobilitate" },
    notesTitle:   { en: "Notes for Your Age Group", fr: "Remarques pour votre tranche d'âge", ja: "年齢層別の注意事項", pt: "Notas para sua Faixa Etária", ro: "Observații pentru grupa ta de vârstă" },
    disclaimer:   { en: "This is general fitness guidance, not medical advice. Stop any exercise that causes pain and consult a physician before starting a new training program, especially if you have an existing injury or health condition.", fr: "Ceci est une orientation générale, pas un avis médical. Arrêtez tout exercice provoquant une douleur et consultez un médecin avant de commencer un nouveau programme, surtout en cas de blessure ou de problème de santé existant.", ja: "これは一般的なフィットネス指針であり、医学的助言ではありません。痛みを伴う運動は中止し、新しいトレーニングプログラムを開始する前に、特に既往症や健康上の問題がある場合は医師にご相談ください。", pt: "Esta é uma orientação geral de condicionamento físico, não um conselho médico. Interrompa qualquer exercício que cause dor e consulte um médico antes de iniciar um novo programa, especialmente se tiver uma lesão ou condição de saúde existente.", ro: "Acesta este un ghid general de fitness, nu un sfat medical. Oprește orice exercițiu care provoacă durere și consultă un medic înainte de a începe un program nou, mai ales dacă ai o accidentare sau o afecțiune medicală existentă." },
    restLbl:      { en: "Rest", fr: "Repos", ja: "休憩", pt: "Descanso", ro: "Odihnă" },
    ageNotes: {
      "<20":  { en: "Prioritise movement quality and full range of motion over load — your body is still developing. Technique before intensity.", fr: "Privilégiez la qualité du mouvement et l'amplitude complète plutôt que la charge — votre corps est encore en développement. La technique avant l'intensité.", ja: "身体はまだ発達段階にあるため、負荷よりも動作の質と可動域を優先してください。強度よりも技術を重視しましょう。", pt: "Priorize a qualidade do movimento e a amplitude completa em vez da carga — seu corpo ainda está se desenvolvendo. Técnica antes da intensidade.", ro: "Acordă prioritate calității mișcării și amplitudinii complete în locul încărcăturii — corpul tău este încă în dezvoltare. Tehnica înaintea intensității." },
      "20-30":{ en: "This is typically peak physical capacity — a good window to push intensity and volume, provided recovery keeps pace with training.", fr: "C'est généralement le pic de capacité physique — une bonne fenêtre pour augmenter l'intensité et le volume, à condition que la récupération suive l'entraînement.", ja: "一般的に身体能力のピークにあたる時期です — 回復がトレーニングに見合っていれば、強度と量を高める良い機会です。", pt: "Esta é tipicamente a capacidade física máxima — uma boa janela para aumentar intensidade e volume, desde que a recuperação acompanhe o treino.", ro: "Aceasta este de obicei perioada de vârf a capacității fizice — o fereastră bună pentru a crește intensitatea și volumul, cu condiția ca recuperarea să țină pasul cu antrenamentul." },
      "30-40":{ en: "Consistency matters more than peak intensity now. Add a few extra minutes of mobility work before heavy training days.", fr: "La régularité compte désormais plus que l'intensité maximale. Ajoutez quelques minutes de mobilité supplémentaires avant les journées d'entraînement intense.", ja: "今の時期は最大強度よりも継続性が重要です。強度の高いトレーニング日の前には、数分間可動域トレーニングを追加しましょう。", pt: "Consistência importa mais que intensidade máxima agora. Adicione alguns minutos extras de mobilidade antes dos dias de treino intenso.", ro: "Consecvența contează acum mai mult decât intensitatea maximă. Adaugă câteva minute suplimentare de mobilitate înainte de zilele de antrenament intens." },
      "40-50":{ en: "Recovery matters more than it used to — prioritise sleep, don't skip warm-ups, and back off if joints feel irritated rather than just tired.", fr: "La récupération compte plus qu'avant — privilégiez le sommeil, ne sautez pas l'échauffement, et levez le pied si les articulations semblent irritées plutôt que simplement fatiguées.", ja: "以前よりも回復が重要になります — 睡眠を優先し、ウォームアップを省略せず、関節に単なる疲労以上の違和感がある場合は強度を落としましょう。", pt: "A recuperação importa mais do que antes — priorize o sono, não pule o aquecimento e reduza a intensidade se as articulações parecerem irritadas, não apenas cansadas.", ro: "Recuperarea contează acum mai mult decât înainte — acordă prioritate somnului, nu sări peste încălzire și redu intensitatea dacă articulațiile par iritate, nu doar obosite." },
      "50-60":{ en: "High-impact and explosive movements have been swapped for joint-friendly alternatives below. If you're new to structured exercise, check with a physician before starting.", fr: "Les mouvements à fort impact et explosifs ont été remplacés ci-dessous par des alternatives plus douces pour les articulations. Si vous débutez l'exercice structuré, consultez un médecin avant de commencer.", ja: "以下では、高衝撃・爆発的な動作を関節に優しい代替種目に置き換えています。構造化されたトレーニングが初めての場合は、開始前に医師にご相談ください。", pt: "Movimentos de alto impacto e explosivos foram substituídos abaixo por alternativas mais amigáveis às articulações. Se você é novo em exercícios estruturados, consulte um médico antes de começar.", ro: "Mișcările cu impact ridicat și explozive au fost înlocuite mai jos cu alternative prietenoase pentru articulații. Dacă ești nou în exercițiul structurat, consultă un medic înainte de a începe." },
      ">60":  { en: "This program is built around control, balance and joint health rather than load. Please consult a physician before beginning, especially if returning to training after a break.", fr: "Ce programme est construit autour du contrôle, de l'équilibre et de la santé articulaire plutôt que de la charge. Veuillez consulter un médecin avant de commencer, surtout en cas de reprise après une pause.", ja: "このプログラムは負荷よりもコントロール、バランス、関節の健康を中心に構成されています。特に休止期間後にトレーニングを再開する場合は、開始前に必ず医師にご相談ください。", pt: "Este programa é construído em torno de controle, equilíbrio e saúde articular, em vez de carga. Consulte um médico antes de começar, especialmente se estiver retomando o treino após uma pausa.", ro: "Acest program este construit în jurul controlului, echilibrului și sănătății articulațiilor, nu al încărcăturii. Te rugăm să consulți un medic înainte de a începe, mai ales dacă reiei antrenamentul după o pauză." },
    },
    ex: {
      armLegSwings:      { en: "Arm & leg swings",          fr: "Balancés bras & jambes",       ja: "腕・脚振り",              pt: "Balanços de braço e perna", ro: "Balansări brațe și picioare" },
      hipRotations:      { en: "Hip 90/90 rotations",        fr: "Rotations de hanche 90/90",    ja: "股関節90/90回旋",         pt: "Rotações de quadril 90/90", ro: "Rotații de șold 90/90" },
      neckShoulderRolls: { en: "Neck & shoulder rolls",      fr: "Rotations nuque & épaules",    ja: "首・肩回し",              pt: "Rotações de pescoço e ombro", ro: "Rotații gât și umeri" },
      bodyweightSquat:   { en: "Bodyweight squat",           fr: "Squat au poids du corps",      ja: "自重スクワット",          pt: "Agachamento livre",        ro: "Genuflexiune cu greutate proprie" },
      bulgarianSplitSquat:{ en: "Bulgarian split squat",     fr: "Fente bulgare",                ja: "ブルガリアンスクワット", pt: "Agachamento búlgaro",      ro: "Genuflexiune bulgărească" },
      broadJump:         { en: "Broad jump",                 fr: "Saut en longueur",             ja: "幅跳び",                  pt: "Salto em distância",       ro: "Săritură în lungime" },
      stepUp:            { en: "Step-up",                    fr: "Montée sur banc",              ja: "ステップアップ",          pt: "Subida no banco",          ro: "Urcare pe bancă" },
      wallSit:           { en: "Wall sit",                   fr: "Chaise contre le mur",         ja: "ウォールシット",          pt: "Cadeira na parede",        ro: "Scaun la perete" },
      gobletSquat:       { en: "Goblet squat",                fr: "Squat goblet",                 ja: "ゴブレットスクワット",   pt: "Agachamento goblet",       ro: "Genuflexiune goblet" },
      romanianDeadliftDB:{ en: "Dumbbell Romanian deadlift", fr: "Soulevé de terre roumain haltères", ja: "ダンベル・ルーマニアンデッドリフト", pt: "Levantamento terra romeno com halteres", ro: "Îndreptări românești cu gantere" },
      walkingLunge:      { en: "Walking lunge",               fr: "Fente marchée",                ja: "ウォーキングランジ",     pt: "Avanço caminhando",        ro: "Fandare în mers" },
      dbStepUp:          { en: "Dumbbell step-up",            fr: "Montée sur banc haltères",     ja: "ダンベル・ステップアップ", pt: "Subida no banco com halteres", ro: "Urcare pe bancă cu gantere" },
      pushUp:            { en: "Push-up",                     fr: "Pompe",                        ja: "腕立て伏せ",              pt: "Flexão de braço",          ro: "Flotare" },
      pikePushUp:        { en: "Pike push-up",                 fr: "Pompe piquée",                 ja: "パイクプッシュアップ",   pt: "Flexão pike",              ro: "Flotare pike" },
      benchDip:          { en: "Bench dip",                    fr: "Dips sur banc",                 ja: "ベンチディップス",       pt: "Mergulho no banco",        ro: "Flotări la bancă (triceps)" },
      dbBenchPress:      { en: "Dumbbell bench press",        fr: "Développé couché haltères",    ja: "ダンベルベンチプレス",   pt: "Supino com halteres",      ro: "Împins la piept cu gantere" },
      dbOverheadPress:   { en: "Dumbbell overhead press",     fr: "Développé militaire haltères", ja: "ダンベルショルダープレス", pt: "Desenvolvimento com halteres", ro: "Împins deasupra capului cu gantere" },
      tricepExtension:   { en: "Dumbbell tricep extension",   fr: "Extension triceps haltère",    ja: "ダンベル・トライセップエクステンション", pt: "Extensão de tríceps com halteres", ro: "Extensii triceps cu ganteră" },
      towelRow:          { en: "Doorway towel row",            fr: "Tirage serviette porte",        ja: "タオルドア・ロウ",       pt: "Remada com toalha na porta", ro: "Tracțiune cu prosop la ușă" },
      supermanHold:      { en: "Superman hold",                fr: "Gainage superman",              ja: "スーパーマンホールド",   pt: "Prancha superman",         ro: "Extensie superman" },
      invertedRowChair:  { en: "Table/sturdy-edge inverted row", fr: "Tirage inversé sous table",  ja: "テーブル・インバーテッドロウ", pt: "Remada invertida na mesa", ro: "Tracțiune inversată la masă" },
      bentOverRow:       { en: "Dumbbell bent-over row",       fr: "Rowing buste penché haltères", ja: "ダンベル・ベントオーバーロウ", pt: "Remada curvada com halteres", ro: "Ramat aplecat cu gantere" },
      latPulldownOrPullup:{ en: "Pull-up / lat pulldown",      fr: "Traction / tirage vertical",   ja: "懸垂／ラットプルダウン", pt: "Barra fixa / puxada alta", ro: "Tracțiuni / tras la helcometru" },
      facePullBand:      { en: "Band face pull",               fr: "Face pull élastique",           ja: "バンド・フェイスプル",   pt: "Face pull com elástico",   ro: "Tracțiune la față cu bandă" },
      plank:             { en: "Plank",                        fr: "Gainage planche",               ja: "プランク",               pt: "Prancha",                  ro: "Scândură (plank)" },
      deadBug:           { en: "Dead bug",                     fr: "Dead bug",                       ja: "デッドバグ",             pt: "Dead bug",                 ro: "Dead bug" },
      sidePlank:         { en: "Side plank",                   fr: "Gainage latéral",                ja: "サイドプランク",         pt: "Prancha lateral",          ro: "Scândură laterală" },
      weightedPlank:     { en: "Weighted plank",                fr: "Planche lestée",                 ja: "加重プランク",           pt: "Prancha com peso",         ro: "Scândură cu greutate" },
      palloffPress:      { en: "Band Pallof press",             fr: "Pallof press élastique",         ja: "バンド・パロフプレス",   pt: "Pallof press com elástico", ro: "Pallof press cu bandă" },
      farmerCarry:       { en: "Farmer's carry",                fr: "Marche du fermier",              ja: "ファーマーズキャリー",   pt: "Farmer's carry",           ro: "Farmer's carry" },
      burpee:            { en: "Burpee",                        fr: "Burpee",                         ja: "バーピー",               pt: "Burpee",                   ro: "Burpee" },
      mountainClimber:   { en: "Mountain climber",              fr: "Mountain climber",               ja: "マウンテンクライマー",   pt: "Mountain climber",         ro: "Mountain climber" },
      jumpingJack:       { en: "Jumping jack",                  fr: "Jumping jack",                   ja: "ジャンピングジャック",   pt: "Polichinelo",              ro: "Jumping jack" },
      marchInPlace:      { en: "March in place",                fr: "Marche sur place",                ja: "その場足踏み",           pt: "Marcha estacionária",      ro: "Mers pe loc" },
      sitToStand:        { en: "Sit-to-stand",                  fr: "Assis-debout",                    ja: "サイド・トゥ・スタンド", pt: "Sentar e levantar",        ro: "Așezat-ridicat" },
      stepTouch:         { en: "Step-touch",                    fr: "Pas chassé",                      ja: "ステップタッチ",         pt: "Passo lateral",            ro: "Pas lateral" },
      kettlebellSwing:   { en: "Kettlebell swing",              fr: "Kettlebell swing",                ja: "ケトルベルスイング",     pt: "Kettlebell swing",         ro: "Kettlebell swing" },
      rowMachineInterval:{ en: "Rowing machine intervals",     fr: "Intervalles rameur",              ja: "ローイングマシン・インターバル", pt: "Intervalos no remo", ro: "Intervale la vâslă" },
      battleRopes:       { en: "Battle ropes",                  fr: "Battle ropes",                    ja: "バトルロープ",           pt: "Battle ropes",             ro: "Battle ropes" },
      kettlebellSwingLight:{ en: "Light kettlebell swing",     fr: "Kettlebell swing léger",          ja: "軽量ケトルベルスイング", pt: "Kettlebell swing leve",    ro: "Kettlebell swing ușor" },
      rowMachineSteady:  { en: "Rowing machine, steady pace",  fr: "Rameur, allure régulière",        ja: "ローイングマシン（一定ペース）", pt: "Remo em ritmo constante", ro: "Vâslă, ritm constant" },
      farmerCarryInterval:{ en: "Farmer's carry intervals",    fr: "Intervalles marche du fermier",   ja: "ファーマーズキャリー・インターバル", pt: "Intervalos de farmer's carry", ro: "Intervale farmer's carry" },
      childsPose:        { en: "Child's pose",                  fr: "Posture de l'enfant",             ja: "チャイルドポーズ",       pt: "Postura da criança",       ro: "Poziția copilului" },
      hamstringStretch:  { en: "Hamstring stretch",             fr: "Étirement ischio-jambiers",       ja: "ハムストリングストレッチ", pt: "Alongamento de posterior de coxa", ro: "Întindere ischiogambieri" },
      hip9090Stretch:    { en: "90/90 hip stretch",             fr: "Étirement hanche 90/90",          ja: "90/90ヒップストレッチ", pt: "Alongamento de quadril 90/90", ro: "Întindere șold 90/90" },
      boxBreathing:      { en: "Box breathing",                 fr: "Respiration carrée",              ja: "ボックスブリージング",   pt: "Respiração quadrada",      ro: "Respirație în cutie" },
    },
  },

};

// Helper: get translation for current language
export function t(obj, lang) {
  if (!obj) return "";
  return obj[lang] || obj["en"] || "";
}
